/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMULTICOREFIELDS_H_
#define _OSGMULTICOREFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class MultiCore;

OSG_GEN_CONTAINERPTR(MultiCore);

/*! \ingroup GrpSystemFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<MultiCore *> :
    public FieldTraitsFCPtrBase<MultiCore *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<MultiCore *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFMultiCorePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFMultiCorePtr"; }
};

template<> inline
const Char8 *FieldTraits<MultiCore *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMultiCorePtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiCore *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMultiCorePtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiCore *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMultiCorePtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiCore *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMultiCorePtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiCore *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMultiCorePtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiCore *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMultiCorePtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiCore *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMultiCorePtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiCore *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMultiCorePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MultiCore *,
                      RecordedRefCountPolicy  > SFRecMultiCorePtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MultiCore *,
                      UnrecordedRefCountPolicy> SFUnrecMultiCorePtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MultiCore *,
                      WeakRefCountPolicy      > SFWeakMultiCorePtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MultiCore *,
                      NoRefCountPolicy        > SFUncountedMultiCorePtr;


/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<MultiCore *,
                      RecordedRefCountPolicy  > MFRecMultiCorePtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<MultiCore *,
                      UnrecordedRefCountPolicy> MFUnrecMultiCorePtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<MultiCore *,
                      WeakRefCountPolicy      > MFWeakMultiCorePtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<MultiCore *,
                      NoRefCountPolicy        > MFUncountedMultiCorePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecMultiCorePtr : 
    public PointerSField<MultiCore *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecMultiCorePtr : 
    public PointerSField<MultiCore *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakMultiCorePtr :
    public PointerSField<MultiCore *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedMultiCorePtr :
    public PointerSField<MultiCore *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecMultiCorePtr :
    public PointerMField<MultiCore *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecMultiCorePtr :
    public PointerMField<MultiCore *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakMultiCorePtr :
    public PointerMField<MultiCore *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedMultiCorePtr :
    public PointerMField<MultiCore *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMULTICOREFIELDS_H_ */
