/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class HardwareSkinningDataAttachment!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGShaderProgramChunk.h"      // ShaderCode Class

#include "OSGHardwareSkinningDataAttachmentBase.h"
#include "OSGHardwareSkinningDataAttachment.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::HardwareSkinningDataAttachment
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var ShaderProgramChunk * HardwareSkinningDataAttachmentBase::_sfShaderCode
    
*/

/*! \var bool            HardwareSkinningDataAttachmentBase::_sfDataValid
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<HardwareSkinningDataAttachment *>::_type("HardwareSkinningDataAttachmentPtr", "AttachmentPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(HardwareSkinningDataAttachment *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           HardwareSkinningDataAttachment *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           HardwareSkinningDataAttachment *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void HardwareSkinningDataAttachmentBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecShaderProgramChunkPtr::Description(
        SFUnrecShaderProgramChunkPtr::getClassType(),
        "shaderCode",
        "",
        ShaderCodeFieldId, ShaderCodeFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&HardwareSkinningDataAttachment::editHandleShaderCode),
        static_cast<FieldGetMethodSig >(&HardwareSkinningDataAttachment::getHandleShaderCode));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "dataValid",
        "",
        DataValidFieldId, DataValidFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&HardwareSkinningDataAttachment::editHandleDataValid),
        static_cast<FieldGetMethodSig >(&HardwareSkinningDataAttachment::getHandleDataValid));

    oType.addInitialDesc(pDesc);
}


HardwareSkinningDataAttachmentBase::TypeObject HardwareSkinningDataAttachmentBase::_type(
    HardwareSkinningDataAttachmentBase::getClassname(),
    Inherited::getClassname(),
    "HardwareSkinningDataAttachment",
    0,
    reinterpret_cast<PrototypeCreateF>(&HardwareSkinningDataAttachmentBase::createEmptyLocal),
    HardwareSkinningDataAttachment::initMethod,
    HardwareSkinningDataAttachment::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&HardwareSkinningDataAttachment::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"HardwareSkinningDataAttachment\"\n"
    "   parent=\"Attachment\"\n"
    "   library=\"Dynamics\"\n"
    "   pointerfieldtypes=\"both\"\n"
    "   structure=\"concrete\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   decoratable=\"false\"\n"
    "   childFields=\"none\"\n"
    "   parentFields=\"none\"\n"
    ">\n"
    "  <Field\n"
    "     name=\"shaderCode\"\n"
    "     type=\"ShaderProgramChunk\"\n"
    "     category=\"pointer\"\n"
    "     cardinality=\"single\"\n"
    "     visibility=\"external\"\n"
    "     access=\"public\"\n"
    "     defaultValue=\"NULL\"\n"
    "     >\n"
    "  </Field>\n"
    "\n"
    "  <Field\n"
    "     name=\"dataValid\"\n"
    "     type=\"bool\"\n"
    "     category=\"data\"\n"
    "     cardinality=\"single\"\n"
    "     visibility=\"external\"\n"
    "     access=\"public\"\n"
    "     defaultValue=\"false\"\n"
    "     >\n"
    "  </Field>\n"
    "\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &HardwareSkinningDataAttachmentBase::getType(void)
{
    return _type;
}

const FieldContainerType &HardwareSkinningDataAttachmentBase::getType(void) const
{
    return _type;
}

UInt32 HardwareSkinningDataAttachmentBase::getContainerSize(void) const
{
    return sizeof(HardwareSkinningDataAttachment);
}

/*------------------------- decorator get ------------------------------*/


//! Get the HardwareSkinningDataAttachment::_sfShaderCode field.
const SFUnrecShaderProgramChunkPtr *HardwareSkinningDataAttachmentBase::getSFShaderCode(void) const
{
    return &_sfShaderCode;
}

SFUnrecShaderProgramChunkPtr *HardwareSkinningDataAttachmentBase::editSFShaderCode     (void)
{
    editSField(ShaderCodeFieldMask);

    return &_sfShaderCode;
}

SFBool *HardwareSkinningDataAttachmentBase::editSFDataValid(void)
{
    editSField(DataValidFieldMask);

    return &_sfDataValid;
}

const SFBool *HardwareSkinningDataAttachmentBase::getSFDataValid(void) const
{
    return &_sfDataValid;
}






/*------------------------------ access -----------------------------------*/

UInt32 HardwareSkinningDataAttachmentBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ShaderCodeFieldMask & whichField))
    {
        returnValue += _sfShaderCode.getBinSize();
    }
    if(FieldBits::NoField != (DataValidFieldMask & whichField))
    {
        returnValue += _sfDataValid.getBinSize();
    }

    return returnValue;
}

void HardwareSkinningDataAttachmentBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ShaderCodeFieldMask & whichField))
    {
        _sfShaderCode.copyToBin(pMem);
    }
    if(FieldBits::NoField != (DataValidFieldMask & whichField))
    {
        _sfDataValid.copyToBin(pMem);
    }
}

void HardwareSkinningDataAttachmentBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ShaderCodeFieldMask & whichField))
    {
        editSField(ShaderCodeFieldMask);
        _sfShaderCode.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (DataValidFieldMask & whichField))
    {
        editSField(DataValidFieldMask);
        _sfDataValid.copyFromBin(pMem);
    }
}

//! create a new instance of the class
HardwareSkinningDataAttachmentTransitPtr HardwareSkinningDataAttachmentBase::createLocal(BitVector bFlags)
{
    HardwareSkinningDataAttachmentTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<HardwareSkinningDataAttachment>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
HardwareSkinningDataAttachmentTransitPtr HardwareSkinningDataAttachmentBase::createDependent(BitVector bFlags)
{
    HardwareSkinningDataAttachmentTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<HardwareSkinningDataAttachment>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
HardwareSkinningDataAttachmentTransitPtr HardwareSkinningDataAttachmentBase::create(void)
{
    HardwareSkinningDataAttachmentTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<HardwareSkinningDataAttachment>(tmpPtr);
    }

    return fc;
}

HardwareSkinningDataAttachment *HardwareSkinningDataAttachmentBase::createEmptyLocal(BitVector bFlags)
{
    HardwareSkinningDataAttachment *returnValue;

    newPtr<HardwareSkinningDataAttachment>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
HardwareSkinningDataAttachment *HardwareSkinningDataAttachmentBase::createEmpty(void)
{
    HardwareSkinningDataAttachment *returnValue;

    newPtr<HardwareSkinningDataAttachment>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr HardwareSkinningDataAttachmentBase::shallowCopyLocal(
    BitVector bFlags) const
{
    HardwareSkinningDataAttachment *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const HardwareSkinningDataAttachment *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr HardwareSkinningDataAttachmentBase::shallowCopyDependent(
    BitVector bFlags) const
{
    HardwareSkinningDataAttachment *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const HardwareSkinningDataAttachment *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr HardwareSkinningDataAttachmentBase::shallowCopy(void) const
{
    HardwareSkinningDataAttachment *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const HardwareSkinningDataAttachment *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

HardwareSkinningDataAttachmentBase::HardwareSkinningDataAttachmentBase(void) :
    Inherited(),
    _sfShaderCode             (NULL),
    _sfDataValid              (bool(false))
{
}

HardwareSkinningDataAttachmentBase::HardwareSkinningDataAttachmentBase(const HardwareSkinningDataAttachmentBase &source) :
    Inherited(source),
    _sfShaderCode             (NULL),
    _sfDataValid              (source._sfDataValid              )
{
}


/*-------------------------- destructors ----------------------------------*/

HardwareSkinningDataAttachmentBase::~HardwareSkinningDataAttachmentBase(void)
{
}

void HardwareSkinningDataAttachmentBase::onCreate(const HardwareSkinningDataAttachment *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        HardwareSkinningDataAttachment *pThis = static_cast<HardwareSkinningDataAttachment *>(this);

        pThis->setShaderCode(source->getShaderCode());
    }
}

GetFieldHandlePtr HardwareSkinningDataAttachmentBase::getHandleShaderCode      (void) const
{
    SFUnrecShaderProgramChunkPtr::GetHandlePtr returnValue(
        new  SFUnrecShaderProgramChunkPtr::GetHandle(
             &_sfShaderCode,
             this->getType().getFieldDesc(ShaderCodeFieldId),
             const_cast<HardwareSkinningDataAttachmentBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr HardwareSkinningDataAttachmentBase::editHandleShaderCode     (void)
{
    SFUnrecShaderProgramChunkPtr::EditHandlePtr returnValue(
        new  SFUnrecShaderProgramChunkPtr::EditHandle(
             &_sfShaderCode,
             this->getType().getFieldDesc(ShaderCodeFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&HardwareSkinningDataAttachment::setShaderCode,
                    static_cast<HardwareSkinningDataAttachment *>(this), _1));

    editSField(ShaderCodeFieldMask);

    return returnValue;
}

GetFieldHandlePtr HardwareSkinningDataAttachmentBase::getHandleDataValid       (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfDataValid,
             this->getType().getFieldDesc(DataValidFieldId),
             const_cast<HardwareSkinningDataAttachmentBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr HardwareSkinningDataAttachmentBase::editHandleDataValid      (void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfDataValid,
             this->getType().getFieldDesc(DataValidFieldId),
             this));


    editSField(DataValidFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void HardwareSkinningDataAttachmentBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    HardwareSkinningDataAttachment *pThis = static_cast<HardwareSkinningDataAttachment *>(this);

    pThis->execSync(static_cast<HardwareSkinningDataAttachment *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *HardwareSkinningDataAttachmentBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    HardwareSkinningDataAttachment *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const HardwareSkinningDataAttachment *>(pRefAspect),
                  dynamic_cast<const HardwareSkinningDataAttachment *>(this));

    return returnValue;
}
#endif

void HardwareSkinningDataAttachmentBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<HardwareSkinningDataAttachment *>(this)->setShaderCode(NULL);


}


OSG_END_NAMESPACE
