# - Find Cg Toolkit
# Find the native Cg Toolkit includes and library
# This module defines
#  CG_INCLUDE_DIR, where to find cg.h, etc.
#  CG_LIBRARIES, the libraries needed to use JPEG.
#  CG_FOUND, If false, do not try to use Cg.
# also defined, but not for general use are
#  CG_LIBRARY, where to find the JPEG library.

FIND_PATH(CG_INCLUDE_DIR Cg/cg.h)

SET(CG_NAMES_RELEASE ${CG_NAMES_RELEASE} libCg)
FIND_LIBRARY(CG_LIBRARY_RELEASE NAMES ${CG_NAMES_RELEASE} )

SET(CG_NAMES_DEBUG ${CG_NAMES_DEBUG} libCgd)
FIND_LIBRARY(CG_LIBRARY_DEBUG NAMES ${CG_NAMES_DEBUG} )

SET(CGGL_NAMES_RELEASE ${CGGL_NAMES_RELEASE} libCgGL)
FIND_LIBRARY(CGGL_LIBRARY_RELEASE NAMES ${CGGL_NAMES_RELEASE} )

SET(CGGL_NAMES_DEBUG ${CGGL_NAMES_DEBUG} libCgGLd)
FIND_LIBRARY(CGGL_LIBRARY_DEBUG NAMES ${CGGL_NAMES_DEBUG} )

IF(CG_LIBRARY_DEBUG AND CGGL_LIBRARY_DEBUG)
  SET(CG_LIBRARIES_FOUND TRUE)
  MARK_AS_ADVANCED(CG_LIBRARY_DEBUG)
ENDIF(CG_LIBRARY_DEBUG AND CGGL_LIBRARY_DEBUG)

IF(CG_LIBRARY_RELEASE AND CGGL_LIBRARY_RELEASE)
  SET(CG_LIBRARIES_FOUND TRUE)
  MARK_AS_ADVANCED(CG_LIBRARY_RELEASE)
ENDIF(CG_LIBRARY_RELEASE AND CGGL_LIBRARY_RELEASE)

# handle the QUIETLY and REQUIRED arguments and set CG_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CG DEFAULT_MSG 
                                  CG_LIBRARIES_FOUND 
                                  CG_INCLUDE_DIR)

