/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class RotateManipulator!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGConfig.h"




#include "OSGRotateManipulatorBase.h"
#include "OSGRotateManipulator.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::RotateManipulator
    The MoveHandle is used for moving objects. It consist of three axis which can be picked and translated and one center box to translate freely in 3D.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<RotateManipulator *, nsOSG>::_type(
    "RotateManipulatorPtr", 
    "ManipulatorPtr", 
    RotateManipulator::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(RotateManipulator *, nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void RotateManipulatorBase::classDescInserter(TypeObject &oType)
{
}


RotateManipulatorBase::TypeObject RotateManipulatorBase::_type(
    RotateManipulatorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&RotateManipulatorBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&RotateManipulator::initMethod),
    reinterpret_cast<ExitContainerF>(&RotateManipulator::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(
        reinterpret_cast<void *>(&RotateManipulator::classDescInserter)),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"RotateManipulator\"\n"
    "\tparent=\"Manipulator\"\n"
    "\tlibrary=\"ContribGUI\"\n"
    "\tpointerfieldtypes=\"none\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"true\"\n"
    "\tparentsystemcomponent=\"true\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"true\"\n"
    ">\n"
    "The MoveHandle is used for moving objects. It consist of three axis which can be picked and translated and one center box to translate freely in 3D.\n"
    "</FieldContainer>\n",
    "The MoveHandle is used for moving objects. It consist of three axis which can be picked and translated and one center box to translate freely in 3D.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &RotateManipulatorBase::getType(void)
{
    return _type;
}

const FieldContainerType &RotateManipulatorBase::getType(void) const
{
    return _type;
}

UInt32 RotateManipulatorBase::getContainerSize(void) const
{
    return sizeof(RotateManipulator);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT RotateManipulatorBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void RotateManipulatorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void RotateManipulatorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
RotateManipulatorTransitPtr RotateManipulatorBase::createLocal(BitVector bFlags)
{
    RotateManipulatorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<RotateManipulator>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
RotateManipulatorTransitPtr RotateManipulatorBase::createDependent(BitVector bFlags)
{
    RotateManipulatorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<RotateManipulator>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
RotateManipulatorTransitPtr RotateManipulatorBase::create(void)
{
    RotateManipulatorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<RotateManipulator>(tmpPtr);
    }

    return fc;
}

RotateManipulator *RotateManipulatorBase::createEmptyLocal(BitVector bFlags)
{
    RotateManipulator *returnValue;

    newPtr<RotateManipulator>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
RotateManipulator *RotateManipulatorBase::createEmpty(void)
{
    RotateManipulator *returnValue;

    newPtr<RotateManipulator>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr RotateManipulatorBase::shallowCopyLocal(
    BitVector bFlags) const
{
    RotateManipulator *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const RotateManipulator *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr RotateManipulatorBase::shallowCopyDependent(
    BitVector bFlags) const
{
    RotateManipulator *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const RotateManipulator *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr RotateManipulatorBase::shallowCopy(void) const
{
    RotateManipulator *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const RotateManipulator *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

RotateManipulatorBase::RotateManipulatorBase(void) :
    Inherited()
{
}

RotateManipulatorBase::RotateManipulatorBase(const RotateManipulatorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

RotateManipulatorBase::~RotateManipulatorBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void RotateManipulatorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    RotateManipulator *pThis = static_cast<RotateManipulator *>(this);

    pThis->execSync(static_cast<RotateManipulator *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *RotateManipulatorBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    RotateManipulator *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const RotateManipulator *>(pRefAspect),
                  dynamic_cast<const RotateManipulator *>(this));

    return returnValue;
}
#endif

void RotateManipulatorBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
