/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCSMNATIVEWINDOWFIELDS_H_
#define _OSGCSMNATIVEWINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribCSMDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class CSMNativeWindow;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! CSMNativeWindowPtr

OSG_GEN_CONTAINERPTR(CSMNativeWindow);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpContribCSMFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<CSMNativeWindow *> :
    public FieldTraitsFCPtrBase<CSMNativeWindow *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<CSMNativeWindow *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBCSM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFCSMNativeWindowPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFCSMNativeWindowPtr"; }
};

template<> inline
const Char8 *FieldTraits<CSMNativeWindow *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecCSMNativeWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMNativeWindow *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecCSMNativeWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMNativeWindow *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakCSMNativeWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMNativeWindow *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdCSMNativeWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMNativeWindow *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecCSMNativeWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMNativeWindow *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecCSMNativeWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMNativeWindow *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakCSMNativeWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMNativeWindow *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdCSMNativeWindowPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<CSMNativeWindowPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribCSMFieldSingle */

typedef PointerSField<CSMNativeWindow *,
                      RecordedRefCountPolicy  > SFRecCSMNativeWindowPtr;
typedef PointerSField<CSMNativeWindow *,
                      UnrecordedRefCountPolicy> SFUnrecCSMNativeWindowPtr;
typedef PointerSField<CSMNativeWindow *,
                      WeakRefCountPolicy      > SFWeakCSMNativeWindowPtr;
typedef PointerSField<CSMNativeWindow *,
                      NoRefCountPolicy        > SFUncountedCSMNativeWindowPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribCSMFieldMulti */

typedef PointerMField<CSMNativeWindow *,
                      RecordedRefCountPolicy  > MFRecCSMNativeWindowPtr;
typedef PointerMField<CSMNativeWindow *,
                      UnrecordedRefCountPolicy> MFUnrecCSMNativeWindowPtr;
typedef PointerMField<CSMNativeWindow *,
                      WeakRefCountPolicy      > MFWeakCSMNativeWindowPtr;
typedef PointerMField<CSMNativeWindow *,
                      NoRefCountPolicy        > MFUncountedCSMNativeWindowPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGCSMNATIVEWINDOWFIELDS_H_ */
