/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSKYBACKGROUNDFIELDS_H_
#define _OSGSKYBACKGROUNDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGWindowDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class SkyBackground;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! SkyBackgroundPtr

OSG_GEN_CONTAINERPTR(SkyBackground);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpWindowFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<SkyBackgroundPtr> :
    public FieldTraitsFCPtrBase<SkyBackgroundPtr>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SkyBackgroundPtr>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_WINDOW_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSkyBackgroundPtr"; }
};


template<> inline
const Char8 *FieldTraits<SkyBackgroundPtr, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSkyBackgroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkyBackgroundPtr, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSkyBackgroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkyBackgroundPtr, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSkyBackgroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkyBackgroundPtr, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSkyBackgroundPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<SkyBackgroundPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)



#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpWindowFieldMulti */

typedef PointerMField<SkyBackgroundPtr,
                      RecordedRefCountPolicy  > MFRecSkyBackgroundPtr;
typedef PointerMField<SkyBackgroundPtr,
                      UnrecordedRefCountPolicy> MFUnrecSkyBackgroundPtr;
typedef PointerMField<SkyBackgroundPtr,
                      WeakRefCountPolicy      > MFWeakSkyBackgroundPtr;
typedef PointerMField<SkyBackgroundPtr,
                      NoRefCountPolicy        > MFUncountedSkyBackgroundPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGSKYBACKGROUNDFIELDS_H_ */
