/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSHLPARAMETERCHUNKFIELDS_H_
#define _OSGSHLPARAMETERCHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGStateDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class SHLParameterChunk;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! SHLParameterChunkPtr

OSG_GEN_CONTAINERPTR(SHLParameterChunk);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpStateFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<SHLParameterChunk *> :
    public FieldTraitsFCPtrBase<SHLParameterChunk *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SHLParameterChunk *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_STATE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSHLParameterChunkPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSHLParameterChunkPtr"; }
};

template<> inline
const Char8 *FieldTraits<SHLParameterChunk *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSHLParameterChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SHLParameterChunk *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSHLParameterChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SHLParameterChunk *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSHLParameterChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SHLParameterChunk *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSHLParameterChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SHLParameterChunk *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSHLParameterChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SHLParameterChunk *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSHLParameterChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SHLParameterChunk *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSHLParameterChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SHLParameterChunk *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSHLParameterChunkPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<SHLParameterChunkPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpStateFieldSingle */

typedef PointerSField<SHLParameterChunk *,
                      RecordedRefCountPolicy  > SFRecSHLParameterChunkPtr;
typedef PointerSField<SHLParameterChunk *,
                      UnrecordedRefCountPolicy> SFUnrecSHLParameterChunkPtr;
typedef PointerSField<SHLParameterChunk *,
                      WeakRefCountPolicy      > SFWeakSHLParameterChunkPtr;
typedef PointerSField<SHLParameterChunk *,
                      NoRefCountPolicy        > SFUncountedSHLParameterChunkPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpStateFieldMulti */

typedef PointerMField<SHLParameterChunk *,
                      RecordedRefCountPolicy  > MFRecSHLParameterChunkPtr;
typedef PointerMField<SHLParameterChunk *,
                      UnrecordedRefCountPolicy> MFUnrecSHLParameterChunkPtr;
typedef PointerMField<SHLParameterChunk *,
                      WeakRefCountPolicy      > MFWeakSHLParameterChunkPtr;
typedef PointerMField<SHLParameterChunk *,
                      NoRefCountPolicy        > MFUncountedSHLParameterChunkPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGSHLPARAMETERCHUNKFIELDS_H_ */
