
MACRO(OSG_SETUP_CUDA_FLAGS)

 IF(NOT WIN32)
#  MESSAGE("FOOOXX ${CMAKE_CONFIGURATION_TYPES}")

  IF(NOT OSG_CUDA_DEFAULTS)
    SET(_OSG_CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} CACHE INTERNAL "Cuda defaults written" FORCE)

    FOREACH(_OSG_CFG_TYPE ${CMAKE_CONFIGURATION_TYPES})
      STRING(TOUPPER ${_OSG_CFG_TYPE} _OSG_CFG_TYPE)
      SET(_OSG_CUDA_NVCC_FLAGS_${_OSG_CFG_TYPE} ${CUDA_NVCC_FLAGS_${_OSG_CFG_TYPE}} CACHE INTERNAL "Cuda defaults written" FORCE)
    ENDFOREACH()

    SET(OSG_CUDA_DEFAULTS 1 CACHE INTERNAL "Cuda defaults written" FORCE) #INTERNAL
  ENDIF(NOT OSG_CUDA_DEFAULTS)

  SET(CUDA_NVCC_FLAGS ${_OSG_CUDA_NVCC_FLAGS};${CUDA_NVCC_OSG_FLAGS} CACHE STRING "" FORCE)


  IF(CMAKE_CXX_FLAGS)
    SET(_CUDA_NVCC_XC_FLAGS "-Xcompiler ")

    STRING(REPLACE " " ";" _OSG_CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})

    FOREACH(_OSG_CXX_FLAG ${_OSG_CMAKE_CXX_FLAGS})
      SET(_CUDA_NVCC_XC_FLAGS "${_CUDA_NVCC_XC_FLAGS},${_OSG_CXX_FLAG}")
    ENDFOREACH()

    STRING(REPLACE ",-std=c++11" "" _CUDA_NVCC_XC_FLAGS ${_CUDA_NVCC_XC_FLAGS})

    SET(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};${_CUDA_NVCC_XC_FLAGS}; CACHE STRING "" FORCE)
  ENDIF()

  FOREACH(_OSG_CFG_TYPE ${CMAKE_CONFIGURATION_TYPES})

    STRING(TOUPPER ${_OSG_CFG_TYPE} _OSG_CFG_TYPE)
    IF(CMAKE_CXX_FLAGS_${_OSG_CFG_TYPE})

      SET(CUDA_NVCC_FLAGS_${_OSG_CFG_TYPE} ${_OSG_CUDA_NVCC_FLAGS_${_OSG_CFG_TYPE}};${CUDA_NVCC_OSG_FLAGS_${_OSG_CFG_TYPE}} CACHE STRING "Cuda defaults written" FORCE)

      SET(_CUDA_NVCC_XC_FLAGS "-Xcompiler ")

      STRING(REPLACE " " ";" _OSG_CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS_${_OSG_CFG_TYPE}})

      FOREACH(_OSG_CXX_FLAG ${_OSG_CMAKE_CXX_FLAGS})
        SET(_CUDA_NVCC_XC_FLAGS "${_CUDA_NVCC_XC_FLAGS},${_OSG_CXX_FLAG}")
      ENDFOREACH()

      STRING(REPLACE ",-Wold-style-cast" "" _CUDA_NVCC_XC_FLAGS ${_CUDA_NVCC_XC_FLAGS})
 
      SET(CUDA_NVCC_FLAGS_${_OSG_CFG_TYPE} ${CUDA_NVCC_FLAGS_${_OSG_CFG_TYPE}};${_CUDA_NVCC_XC_FLAGS}; CACHE STRING "Cuda defaults written" FORCE)
    ENDIF()
  ENDFOREACH()


  MESSAGE("FOOOO ${CUDA_NVCC_FLAGS} ## ${_OSG_CUDA_NVCC_FLAGS}")
 
  FOREACH(_OSG_CFG_TYPE ${CMAKE_CONFIGURATION_TYPES})
    STRING(TOUPPER ${_OSG_CFG_TYPE} _OSG_CFG_TYPE)
    MESSAGE("FOO CUDA_NVCC_FLAGS_${_OSG_CFG_TYPE} ${CUDA_NVCC_FLAGS_${_OSG_CFG_TYPE}}")
  ENDFOREACH()

 ENDIF()
 
ENDMACRO()