# - Find OpenCL
# Find the native OPENCL includes and library
#
#  OPENCL_INCLUDE_DIR - where to find cl/cl.h, etc.
#  OPENCL_LIBRARIES   - List of libraries when using OpenCL.
#  OPENCL_FOUND       - True if OpenCL found.


IF(OPENCL_INCLUDE_DIR AND EXISTS ${OPENCL_INCLUDE_DIR}/CL/cl.h)
  # Already in cache, be silent
  SET(OPENCL_FIND_QUIETLY TRUE)
ENDIF()

FIND_PATH(OPENCL_INCLUDE_DIR CL/cl.h)

SET(OPENCL_NAMES OpenCL)
FIND_LIBRARY(OPENCL_LIBRARY NAMES ${OPENCL_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set OPENCL_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENCL DEFAULT_MSG OPENCL_LIBRARY OPENCL_INCLUDE_DIR)

IF(OPENCL_FOUND)
  SET( OPENCL_LIBRARIES ${OPENCL_LIBRARY} )
ELSE(OPENCL_FOUND)
  SET( OPENCL_LIBRARIES )
ENDIF(OPENCL_FOUND)

MARK_AS_ADVANCED( OPENCL_LIBRARY OPENCL_INCLUDE_DIR )
