MESSAGE(STATUS "Prepare OSGContribCgFX")

GET_FILENAME_COMPONENT(_CMAKE_CURR_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURR_LIST_DIR}/CMake")

INCLUDE(ConfigurePackages.OSGContribCgFX)


IF(NOT OSG_BUILD_DEPENDEND)
  OSG_CONFIGURE_CG()

  OSG_ADD_OPT(CG_FOUND)
  OSG_ADD_OPT(CG_LIBRARIES_FOUND)
  OSG_ADD_OPT(CG_LIBRARIES)
  OSG_ADD_OPT(CG_INCLUDE_DIR)
ENDIF(NOT OSG_BUILD_DEPENDEND)

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CG 1")

MESSAGE("  with Cg : ${OSG_WITH_CG}")
MESSAGE("")

IF(WIN32 AND OSG_WITH_CG)
  IF(EXISTS "${CG_INCLUDE_DIR}/GL")
    MESSAGE(SEND_ERROR "Cg include dir contains GL subdir, this must be renamed prior to generation")
  ENDIF()
ENDIF(WIN32 AND OSG_WITH_CG)

INSTALL(FILES "${_CMAKE_CURR_LIST_DIR}/CMake/FindCg.cmake"
        DESTINATION share/OpenSG/cmake)
#        COMPONENT development_configuration)

INSTALL(
  FILES "${_CMAKE_CURR_LIST_DIR}/CMake/ConfigurePackages.OSGContribCgFX.cmake"
  DESTINATION share/OpenSG/cmake)
#  COMPONENT development_configuration)

