/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFRAMEBUFFEROBJECTFIELDS_H_
#define _OSGFRAMEBUFFEROBJECTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class FrameBufferObject;

OSG_GEN_CONTAINERPTR(FrameBufferObject);
/*! \ingroup GrpSystemWindowFBOFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<FrameBufferObject *, nsOSG> :
    public FieldTraitsFCPtrBase<FrameBufferObject *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<FrameBufferObject *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<FrameBufferObject *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecFrameBufferObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<FrameBufferObject *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecFrameBufferObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<FrameBufferObject *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakFrameBufferObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<FrameBufferObject *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdFrameBufferObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<FrameBufferObject *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecFrameBufferObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<FrameBufferObject *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecFrameBufferObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<FrameBufferObject *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakFrameBufferObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<FrameBufferObject *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdFrameBufferObjectPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemWindowFBOFieldSFields */
typedef PointerSField<FrameBufferObject *,
                      RecordedRefCountPolicy, nsOSG  > SFRecFrameBufferObjectPtr;
/*! \ingroup GrpSystemWindowFBOFieldSFields */
typedef PointerSField<FrameBufferObject *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecFrameBufferObjectPtr;
/*! \ingroup GrpSystemWindowFBOFieldSFields */
typedef PointerSField<FrameBufferObject *,
                      WeakRefCountPolicy, nsOSG      > SFWeakFrameBufferObjectPtr;
/*! \ingroup GrpSystemWindowFBOFieldSFields */
typedef PointerSField<FrameBufferObject *,
                      NoRefCountPolicy, nsOSG        > SFUncountedFrameBufferObjectPtr;


/*! \ingroup GrpSystemWindowFBOFieldMFields */
typedef PointerMField<FrameBufferObject *,
                      RecordedRefCountPolicy, nsOSG  > MFRecFrameBufferObjectPtr;
/*! \ingroup GrpSystemWindowFBOFieldMFields */
typedef PointerMField<FrameBufferObject *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecFrameBufferObjectPtr;
/*! \ingroup GrpSystemWindowFBOFieldMFields */
typedef PointerMField<FrameBufferObject *,
                      WeakRefCountPolicy, nsOSG      > MFWeakFrameBufferObjectPtr;
/*! \ingroup GrpSystemWindowFBOFieldMFields */
typedef PointerMField<FrameBufferObject *,
                      NoRefCountPolicy, nsOSG        > MFUncountedFrameBufferObjectPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemWindowFBOFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecFrameBufferObjectPtr : 
    public PointerSField<FrameBufferObject *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemWindowFBOFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecFrameBufferObjectPtr : 
    public PointerSField<FrameBufferObject *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemWindowFBOFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakFrameBufferObjectPtr :
    public PointerSField<FrameBufferObject *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemWindowFBOFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedFrameBufferObjectPtr :
    public PointerSField<FrameBufferObject *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemWindowFBOFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecFrameBufferObjectPtr :
    public PointerMField<FrameBufferObject *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemWindowFBOFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecFrameBufferObjectPtr :
    public PointerMField<FrameBufferObject *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemWindowFBOFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakFrameBufferObjectPtr :
    public PointerMField<FrameBufferObject *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemWindowFBOFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedFrameBufferObjectPtr :
    public PointerMField<FrameBufferObject *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGFRAMEBUFFEROBJECTFIELDS_H_ */
