/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class FrameBufferObject!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGConfig.h"



#include "OSGFrameBufferAttachment.h"   // ColorAttachments Class

#include "OSGFrameBufferObjectBase.h"
#include "OSGFrameBufferObject.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::FrameBufferObject
    Framebuffer object. Encapsulates FBOs as defined by the EXT_framebuffer_object
    OpenGL extension.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var GLenum          FrameBufferObjectBase::_sfGLId
    The OpenGL texture id for this frame buffer object.
*/

/*! \var GLenum          FrameBufferObjectBase::_sfMultiSampleGLId
    The OpenGL texture id for this frame buffer object.
*/

/*! \var FrameBufferAttachment * FrameBufferObjectBase::_mfColorAttachments
    GL_COLOR_ATTACHMENTX slots, position defines X. 
    This defines the target buffers for color attachments.
*/

/*! \var GLenum          FrameBufferObjectBase::_mfDrawBuffers
    The target draw buffers.  ex: GL_COLOR_ATTACHMENT0.
    These are used to call DrawBuffers to tell OpenGL what targets
    to render into.
*/

/*! \var FrameBufferAttachment * FrameBufferObjectBase::_sfDepthAttachment
    GL_DEPTH_ATTACHMENT slot. The target for depth values.
*/

/*! \var FrameBufferAttachment * FrameBufferObjectBase::_sfStencilAttachment
    GL_STENCIL_ATTACHMENT slot.
*/

/*! \var UInt16          FrameBufferObjectBase::_sfWidth
    
*/

/*! \var UInt16          FrameBufferObjectBase::_sfHeight
    
*/

/*! \var bool            FrameBufferObjectBase::_sfPostProcessOnDeactivate
    Enable to check and generate mipmap level or copy the texture buffer
    result back to the image
*/

/*! \var bool            FrameBufferObjectBase::_sfEnableMultiSample
    
*/

/*! \var UInt32          FrameBufferObjectBase::_sfColorSamples
    
*/

/*! \var UInt32          FrameBufferObjectBase::_sfCoverageSamples
    
*/

/*! \var bool            FrameBufferObjectBase::_sfFixedSampleLocation
    
*/

/*! \var FrameBufferAttachment * FrameBufferObjectBase::_mfMsaaColorAttachments
    GL_COLOR_ATTACHMENTX slots, position defines X. 
    This defines the target buffers for color attachments.
*/

/*! \var FrameBufferAttachment * FrameBufferObjectBase::_sfMsaaDepthAttachment
    GL_DEPTH_ATTACHMENT slot. The target for depth values.
*/

/*! \var FrameBufferAttachment * FrameBufferObjectBase::_sfMsaaStencilAttachment
    GL_STENCIL_ATTACHMENT slot.
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<FrameBufferObject *, nsOSG>::_type(
    "FrameBufferObjectPtr", 
    "AttachmentContainerPtr", 
    FrameBufferObject::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(FrameBufferObject *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           FrameBufferObject *,
                           nsOSG)

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           FrameBufferObject *,
                           nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void FrameBufferObjectBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFGLenum::Description(
        SFGLenum::getClassType(),
        "GLId",
        "The OpenGL texture id for this frame buffer object.\n",
        GLIdFieldId, GLIdFieldMask,
        true,
        (Field::FClusterLocal),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleGLId),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleGLId));

    oType.addInitialDesc(pDesc);

    pDesc = new SFGLenum::Description(
        SFGLenum::getClassType(),
        "multiSampleGLId",
        "The OpenGL texture id for this frame buffer object.\n",
        MultiSampleGLIdFieldId, MultiSampleGLIdFieldMask,
        true,
        (Field::FClusterLocal),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleMultiSampleGLId),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleMultiSampleGLId));

    oType.addInitialDesc(pDesc);

    pDesc = new MFUnrecFrameBufferAttachmentPtr::Description(
        MFUnrecFrameBufferAttachmentPtr::getClassType(),
        "colorAttachments",
        "GL_COLOR_ATTACHMENTX slots, position defines X. \n"
        "This defines the target buffers for color attachments.\n",
        ColorAttachmentsFieldId, ColorAttachmentsFieldMask,
        false,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleColorAttachments),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleColorAttachments));

    oType.addInitialDesc(pDesc);

    pDesc = new MFGLenum::Description(
        MFGLenum::getClassType(),
        "drawBuffers",
        "The target draw buffers.  ex: GL_COLOR_ATTACHMENT0.\n"
        "These are used to call DrawBuffers to tell OpenGL what targets\n"
        "to render into.\n",
        DrawBuffersFieldId, DrawBuffersFieldMask,
        false,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleDrawBuffers),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleDrawBuffers));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecFrameBufferAttachmentPtr::Description(
        SFUnrecFrameBufferAttachmentPtr::getClassType(),
        "depthAttachment",
        "GL_DEPTH_ATTACHMENT slot. The target for depth values.\n",
        DepthAttachmentFieldId, DepthAttachmentFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleDepthAttachment),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleDepthAttachment));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecFrameBufferAttachmentPtr::Description(
        SFUnrecFrameBufferAttachmentPtr::getClassType(),
        "stencilAttachment",
        "GL_STENCIL_ATTACHMENT slot.\n",
        StencilAttachmentFieldId, StencilAttachmentFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleStencilAttachment),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleStencilAttachment));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUInt16::Description(
        SFUInt16::getClassType(),
        "width",
        "",
        WidthFieldId, WidthFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleWidth),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleWidth));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUInt16::Description(
        SFUInt16::getClassType(),
        "height",
        "",
        HeightFieldId, HeightFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleHeight),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleHeight));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "postProcessOnDeactivate",
        "Enable to check and generate mipmap level or copy the texture buffer\n"
        "result back to the image\n",
        PostProcessOnDeactivateFieldId, PostProcessOnDeactivateFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandlePostProcessOnDeactivate),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandlePostProcessOnDeactivate));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "enableMultiSample",
        "",
        EnableMultiSampleFieldId, EnableMultiSampleFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleEnableMultiSample),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleEnableMultiSample));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "colorSamples",
        "",
        ColorSamplesFieldId, ColorSamplesFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleColorSamples),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleColorSamples));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "coverageSamples",
        "",
        CoverageSamplesFieldId, CoverageSamplesFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleCoverageSamples),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleCoverageSamples));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "fixedSampleLocation",
        "",
        FixedSampleLocationFieldId, FixedSampleLocationFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleFixedSampleLocation),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleFixedSampleLocation));

    oType.addInitialDesc(pDesc);

    pDesc = new MFUnrecFrameBufferAttachmentPtr::Description(
        MFUnrecFrameBufferAttachmentPtr::getClassType(),
        "msaaColorAttachments",
        "GL_COLOR_ATTACHMENTX slots, position defines X. \n"
        "This defines the target buffers for color attachments.\n",
        MsaaColorAttachmentsFieldId, MsaaColorAttachmentsFieldMask,
        true,
        (Field::FClusterLocal | Field::FThreadLocal),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleMsaaColorAttachments),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleMsaaColorAttachments));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecFrameBufferAttachmentPtr::Description(
        SFUnrecFrameBufferAttachmentPtr::getClassType(),
        "msaaDepthAttachment",
        "GL_DEPTH_ATTACHMENT slot. The target for depth values.\n",
        MsaaDepthAttachmentFieldId, MsaaDepthAttachmentFieldMask,
        true,
        (Field::FClusterLocal | Field::FThreadLocal),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleMsaaDepthAttachment),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleMsaaDepthAttachment));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecFrameBufferAttachmentPtr::Description(
        SFUnrecFrameBufferAttachmentPtr::getClassType(),
        "msaaStencilAttachment",
        "GL_STENCIL_ATTACHMENT slot.\n",
        MsaaStencilAttachmentFieldId, MsaaStencilAttachmentFieldMask,
        true,
        (Field::FClusterLocal | Field::FThreadLocal),
        static_cast<FieldEditMethodSig>(&FrameBufferObject::editHandleMsaaStencilAttachment),
        static_cast<FieldGetMethodSig >(&FrameBufferObject::getHandleMsaaStencilAttachment));

    oType.addInitialDesc(pDesc);
}


FrameBufferObjectBase::TypeObject FrameBufferObjectBase::_type(
    FrameBufferObjectBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&FrameBufferObjectBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&FrameBufferObject::initMethod),
    reinterpret_cast<ExitContainerF>(&FrameBufferObject::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(
        reinterpret_cast<void *>(&FrameBufferObject::classDescInserter)),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"FrameBufferObject\"\n"
    "    parent=\"AttachmentContainer\"\n"
    "    library=\"System\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    docGroupBase=\"GrpSystemWindowFBO\"\n"
    "    >\n"
    "    Framebuffer object. Encapsulates FBOs as defined by the EXT_framebuffer_object\n"
    "    OpenGL extension.\n"
    "    <Field\n"
    "        name=\"GLId\"\n"
    "        type=\"GLenum\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"0\"\n"
    "        fieldFlags=\"FClusterLocal\"\n"
    "        >\n"
    "        The OpenGL texture id for this frame buffer object.\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"multiSampleGLId\"\n"
    "        type=\"GLenum\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"0\"\n"
    "        fieldFlags=\"FClusterLocal\"\n"
    "        >\n"
    "        The OpenGL texture id for this frame buffer object.\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"colorAttachments\"\n"
    "        type=\"FrameBufferAttachmentPtr\"\n"
    "        cardinality=\"multi\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "        GL_COLOR_ATTACHMENTX slots, position defines X. \n"
    "        This defines the target buffers for color attachments.\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"drawBuffers\"\n"
    "        type=\"GLenum\"\n"
    "        cardinality=\"multi\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"0\"\n"
    "        >\n"
    "        The target draw buffers.  ex: GL_COLOR_ATTACHMENT0.\n"
    "        These are used to call DrawBuffers to tell OpenGL what targets\n"
    "        to render into.\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"depthAttachment\"\n"
    "        type=\"FrameBufferAttachmentPtr\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "        GL_DEPTH_ATTACHMENT slot. The target for depth values.\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"stencilAttachment\"\n"
    "        type=\"FrameBufferAttachmentPtr\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "        GL_STENCIL_ATTACHMENT slot.\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"width\"\n"
    "        type=\"UInt16\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"0\"\n"
    "        >\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"height\"\n"
    "        type=\"UInt16\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"0\"\n"
    "        >\n"
    "    </Field>\n"
    "\n"
    "    <Field\n"
    "        name=\"postProcessOnDeactivate\"\n"
    "        type=\"bool\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"false\"\n"
    "        >\n"
    "        Enable to check and generate mipmap level or copy the texture buffer\n"
    "        result back to the image\n"
    "    </Field>\n"
    "\n"
    "\n"
    "    <Field\n"
    "        name=\"enableMultiSample\"\n"
    "        type=\"bool\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"false\"\n"
    "        >\n"
    "    </Field>\n"
    "\n"
    "    <Field\n"
    "        name=\"colorSamples\"\n"
    "        type=\"UInt32\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"4\"\n"
    "        >\n"
    "    </Field>\n"
    "\n"
    "    <Field\n"
    "        name=\"coverageSamples\"\n"
    "        type=\"UInt32\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"4\"\n"
    "        >\n"
    "    </Field>\n"
    "\n"
    "    <Field\n"
    "        name=\"fixedSampleLocation\"\n"
    "        type=\"bool\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"true\"\n"
    "        >\n"
    "    </Field>\n"
    "\n"
    "\n"
    "    <Field\n"
    "        name=\"msaaColorAttachments\"\n"
    "        type=\"FrameBufferAttachmentPtr\"\n"
    "        cardinality=\"multi\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"protected\"\n"
    "        fieldFlags=\"FClusterLocal,FThreadLocal\"\n"
    "        >\n"
    "        GL_COLOR_ATTACHMENTX slots, position defines X. \n"
    "        This defines the target buffers for color attachments.\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"msaaDepthAttachment\"\n"
    "        type=\"FrameBufferAttachmentPtr\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"protected\"\n"
    "        fieldFlags=\"FClusterLocal,FThreadLocal\"\n"
    "        >\n"
    "        GL_DEPTH_ATTACHMENT slot. The target for depth values.\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"msaaStencilAttachment\"\n"
    "        type=\"FrameBufferAttachmentPtr\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"protected\"\n"
    "        fieldFlags=\"FClusterLocal,FThreadLocal\"\n"
    "        >\n"
    "        GL_STENCIL_ATTACHMENT slot.\n"
    "    </Field>\n"
    "\n"
    "</FieldContainer>\n",
    "Framebuffer object. Encapsulates FBOs as defined by the EXT_framebuffer_object\n"
    "OpenGL extension.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &FrameBufferObjectBase::getType(void)
{
    return _type;
}

const FieldContainerType &FrameBufferObjectBase::getType(void) const
{
    return _type;
}

UInt32 FrameBufferObjectBase::getContainerSize(void) const
{
    return sizeof(FrameBufferObject);
}

/*------------------------- decorator get ------------------------------*/


SFGLenum *FrameBufferObjectBase::editSFGLId(void)
{
    editSField(GLIdFieldMask);

    return &_sfGLId;
}

const SFGLenum *FrameBufferObjectBase::getSFGLId(void) const
{
    return &_sfGLId;
}


SFGLenum *FrameBufferObjectBase::editSFMultiSampleGLId(void)
{
    editSField(MultiSampleGLIdFieldMask);

    return &_sfMultiSampleGLId;
}

const SFGLenum *FrameBufferObjectBase::getSFMultiSampleGLId(void) const
{
    return &_sfMultiSampleGLId;
}


//! Get the FrameBufferObject::_mfColorAttachments field.
const MFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::getMFColorAttachments(void) const
{
    return &_mfColorAttachments;
}

MFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::editMFColorAttachments(void)
{
    editMField(ColorAttachmentsFieldMask, _mfColorAttachments);

    return &_mfColorAttachments;
}
FrameBufferAttachment * FrameBufferObjectBase::getColorAttachments(const UInt32 index) const
{
    return _mfColorAttachments[index];
}

MFGLenum *FrameBufferObjectBase::editMFDrawBuffers(void)
{
    editMField(DrawBuffersFieldMask, _mfDrawBuffers);

    return &_mfDrawBuffers;
}

const MFGLenum *FrameBufferObjectBase::getMFDrawBuffers(void) const
{
    return &_mfDrawBuffers;
}


//! Get the FrameBufferObject::_sfDepthAttachment field.
const SFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::getSFDepthAttachment(void) const
{
    return &_sfDepthAttachment;
}

SFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::editSFDepthAttachment(void)
{
    editSField(DepthAttachmentFieldMask);

    return &_sfDepthAttachment;
}

//! Get the value of the FrameBufferObject::_sfDepthAttachment field.
FrameBufferAttachment * FrameBufferObjectBase::getDepthAttachment(void) const
{
    return _sfDepthAttachment.getValue();
}

//! Set the value of the FrameBufferObject::_sfDepthAttachment field.
void FrameBufferObjectBase::setDepthAttachment(FrameBufferAttachment * const value)
{
    editSField(DepthAttachmentFieldMask);

    _sfDepthAttachment.setValue(value);
}


//! Get the FrameBufferObject::_sfStencilAttachment field.
const SFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::getSFStencilAttachment(void) const
{
    return &_sfStencilAttachment;
}

SFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::editSFStencilAttachment(void)
{
    editSField(StencilAttachmentFieldMask);

    return &_sfStencilAttachment;
}

//! Get the value of the FrameBufferObject::_sfStencilAttachment field.
FrameBufferAttachment * FrameBufferObjectBase::getStencilAttachment(void) const
{
    return _sfStencilAttachment.getValue();
}

//! Set the value of the FrameBufferObject::_sfStencilAttachment field.
void FrameBufferObjectBase::setStencilAttachment(FrameBufferAttachment * const value)
{
    editSField(StencilAttachmentFieldMask);

    _sfStencilAttachment.setValue(value);
}


SFUInt16 *FrameBufferObjectBase::editSFWidth(void)
{
    editSField(WidthFieldMask);

    return &_sfWidth;
}

const SFUInt16 *FrameBufferObjectBase::getSFWidth(void) const
{
    return &_sfWidth;
}


SFUInt16 *FrameBufferObjectBase::editSFHeight(void)
{
    editSField(HeightFieldMask);

    return &_sfHeight;
}

const SFUInt16 *FrameBufferObjectBase::getSFHeight(void) const
{
    return &_sfHeight;
}


SFBool *FrameBufferObjectBase::editSFPostProcessOnDeactivate(void)
{
    editSField(PostProcessOnDeactivateFieldMask);

    return &_sfPostProcessOnDeactivate;
}

const SFBool *FrameBufferObjectBase::getSFPostProcessOnDeactivate(void) const
{
    return &_sfPostProcessOnDeactivate;
}


SFBool *FrameBufferObjectBase::editSFEnableMultiSample(void)
{
    editSField(EnableMultiSampleFieldMask);

    return &_sfEnableMultiSample;
}

const SFBool *FrameBufferObjectBase::getSFEnableMultiSample(void) const
{
    return &_sfEnableMultiSample;
}


SFUInt32 *FrameBufferObjectBase::editSFColorSamples(void)
{
    editSField(ColorSamplesFieldMask);

    return &_sfColorSamples;
}

const SFUInt32 *FrameBufferObjectBase::getSFColorSamples(void) const
{
    return &_sfColorSamples;
}


SFUInt32 *FrameBufferObjectBase::editSFCoverageSamples(void)
{
    editSField(CoverageSamplesFieldMask);

    return &_sfCoverageSamples;
}

const SFUInt32 *FrameBufferObjectBase::getSFCoverageSamples(void) const
{
    return &_sfCoverageSamples;
}


SFBool *FrameBufferObjectBase::editSFFixedSampleLocation(void)
{
    editSField(FixedSampleLocationFieldMask);

    return &_sfFixedSampleLocation;
}

const SFBool *FrameBufferObjectBase::getSFFixedSampleLocation(void) const
{
    return &_sfFixedSampleLocation;
}


//! Get the FrameBufferObject::_mfMsaaColorAttachments field.
const MFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::getMFMsaaColorAttachments(void) const
{
    return &_mfMsaaColorAttachments;
}

MFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::editMFMsaaColorAttachments(void)
{
    editMField(MsaaColorAttachmentsFieldMask, _mfMsaaColorAttachments);

    return &_mfMsaaColorAttachments;
}
FrameBufferAttachment * FrameBufferObjectBase::getMsaaColorAttachments(const UInt32 index) const
{
    return _mfMsaaColorAttachments[index];
}

//! Get the FrameBufferObject::_sfMsaaDepthAttachment field.
const SFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::getSFMsaaDepthAttachment(void) const
{
    return &_sfMsaaDepthAttachment;
}

SFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::editSFMsaaDepthAttachment(void)
{
    editSField(MsaaDepthAttachmentFieldMask);

    return &_sfMsaaDepthAttachment;
}

//! Get the value of the FrameBufferObject::_sfMsaaDepthAttachment field.
FrameBufferAttachment * FrameBufferObjectBase::getMsaaDepthAttachment(void) const
{
    return _sfMsaaDepthAttachment.getValue();
}

//! Set the value of the FrameBufferObject::_sfMsaaDepthAttachment field.
void FrameBufferObjectBase::setMsaaDepthAttachment(FrameBufferAttachment * const value)
{
    editSField(MsaaDepthAttachmentFieldMask);

    _sfMsaaDepthAttachment.setValue(value);
}


//! Get the FrameBufferObject::_sfMsaaStencilAttachment field.
const SFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::getSFMsaaStencilAttachment(void) const
{
    return &_sfMsaaStencilAttachment;
}

SFUnrecFrameBufferAttachmentPtr *FrameBufferObjectBase::editSFMsaaStencilAttachment(void)
{
    editSField(MsaaStencilAttachmentFieldMask);

    return &_sfMsaaStencilAttachment;
}

//! Get the value of the FrameBufferObject::_sfMsaaStencilAttachment field.
FrameBufferAttachment * FrameBufferObjectBase::getMsaaStencilAttachment(void) const
{
    return _sfMsaaStencilAttachment.getValue();
}

//! Set the value of the FrameBufferObject::_sfMsaaStencilAttachment field.
void FrameBufferObjectBase::setMsaaStencilAttachment(FrameBufferAttachment * const value)
{
    editSField(MsaaStencilAttachmentFieldMask);

    _sfMsaaStencilAttachment.setValue(value);
}




void FrameBufferObjectBase::pushToColorAttachments(FrameBufferAttachment * const value)
{
    editMField(ColorAttachmentsFieldMask, _mfColorAttachments);

    _mfColorAttachments.push_back(value);
}

void FrameBufferObjectBase::assignColorAttachments(const MFUnrecFrameBufferAttachmentPtr &value)
{
    MFUnrecFrameBufferAttachmentPtr::const_iterator elemIt  =
        value.begin();
    MFUnrecFrameBufferAttachmentPtr::const_iterator elemEnd =
        value.end  ();

    static_cast<FrameBufferObject *>(this)->clearColorAttachments();

    while(elemIt != elemEnd)
    {
        this->pushToColorAttachments(*elemIt);

        ++elemIt;
    }
}

void FrameBufferObjectBase::removeFromColorAttachments(UInt32 uiIndex)
{
    if(uiIndex < _mfColorAttachments.size())
    {
        editMField(ColorAttachmentsFieldMask, _mfColorAttachments);

        _mfColorAttachments.erase(uiIndex);
    }
}

void FrameBufferObjectBase::removeObjFromColorAttachments(FrameBufferAttachment * const value)
{
    Int32 iElemIdx = _mfColorAttachments.findIndex(value);

    if(iElemIdx != -1)
    {
        editMField(ColorAttachmentsFieldMask, _mfColorAttachments);

        _mfColorAttachments.erase(iElemIdx);
    }
}
void FrameBufferObjectBase::clearColorAttachments(void)
{
    editMField(ColorAttachmentsFieldMask, _mfColorAttachments);


    _mfColorAttachments.clear();
}

void FrameBufferObjectBase::pushToMsaaColorAttachments(FrameBufferAttachment * const value)
{
    editMField(MsaaColorAttachmentsFieldMask, _mfMsaaColorAttachments);

    _mfMsaaColorAttachments.push_back(value);
}

void FrameBufferObjectBase::assignMsaaColorAttachments(const MFUnrecFrameBufferAttachmentPtr &value)
{
    MFUnrecFrameBufferAttachmentPtr::const_iterator elemIt  =
        value.begin();
    MFUnrecFrameBufferAttachmentPtr::const_iterator elemEnd =
        value.end  ();

    static_cast<FrameBufferObject *>(this)->clearMsaaColorAttachments();

    while(elemIt != elemEnd)
    {
        this->pushToMsaaColorAttachments(*elemIt);

        ++elemIt;
    }
}

void FrameBufferObjectBase::removeFromMsaaColorAttachments(UInt32 uiIndex)
{
    if(uiIndex < _mfMsaaColorAttachments.size())
    {
        editMField(MsaaColorAttachmentsFieldMask, _mfMsaaColorAttachments);

        _mfMsaaColorAttachments.erase(uiIndex);
    }
}

void FrameBufferObjectBase::removeObjFromMsaaColorAttachments(FrameBufferAttachment * const value)
{
    Int32 iElemIdx = _mfMsaaColorAttachments.findIndex(value);

    if(iElemIdx != -1)
    {
        editMField(MsaaColorAttachmentsFieldMask, _mfMsaaColorAttachments);

        _mfMsaaColorAttachments.erase(iElemIdx);
    }
}
void FrameBufferObjectBase::clearMsaaColorAttachments(void)
{
    editMField(MsaaColorAttachmentsFieldMask, _mfMsaaColorAttachments);


    _mfMsaaColorAttachments.clear();
}



/*------------------------------ access -----------------------------------*/

SizeT FrameBufferObjectBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (GLIdFieldMask & whichField))
    {
        returnValue += _sfGLId.getBinSize();
    }
    if(FieldBits::NoField != (MultiSampleGLIdFieldMask & whichField))
    {
        returnValue += _sfMultiSampleGLId.getBinSize();
    }
    if(FieldBits::NoField != (ColorAttachmentsFieldMask & whichField))
    {
        returnValue += _mfColorAttachments.getBinSize();
    }
    if(FieldBits::NoField != (DrawBuffersFieldMask & whichField))
    {
        returnValue += _mfDrawBuffers.getBinSize();
    }
    if(FieldBits::NoField != (DepthAttachmentFieldMask & whichField))
    {
        returnValue += _sfDepthAttachment.getBinSize();
    }
    if(FieldBits::NoField != (StencilAttachmentFieldMask & whichField))
    {
        returnValue += _sfStencilAttachment.getBinSize();
    }
    if(FieldBits::NoField != (WidthFieldMask & whichField))
    {
        returnValue += _sfWidth.getBinSize();
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        returnValue += _sfHeight.getBinSize();
    }
    if(FieldBits::NoField != (PostProcessOnDeactivateFieldMask & whichField))
    {
        returnValue += _sfPostProcessOnDeactivate.getBinSize();
    }
    if(FieldBits::NoField != (EnableMultiSampleFieldMask & whichField))
    {
        returnValue += _sfEnableMultiSample.getBinSize();
    }
    if(FieldBits::NoField != (ColorSamplesFieldMask & whichField))
    {
        returnValue += _sfColorSamples.getBinSize();
    }
    if(FieldBits::NoField != (CoverageSamplesFieldMask & whichField))
    {
        returnValue += _sfCoverageSamples.getBinSize();
    }
    if(FieldBits::NoField != (FixedSampleLocationFieldMask & whichField))
    {
        returnValue += _sfFixedSampleLocation.getBinSize();
    }
    if(FieldBits::NoField != (MsaaColorAttachmentsFieldMask & whichField))
    {
        returnValue += _mfMsaaColorAttachments.getBinSize();
    }
    if(FieldBits::NoField != (MsaaDepthAttachmentFieldMask & whichField))
    {
        returnValue += _sfMsaaDepthAttachment.getBinSize();
    }
    if(FieldBits::NoField != (MsaaStencilAttachmentFieldMask & whichField))
    {
        returnValue += _sfMsaaStencilAttachment.getBinSize();
    }

    return returnValue;
}

void FrameBufferObjectBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (GLIdFieldMask & whichField))
    {
        _sfGLId.copyToBin(pMem);
    }
    if(FieldBits::NoField != (MultiSampleGLIdFieldMask & whichField))
    {
        _sfMultiSampleGLId.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ColorAttachmentsFieldMask & whichField))
    {
        _mfColorAttachments.copyToBin(pMem);
    }
    if(FieldBits::NoField != (DrawBuffersFieldMask & whichField))
    {
        _mfDrawBuffers.copyToBin(pMem);
    }
    if(FieldBits::NoField != (DepthAttachmentFieldMask & whichField))
    {
        _sfDepthAttachment.copyToBin(pMem);
    }
    if(FieldBits::NoField != (StencilAttachmentFieldMask & whichField))
    {
        _sfStencilAttachment.copyToBin(pMem);
    }
    if(FieldBits::NoField != (WidthFieldMask & whichField))
    {
        _sfWidth.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        _sfHeight.copyToBin(pMem);
    }
    if(FieldBits::NoField != (PostProcessOnDeactivateFieldMask & whichField))
    {
        _sfPostProcessOnDeactivate.copyToBin(pMem);
    }
    if(FieldBits::NoField != (EnableMultiSampleFieldMask & whichField))
    {
        _sfEnableMultiSample.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ColorSamplesFieldMask & whichField))
    {
        _sfColorSamples.copyToBin(pMem);
    }
    if(FieldBits::NoField != (CoverageSamplesFieldMask & whichField))
    {
        _sfCoverageSamples.copyToBin(pMem);
    }
    if(FieldBits::NoField != (FixedSampleLocationFieldMask & whichField))
    {
        _sfFixedSampleLocation.copyToBin(pMem);
    }
    if(FieldBits::NoField != (MsaaColorAttachmentsFieldMask & whichField))
    {
        _mfMsaaColorAttachments.copyToBin(pMem);
    }
    if(FieldBits::NoField != (MsaaDepthAttachmentFieldMask & whichField))
    {
        _sfMsaaDepthAttachment.copyToBin(pMem);
    }
    if(FieldBits::NoField != (MsaaStencilAttachmentFieldMask & whichField))
    {
        _sfMsaaStencilAttachment.copyToBin(pMem);
    }
}

void FrameBufferObjectBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (GLIdFieldMask & whichField))
    {
        editSField(GLIdFieldMask);
        _sfGLId.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (MultiSampleGLIdFieldMask & whichField))
    {
        editSField(MultiSampleGLIdFieldMask);
        _sfMultiSampleGLId.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ColorAttachmentsFieldMask & whichField))
    {
        editMField(ColorAttachmentsFieldMask, _mfColorAttachments);
        _mfColorAttachments.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (DrawBuffersFieldMask & whichField))
    {
        editMField(DrawBuffersFieldMask, _mfDrawBuffers);
        _mfDrawBuffers.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (DepthAttachmentFieldMask & whichField))
    {
        editSField(DepthAttachmentFieldMask);
        _sfDepthAttachment.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (StencilAttachmentFieldMask & whichField))
    {
        editSField(StencilAttachmentFieldMask);
        _sfStencilAttachment.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (WidthFieldMask & whichField))
    {
        editSField(WidthFieldMask);
        _sfWidth.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        editSField(HeightFieldMask);
        _sfHeight.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (PostProcessOnDeactivateFieldMask & whichField))
    {
        editSField(PostProcessOnDeactivateFieldMask);
        _sfPostProcessOnDeactivate.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (EnableMultiSampleFieldMask & whichField))
    {
        editSField(EnableMultiSampleFieldMask);
        _sfEnableMultiSample.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ColorSamplesFieldMask & whichField))
    {
        editSField(ColorSamplesFieldMask);
        _sfColorSamples.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (CoverageSamplesFieldMask & whichField))
    {
        editSField(CoverageSamplesFieldMask);
        _sfCoverageSamples.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (FixedSampleLocationFieldMask & whichField))
    {
        editSField(FixedSampleLocationFieldMask);
        _sfFixedSampleLocation.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (MsaaColorAttachmentsFieldMask & whichField))
    {
        editMField(MsaaColorAttachmentsFieldMask, _mfMsaaColorAttachments);
        _mfMsaaColorAttachments.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (MsaaDepthAttachmentFieldMask & whichField))
    {
        editSField(MsaaDepthAttachmentFieldMask);
        _sfMsaaDepthAttachment.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (MsaaStencilAttachmentFieldMask & whichField))
    {
        editSField(MsaaStencilAttachmentFieldMask);
        _sfMsaaStencilAttachment.copyFromBin(pMem);
    }
}

//! create a new instance of the class
FrameBufferObjectTransitPtr FrameBufferObjectBase::createLocal(BitVector bFlags)
{
    FrameBufferObjectTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<FrameBufferObject>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
FrameBufferObjectTransitPtr FrameBufferObjectBase::createDependent(BitVector bFlags)
{
    FrameBufferObjectTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<FrameBufferObject>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
FrameBufferObjectTransitPtr FrameBufferObjectBase::create(void)
{
    FrameBufferObjectTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<FrameBufferObject>(tmpPtr);
    }

    return fc;
}

FrameBufferObject *FrameBufferObjectBase::createEmptyLocal(BitVector bFlags)
{
    FrameBufferObject *returnValue;

    newPtr<FrameBufferObject>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
FrameBufferObject *FrameBufferObjectBase::createEmpty(void)
{
    FrameBufferObject *returnValue;

    newPtr<FrameBufferObject>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr FrameBufferObjectBase::shallowCopyLocal(
    BitVector bFlags) const
{
    FrameBufferObject *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const FrameBufferObject *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr FrameBufferObjectBase::shallowCopyDependent(
    BitVector bFlags) const
{
    FrameBufferObject *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const FrameBufferObject *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr FrameBufferObjectBase::shallowCopy(void) const
{
    FrameBufferObject *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const FrameBufferObject *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

FrameBufferObjectBase::FrameBufferObjectBase(void) :
    Inherited(),
    _sfGLId                   (GLenum(0)),
    _sfMultiSampleGLId        (GLenum(0)),
    _mfColorAttachments       (),
    _mfDrawBuffers            (GLenum(0)),
    _sfDepthAttachment        (NULL),
    _sfStencilAttachment      (NULL),
    _sfWidth                  (UInt16(0)),
    _sfHeight                 (UInt16(0)),
    _sfPostProcessOnDeactivate(bool(false)),
    _sfEnableMultiSample      (bool(false)),
    _sfColorSamples           (UInt32(4)),
    _sfCoverageSamples        (UInt32(4)),
    _sfFixedSampleLocation    (bool(true)),
    _mfMsaaColorAttachments   (),
    _sfMsaaDepthAttachment    (NULL),
    _sfMsaaStencilAttachment  (NULL)
{
}

FrameBufferObjectBase::FrameBufferObjectBase(const FrameBufferObjectBase &source) :
    Inherited(source),
    _sfGLId                   (source._sfGLId                   ),
    _sfMultiSampleGLId        (source._sfMultiSampleGLId        ),
    _mfColorAttachments       (),
    _mfDrawBuffers            (source._mfDrawBuffers            ),
    _sfDepthAttachment        (NULL),
    _sfStencilAttachment      (NULL),
    _sfWidth                  (source._sfWidth                  ),
    _sfHeight                 (source._sfHeight                 ),
    _sfPostProcessOnDeactivate(source._sfPostProcessOnDeactivate),
    _sfEnableMultiSample      (source._sfEnableMultiSample      ),
    _sfColorSamples           (source._sfColorSamples           ),
    _sfCoverageSamples        (source._sfCoverageSamples        ),
    _sfFixedSampleLocation    (source._sfFixedSampleLocation    ),
    _mfMsaaColorAttachments   (),
    _sfMsaaDepthAttachment    (NULL),
    _sfMsaaStencilAttachment  (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

FrameBufferObjectBase::~FrameBufferObjectBase(void)
{
}

void FrameBufferObjectBase::onCreate(const FrameBufferObject *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        FrameBufferObject *pThis = static_cast<FrameBufferObject *>(this);

        MFUnrecFrameBufferAttachmentPtr::const_iterator ColorAttachmentsIt  =
            source->_mfColorAttachments.begin();
        MFUnrecFrameBufferAttachmentPtr::const_iterator ColorAttachmentsEnd =
            source->_mfColorAttachments.end  ();

        while(ColorAttachmentsIt != ColorAttachmentsEnd)
        {
            pThis->pushToColorAttachments(*ColorAttachmentsIt);

            ++ColorAttachmentsIt;
        }

        pThis->setDepthAttachment(source->getDepthAttachment());

        pThis->setStencilAttachment(source->getStencilAttachment());

        MFUnrecFrameBufferAttachmentPtr::const_iterator MsaaColorAttachmentsIt  =
            source->_mfMsaaColorAttachments.begin();
        MFUnrecFrameBufferAttachmentPtr::const_iterator MsaaColorAttachmentsEnd =
            source->_mfMsaaColorAttachments.end  ();

        while(MsaaColorAttachmentsIt != MsaaColorAttachmentsEnd)
        {
            pThis->pushToMsaaColorAttachments(*MsaaColorAttachmentsIt);

            ++MsaaColorAttachmentsIt;
        }

        pThis->setMsaaDepthAttachment(source->getMsaaDepthAttachment());

        pThis->setMsaaStencilAttachment(source->getMsaaStencilAttachment());
    }
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleGLId            (void) const
{
    SFGLenum::GetHandlePtr returnValue(
        new  SFGLenum::GetHandle(
             &_sfGLId,
             this->getType().getFieldDesc(GLIdFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleGLId           (void)
{
    SFGLenum::EditHandlePtr returnValue(
        new  SFGLenum::EditHandle(
             &_sfGLId,
             this->getType().getFieldDesc(GLIdFieldId),
             this));


    editSField(GLIdFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleMultiSampleGLId (void) const
{
    SFGLenum::GetHandlePtr returnValue(
        new  SFGLenum::GetHandle(
             &_sfMultiSampleGLId,
             this->getType().getFieldDesc(MultiSampleGLIdFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleMultiSampleGLId(void)
{
    SFGLenum::EditHandlePtr returnValue(
        new  SFGLenum::EditHandle(
             &_sfMultiSampleGLId,
             this->getType().getFieldDesc(MultiSampleGLIdFieldId),
             this));


    editSField(MultiSampleGLIdFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleColorAttachments (void) const
{
    MFUnrecFrameBufferAttachmentPtr::GetHandlePtr returnValue(
        new  MFUnrecFrameBufferAttachmentPtr::GetHandle(
             &_mfColorAttachments,
             this->getType().getFieldDesc(ColorAttachmentsFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleColorAttachments(void)
{
    MFUnrecFrameBufferAttachmentPtr::EditHandlePtr returnValue(
        new  MFUnrecFrameBufferAttachmentPtr::EditHandle(
             &_mfColorAttachments,
             this->getType().getFieldDesc(ColorAttachmentsFieldId),
             this));

    returnValue->setAddMethod(
        boost::bind(&FrameBufferObject::pushToColorAttachments,
                    static_cast<FrameBufferObject *>(this), _1));
    returnValue->setRemoveMethod(
        boost::bind(&FrameBufferObject::removeFromColorAttachments,
                    static_cast<FrameBufferObject *>(this), _1));
    returnValue->setRemoveObjMethod(
        boost::bind(&FrameBufferObject::removeObjFromColorAttachments,
                    static_cast<FrameBufferObject *>(this), _1));
    returnValue->setClearMethod(
        boost::bind(&FrameBufferObject::clearColorAttachments,
                    static_cast<FrameBufferObject *>(this)));

    editMField(ColorAttachmentsFieldMask, _mfColorAttachments);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleDrawBuffers     (void) const
{
    MFGLenum::GetHandlePtr returnValue(
        new  MFGLenum::GetHandle(
             &_mfDrawBuffers,
             this->getType().getFieldDesc(DrawBuffersFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleDrawBuffers    (void)
{
    MFGLenum::EditHandlePtr returnValue(
        new  MFGLenum::EditHandle(
             &_mfDrawBuffers,
             this->getType().getFieldDesc(DrawBuffersFieldId),
             this));


    editMField(DrawBuffersFieldMask, _mfDrawBuffers);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleDepthAttachment (void) const
{
    SFUnrecFrameBufferAttachmentPtr::GetHandlePtr returnValue(
        new  SFUnrecFrameBufferAttachmentPtr::GetHandle(
             &_sfDepthAttachment,
             this->getType().getFieldDesc(DepthAttachmentFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleDepthAttachment(void)
{
    SFUnrecFrameBufferAttachmentPtr::EditHandlePtr returnValue(
        new  SFUnrecFrameBufferAttachmentPtr::EditHandle(
             &_sfDepthAttachment,
             this->getType().getFieldDesc(DepthAttachmentFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&FrameBufferObject::setDepthAttachment,
                    static_cast<FrameBufferObject *>(this), _1));

    editSField(DepthAttachmentFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleStencilAttachment (void) const
{
    SFUnrecFrameBufferAttachmentPtr::GetHandlePtr returnValue(
        new  SFUnrecFrameBufferAttachmentPtr::GetHandle(
             &_sfStencilAttachment,
             this->getType().getFieldDesc(StencilAttachmentFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleStencilAttachment(void)
{
    SFUnrecFrameBufferAttachmentPtr::EditHandlePtr returnValue(
        new  SFUnrecFrameBufferAttachmentPtr::EditHandle(
             &_sfStencilAttachment,
             this->getType().getFieldDesc(StencilAttachmentFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&FrameBufferObject::setStencilAttachment,
                    static_cast<FrameBufferObject *>(this), _1));

    editSField(StencilAttachmentFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleWidth           (void) const
{
    SFUInt16::GetHandlePtr returnValue(
        new  SFUInt16::GetHandle(
             &_sfWidth,
             this->getType().getFieldDesc(WidthFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleWidth          (void)
{
    SFUInt16::EditHandlePtr returnValue(
        new  SFUInt16::EditHandle(
             &_sfWidth,
             this->getType().getFieldDesc(WidthFieldId),
             this));


    editSField(WidthFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleHeight          (void) const
{
    SFUInt16::GetHandlePtr returnValue(
        new  SFUInt16::GetHandle(
             &_sfHeight,
             this->getType().getFieldDesc(HeightFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleHeight         (void)
{
    SFUInt16::EditHandlePtr returnValue(
        new  SFUInt16::EditHandle(
             &_sfHeight,
             this->getType().getFieldDesc(HeightFieldId),
             this));


    editSField(HeightFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandlePostProcessOnDeactivate (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfPostProcessOnDeactivate,
             this->getType().getFieldDesc(PostProcessOnDeactivateFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandlePostProcessOnDeactivate(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfPostProcessOnDeactivate,
             this->getType().getFieldDesc(PostProcessOnDeactivateFieldId),
             this));


    editSField(PostProcessOnDeactivateFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleEnableMultiSample (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfEnableMultiSample,
             this->getType().getFieldDesc(EnableMultiSampleFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleEnableMultiSample(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfEnableMultiSample,
             this->getType().getFieldDesc(EnableMultiSampleFieldId),
             this));


    editSField(EnableMultiSampleFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleColorSamples    (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfColorSamples,
             this->getType().getFieldDesc(ColorSamplesFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleColorSamples   (void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfColorSamples,
             this->getType().getFieldDesc(ColorSamplesFieldId),
             this));


    editSField(ColorSamplesFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleCoverageSamples (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfCoverageSamples,
             this->getType().getFieldDesc(CoverageSamplesFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleCoverageSamples(void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfCoverageSamples,
             this->getType().getFieldDesc(CoverageSamplesFieldId),
             this));


    editSField(CoverageSamplesFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleFixedSampleLocation (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfFixedSampleLocation,
             this->getType().getFieldDesc(FixedSampleLocationFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleFixedSampleLocation(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfFixedSampleLocation,
             this->getType().getFieldDesc(FixedSampleLocationFieldId),
             this));


    editSField(FixedSampleLocationFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleMsaaColorAttachments (void) const
{
    MFUnrecFrameBufferAttachmentPtr::GetHandlePtr returnValue(
        new  MFUnrecFrameBufferAttachmentPtr::GetHandle(
             &_mfMsaaColorAttachments,
             this->getType().getFieldDesc(MsaaColorAttachmentsFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleMsaaColorAttachments(void)
{
    MFUnrecFrameBufferAttachmentPtr::EditHandlePtr returnValue(
        new  MFUnrecFrameBufferAttachmentPtr::EditHandle(
             &_mfMsaaColorAttachments,
             this->getType().getFieldDesc(MsaaColorAttachmentsFieldId),
             this));

    returnValue->setAddMethod(
        boost::bind(&FrameBufferObject::pushToMsaaColorAttachments,
                    static_cast<FrameBufferObject *>(this), _1));
    returnValue->setRemoveMethod(
        boost::bind(&FrameBufferObject::removeFromMsaaColorAttachments,
                    static_cast<FrameBufferObject *>(this), _1));
    returnValue->setRemoveObjMethod(
        boost::bind(&FrameBufferObject::removeObjFromMsaaColorAttachments,
                    static_cast<FrameBufferObject *>(this), _1));
    returnValue->setClearMethod(
        boost::bind(&FrameBufferObject::clearMsaaColorAttachments,
                    static_cast<FrameBufferObject *>(this)));

    editMField(MsaaColorAttachmentsFieldMask, _mfMsaaColorAttachments);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleMsaaDepthAttachment (void) const
{
    SFUnrecFrameBufferAttachmentPtr::GetHandlePtr returnValue(
        new  SFUnrecFrameBufferAttachmentPtr::GetHandle(
             &_sfMsaaDepthAttachment,
             this->getType().getFieldDesc(MsaaDepthAttachmentFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleMsaaDepthAttachment(void)
{
    SFUnrecFrameBufferAttachmentPtr::EditHandlePtr returnValue(
        new  SFUnrecFrameBufferAttachmentPtr::EditHandle(
             &_sfMsaaDepthAttachment,
             this->getType().getFieldDesc(MsaaDepthAttachmentFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&FrameBufferObject::setMsaaDepthAttachment,
                    static_cast<FrameBufferObject *>(this), _1));

    editSField(MsaaDepthAttachmentFieldMask);

    return returnValue;
}

GetFieldHandlePtr FrameBufferObjectBase::getHandleMsaaStencilAttachment (void) const
{
    SFUnrecFrameBufferAttachmentPtr::GetHandlePtr returnValue(
        new  SFUnrecFrameBufferAttachmentPtr::GetHandle(
             &_sfMsaaStencilAttachment,
             this->getType().getFieldDesc(MsaaStencilAttachmentFieldId),
             const_cast<FrameBufferObjectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr FrameBufferObjectBase::editHandleMsaaStencilAttachment(void)
{
    SFUnrecFrameBufferAttachmentPtr::EditHandlePtr returnValue(
        new  SFUnrecFrameBufferAttachmentPtr::EditHandle(
             &_sfMsaaStencilAttachment,
             this->getType().getFieldDesc(MsaaStencilAttachmentFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&FrameBufferObject::setMsaaStencilAttachment,
                    static_cast<FrameBufferObject *>(this), _1));

    editSField(MsaaStencilAttachmentFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void FrameBufferObjectBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    FrameBufferObject *pThis = static_cast<FrameBufferObject *>(this);

    pThis->execSync(static_cast<FrameBufferObject *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *FrameBufferObjectBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    FrameBufferObject *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const FrameBufferObject *>(pRefAspect),
                  dynamic_cast<const FrameBufferObject *>(this));

    return returnValue;
}
#endif

void FrameBufferObjectBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<FrameBufferObject *>(this)->clearColorAttachments();

    static_cast<FrameBufferObject *>(this)->setDepthAttachment(NULL);

    static_cast<FrameBufferObject *>(this)->setStencilAttachment(NULL);

    static_cast<FrameBufferObject *>(this)->clearMsaaColorAttachments();

    static_cast<FrameBufferObject *>(this)->setMsaaDepthAttachment(NULL);

    static_cast<FrameBufferObject *>(this)->setMsaaStencilAttachment(NULL);

#ifdef OSG_MT_CPTR_ASPECT
    AspectOffsetStore oOffsets;

    _pAspectStore->fillOffsetArray(oOffsets, this);
#endif

#ifdef OSG_MT_CPTR_ASPECT
    _mfDrawBuffers.terminateShare(Thread::getCurrentAspect(),
                                      oOffsets);
#endif
}


OSG_END_NAMESPACE
