/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVTKMAPPERFIELDS_H_
#define _OSGVTKMAPPERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribVTKDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VTKMapper;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! VTKMapperPtr

OSG_GEN_CONTAINERPTR(VTKMapper);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpContribVTKFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<VTKMapperPtr> :
    public FieldTraitsFCPtrBase<VTKMapperPtr>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VTKMapperPtr>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBVTK_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVTKMapperPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVTKMapperPtr"; }
};

template<> inline
const Char8 *FieldTraits<VTKMapperPtr, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVTKMapperPtr"; 
}

template<> inline
const Char8 *FieldTraits<VTKMapperPtr, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVTKMapperPtr"; 
}

template<> inline
const Char8 *FieldTraits<VTKMapperPtr, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVTKMapperPtr"; 
}

template<> inline
const Char8 *FieldTraits<VTKMapperPtr, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVTKMapperPtr"; 
}

template<> inline
const Char8 *FieldTraits<VTKMapperPtr, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVTKMapperPtr"; 
}

template<> inline
const Char8 *FieldTraits<VTKMapperPtr, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVTKMapperPtr"; 
}

template<> inline
const Char8 *FieldTraits<VTKMapperPtr, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVTKMapperPtr"; 
}

template<> inline
const Char8 *FieldTraits<VTKMapperPtr, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVTKMapperPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<VTKMapperPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribVTKFieldSingle */

typedef PointerSField<VTKMapperPtr,
                      RecordedRefCountPolicy  > SFRecVTKMapperPtr;
typedef PointerSField<VTKMapperPtr,
                      UnrecordedRefCountPolicy> SFUnrecVTKMapperPtr;
typedef PointerSField<VTKMapperPtr,
                      WeakRefCountPolicy      > SFWeakVTKMapperPtr;
typedef PointerSField<VTKMapperPtr,
                      NoRefCountPolicy        > SFUncountedVTKMapperPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribVTKFieldMulti */

typedef PointerMField<VTKMapperPtr,
                      RecordedRefCountPolicy  > MFRecVTKMapperPtr;
typedef PointerMField<VTKMapperPtr,
                      UnrecordedRefCountPolicy> MFUnrecVTKMapperPtr;
typedef PointerMField<VTKMapperPtr,
                      WeakRefCountPolicy      > MFWeakVTKMapperPtr;
typedef PointerMField<VTKMapperPtr,
                      NoRefCountPolicy        > MFUncountedVTKMapperPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGVTKMAPPERFIELDS_H_ */
