/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFCDPTRTESTFCCUSTOMACCESSFIELDS_H_
#define _OSGFCDPTRTESTFCCUSTOMACCESSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class FCDPtrTestFCCustomAccess;

OSG_GEN_CONTAINERPTR(FCDPtrTestFCCustomAccess);

/*! \ingroup GrpSystemFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<FCDPtrTestFCCustomAccess *> :
    public FieldTraitsFCPtrBase<FCDPtrTestFCCustomAccess *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<FCDPtrTestFCCustomAccess *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFFCDPtrTestFCCustomAccessPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFFCDPtrTestFCCustomAccessPtr"; }
};

template<> inline
const Char8 *FieldTraits<FCDPtrTestFCCustomAccess *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecFCDPtrTestFCCustomAccessPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDPtrTestFCCustomAccess *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecFCDPtrTestFCCustomAccessPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDPtrTestFCCustomAccess *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakFCDPtrTestFCCustomAccessPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDPtrTestFCCustomAccess *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdFCDPtrTestFCCustomAccessPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDPtrTestFCCustomAccess *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecFCDPtrTestFCCustomAccessPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDPtrTestFCCustomAccess *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecFCDPtrTestFCCustomAccessPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDPtrTestFCCustomAccess *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakFCDPtrTestFCCustomAccessPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDPtrTestFCCustomAccess *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdFCDPtrTestFCCustomAccessPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<FCDPtrTestFCCustomAccess *,
                      RecordedRefCountPolicy  > SFRecFCDPtrTestFCCustomAccessPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<FCDPtrTestFCCustomAccess *,
                      UnrecordedRefCountPolicy> SFUnrecFCDPtrTestFCCustomAccessPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<FCDPtrTestFCCustomAccess *,
                      WeakRefCountPolicy      > SFWeakFCDPtrTestFCCustomAccessPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<FCDPtrTestFCCustomAccess *,
                      NoRefCountPolicy        > SFUncountedFCDPtrTestFCCustomAccessPtr;


/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<FCDPtrTestFCCustomAccess *,
                      RecordedRefCountPolicy  > MFRecFCDPtrTestFCCustomAccessPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<FCDPtrTestFCCustomAccess *,
                      UnrecordedRefCountPolicy> MFUnrecFCDPtrTestFCCustomAccessPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<FCDPtrTestFCCustomAccess *,
                      WeakRefCountPolicy      > MFWeakFCDPtrTestFCCustomAccessPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<FCDPtrTestFCCustomAccess *,
                      NoRefCountPolicy        > MFUncountedFCDPtrTestFCCustomAccessPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecFCDPtrTestFCCustomAccessPtr : 
    public PointerSField<FCDPtrTestFCCustomAccess *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecFCDPtrTestFCCustomAccessPtr : 
    public PointerSField<FCDPtrTestFCCustomAccess *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakFCDPtrTestFCCustomAccessPtr :
    public PointerSField<FCDPtrTestFCCustomAccess *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedFCDPtrTestFCCustomAccessPtr :
    public PointerSField<FCDPtrTestFCCustomAccess *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecFCDPtrTestFCCustomAccessPtr :
    public PointerMField<FCDPtrTestFCCustomAccess *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecFCDPtrTestFCCustomAccessPtr :
    public PointerMField<FCDPtrTestFCCustomAccess *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakFCDPtrTestFCCustomAccessPtr :
    public PointerMField<FCDPtrTestFCCustomAccess *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedFCDPtrTestFCCustomAccessPtr :
    public PointerMField<FCDPtrTestFCCustomAccess *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGFCDPTRTESTFCCUSTOMACCESSFIELDS_H_ */
