/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFCDTESTFCFIELDS_H_
#define _OSGFCDTESTFCFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class FCDTestFC;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! FCDTestFCPtr

OSG_GEN_CONTAINERPTR(FCDTestFC);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpSystemFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<FCDTestFC *> :
    public FieldTraitsFCPtrBase<FCDTestFC *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<FCDTestFC *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFFCDTestFCPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFFCDTestFCPtr"; }
};

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdFCDTestFCPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<FCDTestFCPtr, 0>
    \hideinhierarchy
 */
#endif

class FieldContainer;

template <>
struct FieldTraits<FCDTestFC *, 1> :
    public FieldTraitsFCPtrBase<FCDTestFC *, 1>
{
  private:

  public:

    typedef FieldContainer            *ParentType;
    typedef FieldTraits<FCDTestFC *, 1>  Self;

    static const FieldType::Cardinality eParentCard = FieldType::MultiField;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFFCDTestFCPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFFCDTestFCPtr"; }
};

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildFCDTestFCPtr"; 
}

template<> inline
const Char8 *FieldTraits<FCDTestFC *, 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildFCDTestFCPtr"; 
}


#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpSystemFieldSingle */

typedef PointerSField<FCDTestFC *,
                      RecordedRefCountPolicy  > SFRecFCDTestFCPtr;
typedef PointerSField<FCDTestFC *,
                      UnrecordedRefCountPolicy> SFUnrecFCDTestFCPtr;
typedef PointerSField<FCDTestFC *,
                      WeakRefCountPolicy      > SFWeakFCDTestFCPtr;
typedef PointerSField<FCDTestFC *,
                      NoRefCountPolicy        > SFUncountedFCDTestFCPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpSystemFieldMulti */

typedef PointerMField<FCDTestFC *,
                      RecordedRefCountPolicy  > MFRecFCDTestFCPtr;
typedef PointerMField<FCDTestFC *,
                      UnrecordedRefCountPolicy> MFUnrecFCDTestFCPtr;
typedef PointerMField<FCDTestFC *,
                      WeakRefCountPolicy      > MFWeakFCDTestFCPtr;
typedef PointerMField<FCDTestFC *,
                      NoRefCountPolicy        > MFUncountedFCDTestFCPtr;
#endif



typedef ChildPointerSField<
          FCDTestFC *, 
          UnrecordedRefCountPolicy,
          1             > SFUnrecChildFCDTestFCPtr;


typedef ChildPointerMField<
          FCDTestFC *, 
          UnrecordedRefCountPolicy,
          1             > MFUnrecChildFCDTestFCPtr;

OSG_END_NAMESPACE

#endif /* _OSGFCDTESTFCFIELDS_H_ */
