/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFATBORDERCHUNKFIELDS_H_
#define _OSGFATBORDERCHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGDrawableDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class FatBorderChunk;

OSG_GEN_CONTAINERPTR(FatBorderChunk);

/*! \ingroup GrpDrawablesNurbsFieldTraits
    \ingroup GrpLibOSGDrawable
 */
template <>
struct FieldTraits<FatBorderChunk *> :
    public FieldTraitsFCPtrBase<FatBorderChunk *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<FatBorderChunk *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_DRAWABLE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFFatBorderChunkPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFFatBorderChunkPtr"; }
};

template<> inline
const Char8 *FieldTraits<FatBorderChunk *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecFatBorderChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FatBorderChunk *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecFatBorderChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FatBorderChunk *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakFatBorderChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FatBorderChunk *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdFatBorderChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FatBorderChunk *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecFatBorderChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FatBorderChunk *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecFatBorderChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FatBorderChunk *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakFatBorderChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FatBorderChunk *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdFatBorderChunkPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpDrawablesNurbsFieldSFields */
typedef PointerSField<FatBorderChunk *,
                      RecordedRefCountPolicy  > SFRecFatBorderChunkPtr;
/*! \ingroup GrpDrawablesNurbsFieldSFields */
typedef PointerSField<FatBorderChunk *,
                      UnrecordedRefCountPolicy> SFUnrecFatBorderChunkPtr;
/*! \ingroup GrpDrawablesNurbsFieldSFields */
typedef PointerSField<FatBorderChunk *,
                      WeakRefCountPolicy      > SFWeakFatBorderChunkPtr;
/*! \ingroup GrpDrawablesNurbsFieldSFields */
typedef PointerSField<FatBorderChunk *,
                      NoRefCountPolicy        > SFUncountedFatBorderChunkPtr;


/*! \ingroup GrpDrawablesNurbsFieldMFields */
typedef PointerMField<FatBorderChunk *,
                      RecordedRefCountPolicy  > MFRecFatBorderChunkPtr;
/*! \ingroup GrpDrawablesNurbsFieldMFields */
typedef PointerMField<FatBorderChunk *,
                      UnrecordedRefCountPolicy> MFUnrecFatBorderChunkPtr;
/*! \ingroup GrpDrawablesNurbsFieldMFields */
typedef PointerMField<FatBorderChunk *,
                      WeakRefCountPolicy      > MFWeakFatBorderChunkPtr;
/*! \ingroup GrpDrawablesNurbsFieldMFields */
typedef PointerMField<FatBorderChunk *,
                      NoRefCountPolicy        > MFUncountedFatBorderChunkPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpDrawablesNurbsFieldSFields \ingroup GrpLibOSGDrawable */
struct SFRecFatBorderChunkPtr : 
    public PointerSField<FatBorderChunk *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpDrawablesNurbsFieldSFields \ingroup GrpLibOSGDrawable */
struct SFUnrecFatBorderChunkPtr : 
    public PointerSField<FatBorderChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpDrawablesNurbsFieldSFields \ingroup GrpLibOSGDrawable */
struct SFWeakFatBorderChunkPtr :
    public PointerSField<FatBorderChunk *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpDrawablesNurbsFieldSFields \ingroup GrpLibOSGDrawable */
struct SFUncountedFatBorderChunkPtr :
    public PointerSField<FatBorderChunk *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpDrawablesNurbsFieldMFields \ingroup GrpLibOSGDrawable */
struct MFRecFatBorderChunkPtr :
    public PointerMField<FatBorderChunk *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpDrawablesNurbsFieldMFields \ingroup GrpLibOSGDrawable */
struct MFUnrecFatBorderChunkPtr :
    public PointerMField<FatBorderChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpDrawablesNurbsFieldMFields \ingroup GrpLibOSGDrawable */
struct MFWeakFatBorderChunkPtr :
    public PointerMField<FatBorderChunk *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpDrawablesNurbsFieldMFields \ingroup GrpLibOSGDrawable */
struct MFUncountedFatBorderChunkPtr :
    public PointerMField<FatBorderChunk *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGFATBORDERCHUNKFIELDS_H_ */
