/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDRAWABLESTATSATTACHMENTFIELDS_H_
#define _OSGDRAWABLESTATSATTACHMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class DrawableStatsAttachment;

OSG_GEN_CONTAINERPTR(DrawableStatsAttachment);

/*! \ingroup GrpSystemNodeCoreDrawablesFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<DrawableStatsAttachment *> :
    public FieldTraitsFCPtrBase<DrawableStatsAttachment *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<DrawableStatsAttachment *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFDrawableStatsAttachmentPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFDrawableStatsAttachmentPtr"; }
};

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachment *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachment *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachment *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachment *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachment *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachment *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachment *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachment *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdDrawableStatsAttachmentPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemNodeCoreDrawablesFieldSFields */
typedef PointerSField<DrawableStatsAttachment *,
                      RecordedRefCountPolicy  > SFRecDrawableStatsAttachmentPtr;
/*! \ingroup GrpSystemNodeCoreDrawablesFieldSFields */
typedef PointerSField<DrawableStatsAttachment *,
                      UnrecordedRefCountPolicy> SFUnrecDrawableStatsAttachmentPtr;
/*! \ingroup GrpSystemNodeCoreDrawablesFieldSFields */
typedef PointerSField<DrawableStatsAttachment *,
                      WeakRefCountPolicy      > SFWeakDrawableStatsAttachmentPtr;
/*! \ingroup GrpSystemNodeCoreDrawablesFieldSFields */
typedef PointerSField<DrawableStatsAttachment *,
                      NoRefCountPolicy        > SFUncountedDrawableStatsAttachmentPtr;


/*! \ingroup GrpSystemNodeCoreDrawablesFieldMFields */
typedef PointerMField<DrawableStatsAttachment *,
                      RecordedRefCountPolicy  > MFRecDrawableStatsAttachmentPtr;
/*! \ingroup GrpSystemNodeCoreDrawablesFieldMFields */
typedef PointerMField<DrawableStatsAttachment *,
                      UnrecordedRefCountPolicy> MFUnrecDrawableStatsAttachmentPtr;
/*! \ingroup GrpSystemNodeCoreDrawablesFieldMFields */
typedef PointerMField<DrawableStatsAttachment *,
                      WeakRefCountPolicy      > MFWeakDrawableStatsAttachmentPtr;
/*! \ingroup GrpSystemNodeCoreDrawablesFieldMFields */
typedef PointerMField<DrawableStatsAttachment *,
                      NoRefCountPolicy        > MFUncountedDrawableStatsAttachmentPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemNodeCoreDrawablesFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecDrawableStatsAttachmentPtr : 
    public PointerSField<DrawableStatsAttachment *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemNodeCoreDrawablesFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecDrawableStatsAttachmentPtr : 
    public PointerSField<DrawableStatsAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemNodeCoreDrawablesFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakDrawableStatsAttachmentPtr :
    public PointerSField<DrawableStatsAttachment *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemNodeCoreDrawablesFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedDrawableStatsAttachmentPtr :
    public PointerSField<DrawableStatsAttachment *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemNodeCoreDrawablesFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecDrawableStatsAttachmentPtr :
    public PointerMField<DrawableStatsAttachment *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemNodeCoreDrawablesFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecDrawableStatsAttachmentPtr :
    public PointerMField<DrawableStatsAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemNodeCoreDrawablesFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakDrawableStatsAttachmentPtr :
    public PointerMField<DrawableStatsAttachment *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemNodeCoreDrawablesFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedDrawableStatsAttachmentPtr :
    public PointerMField<DrawableStatsAttachment *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGDRAWABLESTATSATTACHMENTFIELDS_H_ */
