/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDRAWABLESTATSATTACHMENTFIELDS_H_
#define _OSGDRAWABLESTATSATTACHMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGFieldContainerPtrSField.h"
#include "OSGFieldContainerPtrMField.h"


OSG_BEGIN_NAMESPACE

class DrawableStatsAttachment;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! DrawableStatsAttachmentPtr

OSG_GEN_CONTAINERPTR(DrawableStatsAttachment);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpSystemFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<DrawableStatsAttachmentPtr> :
    public FieldTraitsFCPtrBase<DrawableStatsAttachmentPtr>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<DrawableStatsAttachmentPtr>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFDrawableStatsAttachmentPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFDrawableStatsAttachmentPtr"; }
};

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachmentPtr, 0>::getSName<RecordedRefCounts>(void)
{
    return "SFRecDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachmentPtr, 0>::getSName<UnrecordedRefCounts>(void)
{
    return "SFUnrecDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachmentPtr, 0>::getSName<WeakRefCounts>(void)
{
    return "SFWeakDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachmentPtr, 0>::getSName<NoRefCounts>(void)
{
    return "SFUnrefdDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachmentPtr, 0>::getMName<RecordedRefCounts>(void)
{
    return "MFRecDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachmentPtr, 0>::getMName<UnrecordedRefCounts>(void)
{
    return "MFUnrecDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachmentPtr, 0>::getMName<WeakRefCounts>(void)
{
    return "MFWeakDrawableStatsAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<DrawableStatsAttachmentPtr, 0>::getMName<NoRefCounts>(void)
{
    return "MFUnrefdDrawableStatsAttachmentPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<DrawableStatsAttachmentPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpSystemFieldSingle */

typedef FieldContainerPtrSField<DrawableStatsAttachmentPtr,
                                RecordedRefCounts  > SFRecDrawableStatsAttachmentPtr;
typedef FieldContainerPtrSField<DrawableStatsAttachmentPtr,
                                UnrecordedRefCounts> SFUnrecDrawableStatsAttachmentPtr;
typedef FieldContainerPtrSField<DrawableStatsAttachmentPtr,
                                WeakRefCounts      > SFWeakDrawableStatsAttachmentPtr;
typedef FieldContainerPtrSField<DrawableStatsAttachmentPtr,
                                NoRefCounts        > SFUncountedDrawableStatsAttachmentPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpSystemFieldMulti */

typedef FieldContainerPtrMField<DrawableStatsAttachmentPtr,
                                RecordedRefCounts  > MFRecDrawableStatsAttachmentPtr;
typedef FieldContainerPtrMField<DrawableStatsAttachmentPtr,
                                UnrecordedRefCounts> MFUnrecDrawableStatsAttachmentPtr;
typedef FieldContainerPtrMField<DrawableStatsAttachmentPtr,
                                WeakRefCounts      > MFWeakDrawableStatsAttachmentPtr;
typedef FieldContainerPtrMField<DrawableStatsAttachmentPtr,
                                NoRefCounts        > MFUncountedDrawableStatsAttachmentPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGDRAWABLESTATSATTACHMENTFIELDS_H_ */
