/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCONNECTORATTACHMENTFIELDS_H_
#define _OSGCONNECTORATTACHMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ConnectorAttachment;

OSG_GEN_CONTAINERPTR(ConnectorAttachment);
/*! \ingroup GrpBaseFieldContainerFieldTraits
    \ingroup GrpLibOSGBase
 */
template <>
struct FieldTraits<ConnectorAttachment *, nsOSG> :
    public FieldTraitsFCPtrBase<ConnectorAttachment *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ConnectorAttachment *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_BASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ConnectorAttachment *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecConnectorAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConnectorAttachment *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecConnectorAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConnectorAttachment *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakConnectorAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConnectorAttachment *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdConnectorAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConnectorAttachment *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecConnectorAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConnectorAttachment *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecConnectorAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConnectorAttachment *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakConnectorAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConnectorAttachment *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdConnectorAttachmentPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<ConnectorAttachment *,
                      RecordedRefCountPolicy, nsOSG  > SFRecConnectorAttachmentPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<ConnectorAttachment *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecConnectorAttachmentPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<ConnectorAttachment *,
                      WeakRefCountPolicy, nsOSG      > SFWeakConnectorAttachmentPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<ConnectorAttachment *,
                      NoRefCountPolicy, nsOSG        > SFUncountedConnectorAttachmentPtr;


/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<ConnectorAttachment *,
                      RecordedRefCountPolicy, nsOSG  > MFRecConnectorAttachmentPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<ConnectorAttachment *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecConnectorAttachmentPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<ConnectorAttachment *,
                      WeakRefCountPolicy, nsOSG      > MFWeakConnectorAttachmentPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<ConnectorAttachment *,
                      NoRefCountPolicy, nsOSG        > MFUncountedConnectorAttachmentPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFRecConnectorAttachmentPtr : 
    public PointerSField<ConnectorAttachment *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFUnrecConnectorAttachmentPtr : 
    public PointerSField<ConnectorAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFWeakConnectorAttachmentPtr :
    public PointerSField<ConnectorAttachment *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFUncountedConnectorAttachmentPtr :
    public PointerSField<ConnectorAttachment *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFRecConnectorAttachmentPtr :
    public PointerMField<ConnectorAttachment *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFUnrecConnectorAttachmentPtr :
    public PointerMField<ConnectorAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFWeakConnectorAttachmentPtr :
    public PointerMField<ConnectorAttachment *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFUncountedConnectorAttachmentPtr :
    public PointerMField<ConnectorAttachment *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCONNECTORATTACHMENTFIELDS_H_ */
