#!/bin/bash

# This script assumes that the user running it has ssh set up
# to allow login to the server without password

export RSYNC_RSH=ssh

rsync -az tracdocs/html dirk@neo.vrsource.org:/home/trac/projects/opensg/doxygen



