/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPOINTCHUNKFIELDS_H_
#define _OSGPOINTCHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGStateDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PointChunk;

OSG_GEN_CONTAINERPTR(PointChunk);

/*! \ingroup GrpStateOpenGLFieldTraits
    \ingroup GrpLibOSGState
 */
template <>
struct FieldTraits<PointChunk *> :
    public FieldTraitsFCPtrBase<PointChunk *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PointChunk *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_STATE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPointChunkPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPointChunkPtr"; }
};

template<> inline
const Char8 *FieldTraits<PointChunk *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPointChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<PointChunk *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPointChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<PointChunk *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPointChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<PointChunk *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPointChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<PointChunk *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPointChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<PointChunk *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPointChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<PointChunk *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPointChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<PointChunk *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPointChunkPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpStateOpenGLFieldSFields */
typedef PointerSField<PointChunk *,
                      RecordedRefCountPolicy  > SFRecPointChunkPtr;
/*! \ingroup GrpStateOpenGLFieldSFields */
typedef PointerSField<PointChunk *,
                      UnrecordedRefCountPolicy> SFUnrecPointChunkPtr;
/*! \ingroup GrpStateOpenGLFieldSFields */
typedef PointerSField<PointChunk *,
                      WeakRefCountPolicy      > SFWeakPointChunkPtr;
/*! \ingroup GrpStateOpenGLFieldSFields */
typedef PointerSField<PointChunk *,
                      NoRefCountPolicy        > SFUncountedPointChunkPtr;


/*! \ingroup GrpStateOpenGLFieldMFields */
typedef PointerMField<PointChunk *,
                      RecordedRefCountPolicy  > MFRecPointChunkPtr;
/*! \ingroup GrpStateOpenGLFieldMFields */
typedef PointerMField<PointChunk *,
                      UnrecordedRefCountPolicy> MFUnrecPointChunkPtr;
/*! \ingroup GrpStateOpenGLFieldMFields */
typedef PointerMField<PointChunk *,
                      WeakRefCountPolicy      > MFWeakPointChunkPtr;
/*! \ingroup GrpStateOpenGLFieldMFields */
typedef PointerMField<PointChunk *,
                      NoRefCountPolicy        > MFUncountedPointChunkPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpStateOpenGLFieldSFields \ingroup GrpLibOSGState */
struct SFRecPointChunkPtr : 
    public PointerSField<PointChunk *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpStateOpenGLFieldSFields \ingroup GrpLibOSGState */
struct SFUnrecPointChunkPtr : 
    public PointerSField<PointChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpStateOpenGLFieldSFields \ingroup GrpLibOSGState */
struct SFWeakPointChunkPtr :
    public PointerSField<PointChunk *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpStateOpenGLFieldSFields \ingroup GrpLibOSGState */
struct SFUncountedPointChunkPtr :
    public PointerSField<PointChunk *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpStateOpenGLFieldMFields \ingroup GrpLibOSGState */
struct MFRecPointChunkPtr :
    public PointerMField<PointChunk *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpStateOpenGLFieldMFields \ingroup GrpLibOSGState */
struct MFUnrecPointChunkPtr :
    public PointerMField<PointChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpStateOpenGLFieldMFields \ingroup GrpLibOSGState */
struct MFWeakPointChunkPtr :
    public PointerMField<PointChunk *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpStateOpenGLFieldMFields \ingroup GrpLibOSGState */
struct MFUncountedPointChunkPtr :
    public PointerMField<PointChunk *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPOINTCHUNKFIELDS_H_ */
