/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSTENCILCHUNKFIELDS_H_
#define _OSGSTENCILCHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGStateDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class StencilChunk;

OSG_GEN_CONTAINERPTR(StencilChunk);

/*! \ingroup GrpStateFieldTraits
    \ingroup GrpLibOSGState
 */
template <>
struct FieldTraits<StencilChunk *> :
    public FieldTraitsFCPtrBase<StencilChunk *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<StencilChunk *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_STATE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFStencilChunkPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFStencilChunkPtr"; }
};

template<> inline
const Char8 *FieldTraits<StencilChunk *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecStencilChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<StencilChunk *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecStencilChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<StencilChunk *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakStencilChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<StencilChunk *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdStencilChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<StencilChunk *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecStencilChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<StencilChunk *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecStencilChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<StencilChunk *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakStencilChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<StencilChunk *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdStencilChunkPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpStateFieldSFields */
typedef PointerSField<StencilChunk *,
                      RecordedRefCountPolicy  > SFRecStencilChunkPtr;
/*! \ingroup GrpStateFieldSFields */
typedef PointerSField<StencilChunk *,
                      UnrecordedRefCountPolicy> SFUnrecStencilChunkPtr;
/*! \ingroup GrpStateFieldSFields */
typedef PointerSField<StencilChunk *,
                      WeakRefCountPolicy      > SFWeakStencilChunkPtr;
/*! \ingroup GrpStateFieldSFields */
typedef PointerSField<StencilChunk *,
                      NoRefCountPolicy        > SFUncountedStencilChunkPtr;


/*! \ingroup GrpStateFieldMFields */
typedef PointerMField<StencilChunk *,
                      RecordedRefCountPolicy  > MFRecStencilChunkPtr;
/*! \ingroup GrpStateFieldMFields */
typedef PointerMField<StencilChunk *,
                      UnrecordedRefCountPolicy> MFUnrecStencilChunkPtr;
/*! \ingroup GrpStateFieldMFields */
typedef PointerMField<StencilChunk *,
                      WeakRefCountPolicy      > MFWeakStencilChunkPtr;
/*! \ingroup GrpStateFieldMFields */
typedef PointerMField<StencilChunk *,
                      NoRefCountPolicy        > MFUncountedStencilChunkPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpStateFieldSFields \ingroup GrpLibOSGState */
struct SFRecStencilChunkPtr : 
    public PointerSField<StencilChunk *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpStateFieldSFields \ingroup GrpLibOSGState */
struct SFUnrecStencilChunkPtr : 
    public PointerSField<StencilChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpStateFieldSFields \ingroup GrpLibOSGState */
struct SFWeakStencilChunkPtr :
    public PointerSField<StencilChunk *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpStateFieldSFields \ingroup GrpLibOSGState */
struct SFUncountedStencilChunkPtr :
    public PointerSField<StencilChunk *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpStateFieldMFields \ingroup GrpLibOSGState */
struct MFRecStencilChunkPtr :
    public PointerMField<StencilChunk *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpStateFieldMFields \ingroup GrpLibOSGState */
struct MFUnrecStencilChunkPtr :
    public PointerMField<StencilChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpStateFieldMFields \ingroup GrpLibOSGState */
struct MFWeakStencilChunkPtr :
    public PointerMField<StencilChunk *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpStateFieldMFields \ingroup GrpLibOSGState */
struct MFUncountedStencilChunkPtr :
    public PointerMField<StencilChunk *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSTENCILCHUNKFIELDS_H_ */
