/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMATRIXCAMERADECORATORFIELDS_H_
#define _OSGMATRIXCAMERADECORATORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGWindowDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class MatrixCameraDecorator;

OSG_GEN_CONTAINERPTR(MatrixCameraDecorator);

/*! \ingroup GrpWindowCameraFieldTraits
    \ingroup GrpLibOSGWindow
 */
template <>
struct FieldTraits<MatrixCameraDecorator *> :
    public FieldTraitsFCPtrBase<MatrixCameraDecorator *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<MatrixCameraDecorator *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_WINDOW_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFMatrixCameraDecoratorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFMatrixCameraDecoratorPtr"; }
};

template<> inline
const Char8 *FieldTraits<MatrixCameraDecorator *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMatrixCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MatrixCameraDecorator *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMatrixCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MatrixCameraDecorator *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMatrixCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MatrixCameraDecorator *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMatrixCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MatrixCameraDecorator *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMatrixCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MatrixCameraDecorator *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMatrixCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MatrixCameraDecorator *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMatrixCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MatrixCameraDecorator *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMatrixCameraDecoratorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpWindowCameraFieldSFields */
typedef PointerSField<MatrixCameraDecorator *,
                      RecordedRefCountPolicy  > SFRecMatrixCameraDecoratorPtr;
/*! \ingroup GrpWindowCameraFieldSFields */
typedef PointerSField<MatrixCameraDecorator *,
                      UnrecordedRefCountPolicy> SFUnrecMatrixCameraDecoratorPtr;
/*! \ingroup GrpWindowCameraFieldSFields */
typedef PointerSField<MatrixCameraDecorator *,
                      WeakRefCountPolicy      > SFWeakMatrixCameraDecoratorPtr;
/*! \ingroup GrpWindowCameraFieldSFields */
typedef PointerSField<MatrixCameraDecorator *,
                      NoRefCountPolicy        > SFUncountedMatrixCameraDecoratorPtr;


/*! \ingroup GrpWindowCameraFieldMFields */
typedef PointerMField<MatrixCameraDecorator *,
                      RecordedRefCountPolicy  > MFRecMatrixCameraDecoratorPtr;
/*! \ingroup GrpWindowCameraFieldMFields */
typedef PointerMField<MatrixCameraDecorator *,
                      UnrecordedRefCountPolicy> MFUnrecMatrixCameraDecoratorPtr;
/*! \ingroup GrpWindowCameraFieldMFields */
typedef PointerMField<MatrixCameraDecorator *,
                      WeakRefCountPolicy      > MFWeakMatrixCameraDecoratorPtr;
/*! \ingroup GrpWindowCameraFieldMFields */
typedef PointerMField<MatrixCameraDecorator *,
                      NoRefCountPolicy        > MFUncountedMatrixCameraDecoratorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpWindowCameraFieldSFields \ingroup GrpLibOSGWindow */
struct SFRecMatrixCameraDecoratorPtr : 
    public PointerSField<MatrixCameraDecorator *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpWindowCameraFieldSFields \ingroup GrpLibOSGWindow */
struct SFUnrecMatrixCameraDecoratorPtr : 
    public PointerSField<MatrixCameraDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowCameraFieldSFields \ingroup GrpLibOSGWindow */
struct SFWeakMatrixCameraDecoratorPtr :
    public PointerSField<MatrixCameraDecorator *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpWindowCameraFieldSFields \ingroup GrpLibOSGWindow */
struct SFUncountedMatrixCameraDecoratorPtr :
    public PointerSField<MatrixCameraDecorator *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpWindowCameraFieldMFields \ingroup GrpLibOSGWindow */
struct MFRecMatrixCameraDecoratorPtr :
    public PointerMField<MatrixCameraDecorator *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpWindowCameraFieldMFields \ingroup GrpLibOSGWindow */
struct MFUnrecMatrixCameraDecoratorPtr :
    public PointerMField<MatrixCameraDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowCameraFieldMFields \ingroup GrpLibOSGWindow */
struct MFWeakMatrixCameraDecoratorPtr :
    public PointerMField<MatrixCameraDecorator *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpWindowCameraFieldMFields \ingroup GrpLibOSGWindow */
struct MFUncountedMatrixCameraDecoratorPtr :
    public PointerMField<MatrixCameraDecorator *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMATRIXCAMERADECORATORFIELDS_H_ */
