/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ShaderExecutableVarChunk!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGConfig.h"



#include "OSGShaderProgramVariableChunk.h" // ProgramVarChunks Class
#include "OSGShaderProgramVariables.h"  // Variables Class

#include "OSGShaderExecutableVarChunkBase.h"
#include "OSGShaderExecutableVarChunk.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ShaderExecutableVarChunk
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var ShaderProgramVariableChunk * ShaderExecutableVarChunkBase::_mfProgramVarChunks
    
*/

/*! \var ShaderProgramVariables * ShaderExecutableVarChunkBase::_sfVariables
    fragment program object
*/

/*! \var Int32           ShaderExecutableVarChunkBase::_mfVariableLocations
    fragment program object
*/

/*! \var UInt32          ShaderExecutableVarChunkBase::_sfActiveShader
    fragment program object
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ShaderExecutableVarChunk *, nsOSG>::_type(
    "ShaderExecutableVarChunkPtr", 
    "StateChunkPtr", 
    ShaderExecutableVarChunk::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ShaderExecutableVarChunk *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ShaderExecutableVarChunk *,
                           nsOSG)

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ShaderExecutableVarChunk *,
                           nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ShaderExecutableVarChunkBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new MFUncountedShaderProgramVariableChunkPtr::Description(
        MFUncountedShaderProgramVariableChunkPtr::getClassType(),
        "programVarChunks",
        "",
        ProgramVarChunksFieldId, ProgramVarChunksFieldMask,
        false,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast     <FieldEditMethodSig>(&ShaderExecutableVarChunk::invalidEditField),
        static_cast     <FieldGetMethodSig >(&ShaderExecutableVarChunk::invalidGetField));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecChildShaderProgramVariablesPtr::Description(
        SFUnrecChildShaderProgramVariablesPtr::getClassType(),
        "variables",
        "fragment program object\n",
        VariablesFieldId, VariablesFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&ShaderExecutableVarChunk::editHandleVariables),
        static_cast<FieldGetMethodSig >(&ShaderExecutableVarChunk::getHandleVariables));

    oType.addInitialDesc(pDesc);

    pDesc = new MFInt32::Description(
        MFInt32::getClassType(),
        "variableLocations",
        "fragment program object\n",
        VariableLocationsFieldId, VariableLocationsFieldMask,
        true,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&ShaderExecutableVarChunk::editHandleVariableLocations),
        static_cast<FieldGetMethodSig >(&ShaderExecutableVarChunk::getHandleVariableLocations));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "activeShader",
        "fragment program object\n",
        ActiveShaderFieldId, ActiveShaderFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&ShaderExecutableVarChunk::editHandleActiveShader),
        static_cast<FieldGetMethodSig >(&ShaderExecutableVarChunk::getHandleActiveShader));

    oType.addInitialDesc(pDesc);
}


ShaderExecutableVarChunkBase::TypeObject ShaderExecutableVarChunkBase::_type(
    ShaderExecutableVarChunkBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ShaderExecutableVarChunkBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&ShaderExecutableVarChunk::initMethod),
    reinterpret_cast<ExitContainerF>(&ShaderExecutableVarChunk::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(
        reinterpret_cast<void *>(&ShaderExecutableVarChunk::classDescInserter)),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"ShaderExecutableVarChunk\"\n"
    "   parent=\"StateChunk\"\n"
    "   library=\"System\"\n"
    "   pointerfieldtypes=\"both\"\n"
    "   structure=\"concrete\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   decoratable=\"false\"\n"
    "   useLocalIncludes=\"false\"\n"
    "   docGroupBase=\"GrpSystemShader\"\n"
    "   >\n"
    "  <Field\n"
    "\t name=\"programVarChunks\"\n"
    "\t type=\"ShaderProgramVariableChunk\"\n"
    "\t cardinality=\"multi\"\n"
    "\t visibility=\"external\"\n"
    "\t access=\"none\"\n"
    "     category=\"uncountedpointer\"\n"
    "     >\n"
    "  </Field>\n"
    "<!--  <Field\n"
    "\t name=\"ShaderExecytableChunk\"\n"
    "\t type=\"ShaderExecutableChunk\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"external\"\n"
    "\t defaultValue=\"NULL\"\n"
    "\t access=\"public\"\n"
    "     category=\"pointer\"\n"
    "\t >\n"
    "  </Field> -->\n"
    "  <Field\n"
    "\t name=\"variables\"\n"
    "\t type=\"ShaderProgramVariables\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"external\"\n"
    "\t access=\"public\"\n"
    "     category=\"childpointer\"\n"
    "     childParentType=\"FieldContainer\"\n"
    "     linkParentField=\"Parents\"\n"
    "\t >\n"
    "\tfragment program object\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"variableLocations\"\n"
    "\t type=\"Int32\"\n"
    "\t cardinality=\"multi\"\n"
    "\t visibility=\"internal\"\n"
    "\t access=\"protected\"\n"
    "\t >\n"
    "\tfragment program object\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"activeShader\"\n"
    "\t type=\"UInt32\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"internal\"\n"
    "\t access=\"protected\"\n"
    "\t >\n"
    "\tfragment program object\n"
    "  </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ShaderExecutableVarChunkBase::getType(void)
{
    return _type;
}

const FieldContainerType &ShaderExecutableVarChunkBase::getType(void) const
{
    return _type;
}

UInt32 ShaderExecutableVarChunkBase::getContainerSize(void) const
{
    return sizeof(ShaderExecutableVarChunk);
}

/*------------------------- decorator get ------------------------------*/



//! Get the ShaderExecutableVarChunk::_sfVariables field.
const SFUnrecChildShaderProgramVariablesPtr *ShaderExecutableVarChunkBase::getSFVariables(void) const
{
    return &_sfVariables;
}

SFUnrecChildShaderProgramVariablesPtr *ShaderExecutableVarChunkBase::editSFVariables      (void)
{
    editSField(VariablesFieldMask);

    return &_sfVariables;
}

//! Get the value of the ShaderExecutableVarChunk::_sfVariables field.
ShaderProgramVariables * ShaderExecutableVarChunkBase::getVariables(void) const
{
    return _sfVariables.getValue();
}

//! Set the value of the ShaderExecutableVarChunk::_sfVariables field.
void ShaderExecutableVarChunkBase::setVariables(ShaderProgramVariables * const value)
{
    editSField(VariablesFieldMask);

    _sfVariables.setValue(value);
}


MFInt32 *ShaderExecutableVarChunkBase::editMFVariableLocations(void)
{
    editMField(VariableLocationsFieldMask, _mfVariableLocations);

    return &_mfVariableLocations;
}

const MFInt32 *ShaderExecutableVarChunkBase::getMFVariableLocations(void) const
{
    return &_mfVariableLocations;
}


SFUInt32 *ShaderExecutableVarChunkBase::editSFActiveShader(void)
{
    editSField(ActiveShaderFieldMask);

    return &_sfActiveShader;
}

const SFUInt32 *ShaderExecutableVarChunkBase::getSFActiveShader(void) const
{
    return &_sfActiveShader;
}






/*------------------------------ access -----------------------------------*/

SizeT ShaderExecutableVarChunkBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ProgramVarChunksFieldMask & whichField))
    {
        returnValue += _mfProgramVarChunks.getBinSize();
    }
    if(FieldBits::NoField != (VariablesFieldMask & whichField))
    {
        returnValue += _sfVariables.getBinSize();
    }
    if(FieldBits::NoField != (VariableLocationsFieldMask & whichField))
    {
        returnValue += _mfVariableLocations.getBinSize();
    }
    if(FieldBits::NoField != (ActiveShaderFieldMask & whichField))
    {
        returnValue += _sfActiveShader.getBinSize();
    }

    return returnValue;
}

void ShaderExecutableVarChunkBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ProgramVarChunksFieldMask & whichField))
    {
        _mfProgramVarChunks.copyToBin(pMem);
    }
    if(FieldBits::NoField != (VariablesFieldMask & whichField))
    {
        _sfVariables.copyToBin(pMem);
    }
    if(FieldBits::NoField != (VariableLocationsFieldMask & whichField))
    {
        _mfVariableLocations.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ActiveShaderFieldMask & whichField))
    {
        _sfActiveShader.copyToBin(pMem);
    }
}

void ShaderExecutableVarChunkBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ProgramVarChunksFieldMask & whichField))
    {
        editMField(ProgramVarChunksFieldMask, _mfProgramVarChunks);
        _mfProgramVarChunks.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (VariablesFieldMask & whichField))
    {
        editSField(VariablesFieldMask);
        _sfVariables.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (VariableLocationsFieldMask & whichField))
    {
        editMField(VariableLocationsFieldMask, _mfVariableLocations);
        _mfVariableLocations.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ActiveShaderFieldMask & whichField))
    {
        editSField(ActiveShaderFieldMask);
        _sfActiveShader.copyFromBin(pMem);
    }
}

//! create a new instance of the class
ShaderExecutableVarChunkTransitPtr ShaderExecutableVarChunkBase::createLocal(BitVector bFlags)
{
    ShaderExecutableVarChunkTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ShaderExecutableVarChunk>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ShaderExecutableVarChunkTransitPtr ShaderExecutableVarChunkBase::createDependent(BitVector bFlags)
{
    ShaderExecutableVarChunkTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ShaderExecutableVarChunk>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ShaderExecutableVarChunkTransitPtr ShaderExecutableVarChunkBase::create(void)
{
    ShaderExecutableVarChunkTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ShaderExecutableVarChunk>(tmpPtr);
    }

    return fc;
}

ShaderExecutableVarChunk *ShaderExecutableVarChunkBase::createEmptyLocal(BitVector bFlags)
{
    ShaderExecutableVarChunk *returnValue;

    newPtr<ShaderExecutableVarChunk>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ShaderExecutableVarChunk *ShaderExecutableVarChunkBase::createEmpty(void)
{
    ShaderExecutableVarChunk *returnValue;

    newPtr<ShaderExecutableVarChunk>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ShaderExecutableVarChunkBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ShaderExecutableVarChunk *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ShaderExecutableVarChunk *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ShaderExecutableVarChunkBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ShaderExecutableVarChunk *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ShaderExecutableVarChunk *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ShaderExecutableVarChunkBase::shallowCopy(void) const
{
    ShaderExecutableVarChunk *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ShaderExecutableVarChunk *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ShaderExecutableVarChunkBase::ShaderExecutableVarChunkBase(void) :
    Inherited(),
    _mfProgramVarChunks       (),
    _sfVariables              (this,
                          VariablesFieldId,
                          ShaderProgramVariables::ParentsFieldId),
    _mfVariableLocations      (),
    _sfActiveShader           ()
{
}

ShaderExecutableVarChunkBase::ShaderExecutableVarChunkBase(const ShaderExecutableVarChunkBase &source) :
    Inherited(source),
    _mfProgramVarChunks       (),
    _sfVariables              (this,
                          VariablesFieldId,
                          ShaderProgramVariables::ParentsFieldId),
    _mfVariableLocations      (source._mfVariableLocations      ),
    _sfActiveShader           (source._sfActiveShader           )
{
}


/*-------------------------- destructors ----------------------------------*/

ShaderExecutableVarChunkBase::~ShaderExecutableVarChunkBase(void)
{
}

/*-------------------------------------------------------------------------*/
/* Child linking                                                           */

bool ShaderExecutableVarChunkBase::unlinkChild(
    FieldContainer * const pChild,
    UInt16           const childFieldId)
{
    if(childFieldId == VariablesFieldId)
    {
        ShaderProgramVariables * pTypedChild =
            dynamic_cast<ShaderProgramVariables *>(pChild);

        if(pTypedChild != NULL)
        {
            if(_sfVariables.getValue() == pTypedChild)
            {
                editSField(VariablesFieldMask);

                _sfVariables.setValue(NULL);

                return true;
            }

            SWARNING << "Parent (["        << this
                     << "] id ["           << this->getId()
                     << "] type ["         << this->getType().getCName()
                     << "] childFieldId [" << childFieldId
                     << "]) - Child (["    << pChild
                     << "] id ["           << pChild->getId()
                     << "] type ["         << pChild->getType().getCName()
                     << "]): link inconsistent!"
                     << std::endl;

            return false;
        }

        return false;
    }


    return Inherited::unlinkChild(pChild, childFieldId);
}

void ShaderExecutableVarChunkBase::onCreate(const ShaderExecutableVarChunk *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        ShaderExecutableVarChunk *pThis = static_cast<ShaderExecutableVarChunk *>(this);

        pThis->setVariables(source->getVariables());
    }
}

GetFieldHandlePtr ShaderExecutableVarChunkBase::getHandleProgramVarChunks (void) const
{
    MFUncountedShaderProgramVariableChunkPtr::GetHandlePtr returnValue;

    return returnValue;
}

EditFieldHandlePtr ShaderExecutableVarChunkBase::editHandleProgramVarChunks(void)
{
    EditFieldHandlePtr returnValue;

    return returnValue;
}

GetFieldHandlePtr ShaderExecutableVarChunkBase::getHandleVariables       (void) const
{
    SFUnrecChildShaderProgramVariablesPtr::GetHandlePtr returnValue(
        new  SFUnrecChildShaderProgramVariablesPtr::GetHandle(
             &_sfVariables,
             this->getType().getFieldDesc(VariablesFieldId),
             const_cast<ShaderExecutableVarChunkBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ShaderExecutableVarChunkBase::editHandleVariables      (void)
{
    SFUnrecChildShaderProgramVariablesPtr::EditHandlePtr returnValue(
        new  SFUnrecChildShaderProgramVariablesPtr::EditHandle(
             &_sfVariables,
             this->getType().getFieldDesc(VariablesFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&ShaderExecutableVarChunk::setVariables,
                    static_cast<ShaderExecutableVarChunk *>(this), _1));

    editSField(VariablesFieldMask);

    return returnValue;
}

GetFieldHandlePtr ShaderExecutableVarChunkBase::getHandleVariableLocations (void) const
{
    MFInt32::GetHandlePtr returnValue(
        new  MFInt32::GetHandle(
             &_mfVariableLocations,
             this->getType().getFieldDesc(VariableLocationsFieldId),
             const_cast<ShaderExecutableVarChunkBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ShaderExecutableVarChunkBase::editHandleVariableLocations(void)
{
    MFInt32::EditHandlePtr returnValue(
        new  MFInt32::EditHandle(
             &_mfVariableLocations,
             this->getType().getFieldDesc(VariableLocationsFieldId),
             this));


    editMField(VariableLocationsFieldMask, _mfVariableLocations);

    return returnValue;
}

GetFieldHandlePtr ShaderExecutableVarChunkBase::getHandleActiveShader    (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfActiveShader,
             this->getType().getFieldDesc(ActiveShaderFieldId),
             const_cast<ShaderExecutableVarChunkBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ShaderExecutableVarChunkBase::editHandleActiveShader   (void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfActiveShader,
             this->getType().getFieldDesc(ActiveShaderFieldId),
             this));


    editSField(ActiveShaderFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void ShaderExecutableVarChunkBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ShaderExecutableVarChunk *pThis = static_cast<ShaderExecutableVarChunk *>(this);

    pThis->execSync(static_cast<ShaderExecutableVarChunk *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ShaderExecutableVarChunkBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ShaderExecutableVarChunk *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ShaderExecutableVarChunk *>(pRefAspect),
                  dynamic_cast<const ShaderExecutableVarChunk *>(this));

    return returnValue;
}
#endif

void ShaderExecutableVarChunkBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<ShaderExecutableVarChunk *>(this)->setVariables(NULL);

#ifdef OSG_MT_CPTR_ASPECT
    AspectOffsetStore oOffsets;

    _pAspectStore->fillOffsetArray(oOffsets, this);
#endif

#ifdef OSG_MT_CPTR_ASPECT
    _mfVariableLocations.terminateShare(Thread::getCurrentAspect(),
                                      oOffsets);
#endif
}


OSG_END_NAMESPACE
