
MESSAGE(STATUS "Prepare OSGCompute")

GET_FILENAME_COMPONENT(_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake")
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake/cuda")

FIND_PACKAGE(CUDA QUIET)

INCLUDE(ConfigurePackagesExt)

IF(NOT OSG_BUILD_DEPENDEND)
  OSG_CONFIGURE_NVSDKCOMMON()
  OSG_CONFIGURE_NVOCLUTILS()
  OSG_CONFIGURE_CUDACOMMON()
  OSG_CONFIGURE_CUDAUTIL()
  OSG_CONFIGURE_CUDPP()
  OSG_CONFIGURE_CUDAPARTSDK()
ENDIF(NOT OSG_BUILD_DEPENDEND)

MESSAGE(STATUS "NV Status: NV:${OSG_NVSDKCOMMON_FOUND}")
MESSAGE(STATUS "Cuda Status: CC:${OSG_CUDACOMMON_FOUND} CU:${OSG_CUDAUTIL_FOUND} CP:${OSG_CUDPP_FOUND}")
MESSAGE(STATUS "OCL Status : NV:${OSG_NVOCLUTILS_FOUND}")

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_NVSDKCOMMON 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_NVOCLUTILS 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDACOMMON 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDAUTIL 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDPP 1")
