/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFILECONTEXTATTACHMENTFIELDS_H_
#define _OSGFILECONTEXTATTACHMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class FileContextAttachment;

OSG_GEN_CONTAINERPTR(FileContextAttachment);
/*! \ingroup GrpSystemFileIOFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<FileContextAttachment *, nsOSG> :
    public FieldTraitsFCPtrBase<FileContextAttachment *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<FileContextAttachment *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<FileContextAttachment *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecFileContextAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<FileContextAttachment *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecFileContextAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<FileContextAttachment *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakFileContextAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<FileContextAttachment *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdFileContextAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<FileContextAttachment *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecFileContextAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<FileContextAttachment *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecFileContextAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<FileContextAttachment *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakFileContextAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<FileContextAttachment *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdFileContextAttachmentPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemFileIOFieldSFields */
typedef PointerSField<FileContextAttachment *,
                      RecordedRefCountPolicy, nsOSG  > SFRecFileContextAttachmentPtr;
/*! \ingroup GrpSystemFileIOFieldSFields */
typedef PointerSField<FileContextAttachment *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecFileContextAttachmentPtr;
/*! \ingroup GrpSystemFileIOFieldSFields */
typedef PointerSField<FileContextAttachment *,
                      WeakRefCountPolicy, nsOSG      > SFWeakFileContextAttachmentPtr;
/*! \ingroup GrpSystemFileIOFieldSFields */
typedef PointerSField<FileContextAttachment *,
                      NoRefCountPolicy, nsOSG        > SFUncountedFileContextAttachmentPtr;


/*! \ingroup GrpSystemFileIOFieldMFields */
typedef PointerMField<FileContextAttachment *,
                      RecordedRefCountPolicy, nsOSG  > MFRecFileContextAttachmentPtr;
/*! \ingroup GrpSystemFileIOFieldMFields */
typedef PointerMField<FileContextAttachment *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecFileContextAttachmentPtr;
/*! \ingroup GrpSystemFileIOFieldMFields */
typedef PointerMField<FileContextAttachment *,
                      WeakRefCountPolicy, nsOSG      > MFWeakFileContextAttachmentPtr;
/*! \ingroup GrpSystemFileIOFieldMFields */
typedef PointerMField<FileContextAttachment *,
                      NoRefCountPolicy, nsOSG        > MFUncountedFileContextAttachmentPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemFileIOFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecFileContextAttachmentPtr : 
    public PointerSField<FileContextAttachment *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFileIOFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecFileContextAttachmentPtr : 
    public PointerSField<FileContextAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFileIOFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakFileContextAttachmentPtr :
    public PointerSField<FileContextAttachment *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemFileIOFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedFileContextAttachmentPtr :
    public PointerSField<FileContextAttachment *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemFileIOFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecFileContextAttachmentPtr :
    public PointerMField<FileContextAttachment *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemFileIOFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecFileContextAttachmentPtr :
    public PointerMField<FileContextAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFileIOFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakFileContextAttachmentPtr :
    public PointerMField<FileContextAttachment *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemFileIOFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedFileContextAttachmentPtr :
    public PointerMField<FileContextAttachment *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGFILECONTEXTATTACHMENTFIELDS_H_ */
