/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMAPHELPERFIELDS_H_
#define _OSGMAPHELPERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class MapHelper;

OSG_GEN_CONTAINERPTR(MapHelper);

/*! \ingroup GrpBaseFieldContainerFieldTraits
 */
template <>
struct FieldTraits<MapHelper *> :
    public FieldTraitsFCPtrBase<MapHelper *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<MapHelper *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_BASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFMapHelperPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFMapHelperPtr"; }
};

template<> inline
const Char8 *FieldTraits<MapHelper *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMapHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<MapHelper *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMapHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<MapHelper *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMapHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<MapHelper *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMapHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<MapHelper *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMapHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<MapHelper *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMapHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<MapHelper *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMapHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<MapHelper *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMapHelperPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<MapHelper *,
                      RecordedRefCountPolicy  > SFRecMapHelperPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<MapHelper *,
                      UnrecordedRefCountPolicy> SFUnrecMapHelperPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<MapHelper *,
                      WeakRefCountPolicy      > SFWeakMapHelperPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<MapHelper *,
                      NoRefCountPolicy        > SFUncountedMapHelperPtr;


/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<MapHelper *,
                      RecordedRefCountPolicy  > MFRecMapHelperPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<MapHelper *,
                      UnrecordedRefCountPolicy> MFUnrecMapHelperPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<MapHelper *,
                      WeakRefCountPolicy      > MFWeakMapHelperPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<MapHelper *,
                      NoRefCountPolicy        > MFUncountedMapHelperPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBaseFieldContainerFieldSFields */
struct SFRecMapHelperPtr : 
    public PointerSField<MapHelper *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields */
struct SFUnrecMapHelperPtr : 
    public PointerSField<MapHelper *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields */
struct SFWeakMapHelperPtr :
    public PointerSField<MapHelper *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields */
struct SFUncountedMapHelperPtr :
    public PointerSField<MapHelper *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpBaseFieldContainerFieldMFields */
struct MFRecMapHelperPtr :
    public PointerMField<MapHelper *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields */
struct MFUnrecMapHelperPtr :
    public PointerMField<MapHelper *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldMFields */
struct MFWeakMapHelperPtr :
    public PointerMField<MapHelper *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields */
struct MFUncountedMapHelperPtr :
    public PointerMField<MapHelper *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMAPHELPERFIELDS_H_ */
