/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TextureChunk
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTURECHUNKBASE_H_
#define _OSGTEXTURECHUNKBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGBaseTypes.h"

#include "OSGTextureBaseChunk.h" // Parent

#include "OSGImageFields.h" // Image type
#include "OSGGLenumFields.h" // InternalFormat type
#include "OSGGLenumFields.h" // ExternalFormat type
#include "OSGBoolFields.h" // Scale type
#include "OSGUInt32Fields.h" // Frame type
#include "OSGGLenumFields.h" // MinFilter type
#include "OSGGLenumFields.h" // MagFilter type
#include "OSGGLenumFields.h" // WrapS type
#include "OSGGLenumFields.h" // WrapT type
#include "OSGGLenumFields.h" // WrapR type
#include "OSGGLenumFields.h" // EnvMode type
#include "OSGColor4fFields.h" // EnvColor type
#include "OSGGLenumFields.h" // EnvCombineRGB type
#include "OSGGLenumFields.h" // EnvCombineAlpha type
#include "OSGReal32Fields.h" // EnvScaleRGB type
#include "OSGReal32Fields.h" // EnvScaleAlpha type
#include "OSGGLenumFields.h" // EnvSource0RGB type
#include "OSGGLenumFields.h" // EnvSource1RGB type
#include "OSGGLenumFields.h" // EnvSource2RGB type
#include "OSGGLenumFields.h" // EnvSource0Alpha type
#include "OSGGLenumFields.h" // EnvSource1Alpha type
#include "OSGGLenumFields.h" // EnvSource2Alpha type
#include "OSGGLenumFields.h" // EnvOperand0RGB type
#include "OSGGLenumFields.h" // EnvOperand1RGB type
#include "OSGGLenumFields.h" // EnvOperand2RGB type
#include "OSGGLenumFields.h" // EnvOperand0Alpha type
#include "OSGGLenumFields.h" // EnvOperand1Alpha type
#include "OSGGLenumFields.h" // EnvOperand2Alpha type
#include "OSGGLenumFields.h" // GLId type
#include "OSGInt32Fields.h" // IgnoreGLForAspect type
#include "OSGBoolFields.h" // PointSprite type
#include "OSGReal32Fields.h" // Priority type
#include "OSGGLenumFields.h" // ShaderOperation type
#include "OSGGLenumFields.h" // ShaderInput type
#include "OSGReal32Fields.h" // ShaderOffsetMatrix type
#include "OSGReal32Fields.h" // ShaderOffsetScale type
#include "OSGReal32Fields.h" // ShaderOffsetBias type
#include "OSGGLenumFields.h" // ShaderRGBADotProduct type
#include "OSGUInt8Fields.h" // ShaderCullModes type
#include "OSGVec3fFields.h" // ShaderConstEye type
#include "OSGReal32Fields.h" // LodBias type
#include "OSGInt32Fields.h" // DirtyLeft type
#include "OSGInt32Fields.h" // DirtyMinX type
#include "OSGInt32Fields.h" // DirtyMaxX type
#include "OSGInt32Fields.h" // DirtyMinY type
#include "OSGInt32Fields.h" // DirtyMaxY type
#include "OSGInt32Fields.h" // DirtyMinZ type
#include "OSGInt32Fields.h" // DirtyMaxZ type
#include "OSGReal32Fields.h" // Anisotropy type
#include "OSGColor4fFields.h" // BorderColor type
#include "OSGGLenumFields.h" // CompareMode type
#include "OSGGLenumFields.h" // CompareFunc type
#include "OSGGLenumFields.h" // DepthMode type
#include "OSGUInt32Fields.h" // BorderWidth type
#include "OSGUInt32Fields.h" // NPOTMatrixScale type

#include "OSGTextureChunkFields.h"

OSG_BEGIN_NAMESPACE

class TextureChunk;

//! \brief TextureChunk Base Class.

class OSG_SYSTEM_DLLMAPPING TextureChunkBase : public TextureBaseChunk
{
  public:

    typedef TextureBaseChunk Inherited;
    typedef TextureBaseChunk ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(TextureChunk);

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        ImageFieldId = Inherited::NextFieldId,
        InternalFormatFieldId = ImageFieldId + 1,
        ExternalFormatFieldId = InternalFormatFieldId + 1,
        ScaleFieldId = ExternalFormatFieldId + 1,
        FrameFieldId = ScaleFieldId + 1,
        MinFilterFieldId = FrameFieldId + 1,
        MagFilterFieldId = MinFilterFieldId + 1,
        WrapSFieldId = MagFilterFieldId + 1,
        WrapTFieldId = WrapSFieldId + 1,
        WrapRFieldId = WrapTFieldId + 1,
        EnvModeFieldId = WrapRFieldId + 1,
        EnvColorFieldId = EnvModeFieldId + 1,
        EnvCombineRGBFieldId = EnvColorFieldId + 1,
        EnvCombineAlphaFieldId = EnvCombineRGBFieldId + 1,
        EnvScaleRGBFieldId = EnvCombineAlphaFieldId + 1,
        EnvScaleAlphaFieldId = EnvScaleRGBFieldId + 1,
        EnvSource0RGBFieldId = EnvScaleAlphaFieldId + 1,
        EnvSource1RGBFieldId = EnvSource0RGBFieldId + 1,
        EnvSource2RGBFieldId = EnvSource1RGBFieldId + 1,
        EnvSource0AlphaFieldId = EnvSource2RGBFieldId + 1,
        EnvSource1AlphaFieldId = EnvSource0AlphaFieldId + 1,
        EnvSource2AlphaFieldId = EnvSource1AlphaFieldId + 1,
        EnvOperand0RGBFieldId = EnvSource2AlphaFieldId + 1,
        EnvOperand1RGBFieldId = EnvOperand0RGBFieldId + 1,
        EnvOperand2RGBFieldId = EnvOperand1RGBFieldId + 1,
        EnvOperand0AlphaFieldId = EnvOperand2RGBFieldId + 1,
        EnvOperand1AlphaFieldId = EnvOperand0AlphaFieldId + 1,
        EnvOperand2AlphaFieldId = EnvOperand1AlphaFieldId + 1,
        GLIdFieldId = EnvOperand2AlphaFieldId + 1,
        IgnoreGLForAspectFieldId = GLIdFieldId + 1,
        PointSpriteFieldId = IgnoreGLForAspectFieldId + 1,
        PriorityFieldId = PointSpriteFieldId + 1,
        ShaderOperationFieldId = PriorityFieldId + 1,
        ShaderInputFieldId = ShaderOperationFieldId + 1,
        ShaderOffsetMatrixFieldId = ShaderInputFieldId + 1,
        ShaderOffsetScaleFieldId = ShaderOffsetMatrixFieldId + 1,
        ShaderOffsetBiasFieldId = ShaderOffsetScaleFieldId + 1,
        ShaderRGBADotProductFieldId = ShaderOffsetBiasFieldId + 1,
        ShaderCullModesFieldId = ShaderRGBADotProductFieldId + 1,
        ShaderConstEyeFieldId = ShaderCullModesFieldId + 1,
        LodBiasFieldId = ShaderConstEyeFieldId + 1,
        DirtyLeftFieldId = LodBiasFieldId + 1,
        DirtyMinXFieldId = DirtyLeftFieldId + 1,
        DirtyMaxXFieldId = DirtyMinXFieldId + 1,
        DirtyMinYFieldId = DirtyMaxXFieldId + 1,
        DirtyMaxYFieldId = DirtyMinYFieldId + 1,
        DirtyMinZFieldId = DirtyMaxYFieldId + 1,
        DirtyMaxZFieldId = DirtyMinZFieldId + 1,
        AnisotropyFieldId = DirtyMaxZFieldId + 1,
        BorderColorFieldId = AnisotropyFieldId + 1,
        CompareModeFieldId = BorderColorFieldId + 1,
        CompareFuncFieldId = CompareModeFieldId + 1,
        DepthModeFieldId = CompareFuncFieldId + 1,
        BorderWidthFieldId = DepthModeFieldId + 1,
        NPOTMatrixScaleFieldId = BorderWidthFieldId + 1,
        NextFieldId = NPOTMatrixScaleFieldId + 1
    };

    static const OSG::BitVector ImageFieldMask =
        (TypeTraits<BitVector>::One << ImageFieldId);
    static const OSG::BitVector InternalFormatFieldMask =
        (TypeTraits<BitVector>::One << InternalFormatFieldId);
    static const OSG::BitVector ExternalFormatFieldMask =
        (TypeTraits<BitVector>::One << ExternalFormatFieldId);
    static const OSG::BitVector ScaleFieldMask =
        (TypeTraits<BitVector>::One << ScaleFieldId);
    static const OSG::BitVector FrameFieldMask =
        (TypeTraits<BitVector>::One << FrameFieldId);
    static const OSG::BitVector MinFilterFieldMask =
        (TypeTraits<BitVector>::One << MinFilterFieldId);
    static const OSG::BitVector MagFilterFieldMask =
        (TypeTraits<BitVector>::One << MagFilterFieldId);
    static const OSG::BitVector WrapSFieldMask =
        (TypeTraits<BitVector>::One << WrapSFieldId);
    static const OSG::BitVector WrapTFieldMask =
        (TypeTraits<BitVector>::One << WrapTFieldId);
    static const OSG::BitVector WrapRFieldMask =
        (TypeTraits<BitVector>::One << WrapRFieldId);
    static const OSG::BitVector EnvModeFieldMask =
        (TypeTraits<BitVector>::One << EnvModeFieldId);
    static const OSG::BitVector EnvColorFieldMask =
        (TypeTraits<BitVector>::One << EnvColorFieldId);
    static const OSG::BitVector EnvCombineRGBFieldMask =
        (TypeTraits<BitVector>::One << EnvCombineRGBFieldId);
    static const OSG::BitVector EnvCombineAlphaFieldMask =
        (TypeTraits<BitVector>::One << EnvCombineAlphaFieldId);
    static const OSG::BitVector EnvScaleRGBFieldMask =
        (TypeTraits<BitVector>::One << EnvScaleRGBFieldId);
    static const OSG::BitVector EnvScaleAlphaFieldMask =
        (TypeTraits<BitVector>::One << EnvScaleAlphaFieldId);
    static const OSG::BitVector EnvSource0RGBFieldMask =
        (TypeTraits<BitVector>::One << EnvSource0RGBFieldId);
    static const OSG::BitVector EnvSource1RGBFieldMask =
        (TypeTraits<BitVector>::One << EnvSource1RGBFieldId);
    static const OSG::BitVector EnvSource2RGBFieldMask =
        (TypeTraits<BitVector>::One << EnvSource2RGBFieldId);
    static const OSG::BitVector EnvSource0AlphaFieldMask =
        (TypeTraits<BitVector>::One << EnvSource0AlphaFieldId);
    static const OSG::BitVector EnvSource1AlphaFieldMask =
        (TypeTraits<BitVector>::One << EnvSource1AlphaFieldId);
    static const OSG::BitVector EnvSource2AlphaFieldMask =
        (TypeTraits<BitVector>::One << EnvSource2AlphaFieldId);
    static const OSG::BitVector EnvOperand0RGBFieldMask =
        (TypeTraits<BitVector>::One << EnvOperand0RGBFieldId);
    static const OSG::BitVector EnvOperand1RGBFieldMask =
        (TypeTraits<BitVector>::One << EnvOperand1RGBFieldId);
    static const OSG::BitVector EnvOperand2RGBFieldMask =
        (TypeTraits<BitVector>::One << EnvOperand2RGBFieldId);
    static const OSG::BitVector EnvOperand0AlphaFieldMask =
        (TypeTraits<BitVector>::One << EnvOperand0AlphaFieldId);
    static const OSG::BitVector EnvOperand1AlphaFieldMask =
        (TypeTraits<BitVector>::One << EnvOperand1AlphaFieldId);
    static const OSG::BitVector EnvOperand2AlphaFieldMask =
        (TypeTraits<BitVector>::One << EnvOperand2AlphaFieldId);
    static const OSG::BitVector GLIdFieldMask =
        (TypeTraits<BitVector>::One << GLIdFieldId);
    static const OSG::BitVector IgnoreGLForAspectFieldMask =
        (TypeTraits<BitVector>::One << IgnoreGLForAspectFieldId);
    static const OSG::BitVector PointSpriteFieldMask =
        (TypeTraits<BitVector>::One << PointSpriteFieldId);
    static const OSG::BitVector PriorityFieldMask =
        (TypeTraits<BitVector>::One << PriorityFieldId);
    static const OSG::BitVector ShaderOperationFieldMask =
        (TypeTraits<BitVector>::One << ShaderOperationFieldId);
    static const OSG::BitVector ShaderInputFieldMask =
        (TypeTraits<BitVector>::One << ShaderInputFieldId);
    static const OSG::BitVector ShaderOffsetMatrixFieldMask =
        (TypeTraits<BitVector>::One << ShaderOffsetMatrixFieldId);
    static const OSG::BitVector ShaderOffsetScaleFieldMask =
        (TypeTraits<BitVector>::One << ShaderOffsetScaleFieldId);
    static const OSG::BitVector ShaderOffsetBiasFieldMask =
        (TypeTraits<BitVector>::One << ShaderOffsetBiasFieldId);
    static const OSG::BitVector ShaderRGBADotProductFieldMask =
        (TypeTraits<BitVector>::One << ShaderRGBADotProductFieldId);
    static const OSG::BitVector ShaderCullModesFieldMask =
        (TypeTraits<BitVector>::One << ShaderCullModesFieldId);
    static const OSG::BitVector ShaderConstEyeFieldMask =
        (TypeTraits<BitVector>::One << ShaderConstEyeFieldId);
    static const OSG::BitVector LodBiasFieldMask =
        (TypeTraits<BitVector>::One << LodBiasFieldId);
    static const OSG::BitVector DirtyLeftFieldMask =
        (TypeTraits<BitVector>::One << DirtyLeftFieldId);
    static const OSG::BitVector DirtyMinXFieldMask =
        (TypeTraits<BitVector>::One << DirtyMinXFieldId);
    static const OSG::BitVector DirtyMaxXFieldMask =
        (TypeTraits<BitVector>::One << DirtyMaxXFieldId);
    static const OSG::BitVector DirtyMinYFieldMask =
        (TypeTraits<BitVector>::One << DirtyMinYFieldId);
    static const OSG::BitVector DirtyMaxYFieldMask =
        (TypeTraits<BitVector>::One << DirtyMaxYFieldId);
    static const OSG::BitVector DirtyMinZFieldMask =
        (TypeTraits<BitVector>::One << DirtyMinZFieldId);
    static const OSG::BitVector DirtyMaxZFieldMask =
        (TypeTraits<BitVector>::One << DirtyMaxZFieldId);
    static const OSG::BitVector AnisotropyFieldMask =
        (TypeTraits<BitVector>::One << AnisotropyFieldId);
    static const OSG::BitVector BorderColorFieldMask =
        (TypeTraits<BitVector>::One << BorderColorFieldId);
    static const OSG::BitVector CompareModeFieldMask =
        (TypeTraits<BitVector>::One << CompareModeFieldId);
    static const OSG::BitVector CompareFuncFieldMask =
        (TypeTraits<BitVector>::One << CompareFuncFieldId);
    static const OSG::BitVector DepthModeFieldMask =
        (TypeTraits<BitVector>::One << DepthModeFieldId);
    static const OSG::BitVector BorderWidthFieldMask =
        (TypeTraits<BitVector>::One << BorderWidthFieldId);
    static const OSG::BitVector NPOTMatrixScaleFieldMask =
        (TypeTraits<BitVector>::One << NPOTMatrixScaleFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

            const SFImagePtr          *getSFImage           (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFInternalFormat  (void);
#endif
                  SFGLenum            *editSFInternalFormat (void);
            const SFGLenum            *getSFInternalFormat  (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFExternalFormat  (void);
#endif
                  SFGLenum            *editSFExternalFormat (void);
            const SFGLenum            *getSFExternalFormat  (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFBool              *getSFScale           (void);
#endif
                  SFBool              *editSFScale          (void);
            const SFBool              *getSFScale           (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFUInt32            *getSFFrame           (void);
#endif
                  SFUInt32            *editSFFrame          (void);
            const SFUInt32            *getSFFrame           (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFMinFilter       (void);
#endif
                  SFGLenum            *editSFMinFilter      (void);
            const SFGLenum            *getSFMinFilter       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFMagFilter       (void);
#endif
                  SFGLenum            *editSFMagFilter      (void);
            const SFGLenum            *getSFMagFilter       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFWrapS           (void);
#endif
                  SFGLenum            *editSFWrapS          (void);
            const SFGLenum            *getSFWrapS           (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFWrapT           (void);
#endif
                  SFGLenum            *editSFWrapT          (void);
            const SFGLenum            *getSFWrapT           (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFWrapR           (void);
#endif
                  SFGLenum            *editSFWrapR          (void);
            const SFGLenum            *getSFWrapR           (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvMode         (void);
#endif
                  SFGLenum            *editSFEnvMode        (void);
            const SFGLenum            *getSFEnvMode         (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFColor4f           *getSFEnvColor        (void);
#endif
                  SFColor4f           *editSFEnvColor       (void);
            const SFColor4f           *getSFEnvColor        (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvCombineRGB   (void);
#endif
                  SFGLenum            *editSFEnvCombineRGB  (void);
            const SFGLenum            *getSFEnvCombineRGB   (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvCombineAlpha (void);
#endif
                  SFGLenum            *editSFEnvCombineAlpha(void);
            const SFGLenum            *getSFEnvCombineAlpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFReal32            *getSFEnvScaleRGB     (void);
#endif
                  SFReal32            *editSFEnvScaleRGB    (void);
            const SFReal32            *getSFEnvScaleRGB     (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFReal32            *getSFEnvScaleAlpha   (void);
#endif
                  SFReal32            *editSFEnvScaleAlpha  (void);
            const SFReal32            *getSFEnvScaleAlpha   (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvSource0RGB   (void);
#endif
                  SFGLenum            *editSFEnvSource0RGB  (void);
            const SFGLenum            *getSFEnvSource0RGB   (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvSource1RGB   (void);
#endif
                  SFGLenum            *editSFEnvSource1RGB  (void);
            const SFGLenum            *getSFEnvSource1RGB   (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvSource2RGB   (void);
#endif
                  SFGLenum            *editSFEnvSource2RGB  (void);
            const SFGLenum            *getSFEnvSource2RGB   (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvSource0Alpha (void);
#endif
                  SFGLenum            *editSFEnvSource0Alpha(void);
            const SFGLenum            *getSFEnvSource0Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvSource1Alpha (void);
#endif
                  SFGLenum            *editSFEnvSource1Alpha(void);
            const SFGLenum            *getSFEnvSource1Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvSource2Alpha (void);
#endif
                  SFGLenum            *editSFEnvSource2Alpha(void);
            const SFGLenum            *getSFEnvSource2Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvOperand0RGB  (void);
#endif
                  SFGLenum            *editSFEnvOperand0RGB (void);
            const SFGLenum            *getSFEnvOperand0RGB  (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvOperand1RGB  (void);
#endif
                  SFGLenum            *editSFEnvOperand1RGB (void);
            const SFGLenum            *getSFEnvOperand1RGB  (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvOperand2RGB  (void);
#endif
                  SFGLenum            *editSFEnvOperand2RGB (void);
            const SFGLenum            *getSFEnvOperand2RGB  (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvOperand0Alpha (void);
#endif
                  SFGLenum            *editSFEnvOperand0Alpha(void);
            const SFGLenum            *getSFEnvOperand0Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvOperand1Alpha (void);
#endif
                  SFGLenum            *editSFEnvOperand1Alpha(void);
            const SFGLenum            *getSFEnvOperand1Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFEnvOperand2Alpha (void);
#endif
                  SFGLenum            *editSFEnvOperand2Alpha(void);
            const SFGLenum            *getSFEnvOperand2Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFGLId            (void);
#endif
                  SFGLenum            *editSFGLId           (void);
            const SFGLenum            *getSFGLId            (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFInt32             *getSFIgnoreGLForAspect (void);
#endif
                  SFInt32             *editSFIgnoreGLForAspect(void);
            const SFInt32             *getSFIgnoreGLForAspect (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFBool              *getSFPointSprite     (void);
#endif
                  SFBool              *editSFPointSprite    (void);
            const SFBool              *getSFPointSprite     (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFReal32            *getSFPriority        (void);
#endif
                  SFReal32            *editSFPriority       (void);
            const SFReal32            *getSFPriority        (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFShaderOperation (void);
#endif
                  SFGLenum            *editSFShaderOperation(void);
            const SFGLenum            *getSFShaderOperation (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFShaderInput     (void);
#endif
                  SFGLenum            *editSFShaderInput    (void);
            const SFGLenum            *getSFShaderInput     (void) const;

#ifdef OSG_1_GET_COMPAT
                  MFReal32            *getMFShaderOffsetMatrix (void);
#endif
                  MFReal32            *editMFShaderOffsetMatrix(void);
            const MFReal32            *getMFShaderOffsetMatrix (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFReal32            *getSFShaderOffsetScale (void);
#endif
                  SFReal32            *editSFShaderOffsetScale(void);
            const SFReal32            *getSFShaderOffsetScale (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFReal32            *getSFShaderOffsetBias (void);
#endif
                  SFReal32            *editSFShaderOffsetBias(void);
            const SFReal32            *getSFShaderOffsetBias (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFShaderRGBADotProduct (void);
#endif
                  SFGLenum            *editSFShaderRGBADotProduct(void);
            const SFGLenum            *getSFShaderRGBADotProduct (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFUInt8             *getSFShaderCullModes (void);
#endif
                  SFUInt8             *editSFShaderCullModes(void);
            const SFUInt8             *getSFShaderCullModes (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFVec3f             *getSFShaderConstEye  (void);
#endif
                  SFVec3f             *editSFShaderConstEye (void);
            const SFVec3f             *getSFShaderConstEye  (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFReal32            *getSFLodBias         (void);
#endif
                  SFReal32            *editSFLodBias        (void);
            const SFReal32            *getSFLodBias         (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFInt32             *getSFDirtyLeft       (void);
#endif
                  SFInt32             *editSFDirtyLeft      (void);
            const SFInt32             *getSFDirtyLeft       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFInt32             *getSFDirtyMinX       (void);
#endif
                  SFInt32             *editSFDirtyMinX      (void);
            const SFInt32             *getSFDirtyMinX       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFInt32             *getSFDirtyMaxX       (void);
#endif
                  SFInt32             *editSFDirtyMaxX      (void);
            const SFInt32             *getSFDirtyMaxX       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFInt32             *getSFDirtyMinY       (void);
#endif
                  SFInt32             *editSFDirtyMinY      (void);
            const SFInt32             *getSFDirtyMinY       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFInt32             *getSFDirtyMaxY       (void);
#endif
                  SFInt32             *editSFDirtyMaxY      (void);
            const SFInt32             *getSFDirtyMaxY       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFInt32             *getSFDirtyMinZ       (void);
#endif
                  SFInt32             *editSFDirtyMinZ      (void);
            const SFInt32             *getSFDirtyMinZ       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFInt32             *getSFDirtyMaxZ       (void);
#endif
                  SFInt32             *editSFDirtyMaxZ      (void);
            const SFInt32             *getSFDirtyMaxZ       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFReal32            *getSFAnisotropy      (void);
#endif
                  SFReal32            *editSFAnisotropy     (void);
            const SFReal32            *getSFAnisotropy      (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFColor4f           *getSFBorderColor     (void);
#endif
                  SFColor4f           *editSFBorderColor    (void);
            const SFColor4f           *getSFBorderColor     (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFCompareMode     (void);
#endif
                  SFGLenum            *editSFCompareMode    (void);
            const SFGLenum            *getSFCompareMode     (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFCompareFunc     (void);
#endif
                  SFGLenum            *editSFCompareFunc    (void);
            const SFGLenum            *getSFCompareFunc     (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFGLenum            *getSFDepthMode       (void);
#endif
                  SFGLenum            *editSFDepthMode      (void);
            const SFGLenum            *getSFDepthMode       (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFUInt32            *getSFBorderWidth     (void);
#endif
                  SFUInt32            *editSFBorderWidth    (void);
            const SFUInt32            *getSFBorderWidth     (void) const;

#ifdef OSG_1_GET_COMPAT
                  SFUInt32            *getSFNPOTMatrixScale (void);
#endif
                  SFUInt32            *editSFNPOTMatrixScale(void);
            const SFUInt32            *getSFNPOTMatrixScale (void) const;


                  ImagePtrConst getImage          (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getInternalFormat  (void);
#endif
                  GLenum              &editInternalFormat (void);
            const GLenum              &getInternalFormat  (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getExternalFormat  (void);
#endif
                  GLenum              &editExternalFormat (void);
            const GLenum              &getExternalFormat  (void) const;

#ifdef OSG_1_GET_COMPAT
                  bool                &getScale           (void);
#endif
                  bool                &editScale          (void);
            const bool                &getScale           (void) const;

#ifdef OSG_1_GET_COMPAT
                  UInt32              &getFrame           (void);
#endif
                  UInt32              &editFrame          (void);
            const UInt32              &getFrame           (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getMinFilter       (void);
#endif
                  GLenum              &editMinFilter      (void);
            const GLenum              &getMinFilter       (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getMagFilter       (void);
#endif
                  GLenum              &editMagFilter      (void);
            const GLenum              &getMagFilter       (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getWrapS           (void);
#endif
                  GLenum              &editWrapS          (void);
            const GLenum              &getWrapS           (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getWrapT           (void);
#endif
                  GLenum              &editWrapT          (void);
            const GLenum              &getWrapT           (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getWrapR           (void);
#endif
                  GLenum              &editWrapR          (void);
            const GLenum              &getWrapR           (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvMode         (void);
#endif
                  GLenum              &editEnvMode        (void);
            const GLenum              &getEnvMode         (void) const;

#ifdef OSG_1_GET_COMPAT
                  Color4f             &getEnvColor        (void);
#endif
                  Color4f             &editEnvColor       (void);
            const Color4f             &getEnvColor        (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvCombineRGB   (void);
#endif
                  GLenum              &editEnvCombineRGB  (void);
            const GLenum              &getEnvCombineRGB   (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvCombineAlpha (void);
#endif
                  GLenum              &editEnvCombineAlpha(void);
            const GLenum              &getEnvCombineAlpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  Real32              &getEnvScaleRGB     (void);
#endif
                  Real32              &editEnvScaleRGB    (void);
            const Real32              &getEnvScaleRGB     (void) const;

#ifdef OSG_1_GET_COMPAT
                  Real32              &getEnvScaleAlpha   (void);
#endif
                  Real32              &editEnvScaleAlpha  (void);
            const Real32              &getEnvScaleAlpha   (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvSource0RGB   (void);
#endif
                  GLenum              &editEnvSource0RGB  (void);
            const GLenum              &getEnvSource0RGB   (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvSource1RGB   (void);
#endif
                  GLenum              &editEnvSource1RGB  (void);
            const GLenum              &getEnvSource1RGB   (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvSource2RGB   (void);
#endif
                  GLenum              &editEnvSource2RGB  (void);
            const GLenum              &getEnvSource2RGB   (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvSource0Alpha (void);
#endif
                  GLenum              &editEnvSource0Alpha(void);
            const GLenum              &getEnvSource0Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvSource1Alpha (void);
#endif
                  GLenum              &editEnvSource1Alpha(void);
            const GLenum              &getEnvSource1Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvSource2Alpha (void);
#endif
                  GLenum              &editEnvSource2Alpha(void);
            const GLenum              &getEnvSource2Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvOperand0RGB  (void);
#endif
                  GLenum              &editEnvOperand0RGB (void);
            const GLenum              &getEnvOperand0RGB  (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvOperand1RGB  (void);
#endif
                  GLenum              &editEnvOperand1RGB (void);
            const GLenum              &getEnvOperand1RGB  (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvOperand2RGB  (void);
#endif
                  GLenum              &editEnvOperand2RGB (void);
            const GLenum              &getEnvOperand2RGB  (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvOperand0Alpha (void);
#endif
                  GLenum              &editEnvOperand0Alpha(void);
            const GLenum              &getEnvOperand0Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvOperand1Alpha (void);
#endif
                  GLenum              &editEnvOperand1Alpha(void);
            const GLenum              &getEnvOperand1Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getEnvOperand2Alpha (void);
#endif
                  GLenum              &editEnvOperand2Alpha(void);
            const GLenum              &getEnvOperand2Alpha (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getGLId            (void);
#endif
                  GLenum              &editGLId           (void);
            const GLenum              &getGLId            (void) const;

#ifdef OSG_1_GET_COMPAT
                  Int32               &getIgnoreGLForAspect (void);
#endif
                  Int32               &editIgnoreGLForAspect(void);
            const Int32               &getIgnoreGLForAspect (void) const;

#ifdef OSG_1_GET_COMPAT
                  bool                &getPointSprite     (void);
#endif
                  bool                &editPointSprite    (void);
            const bool                &getPointSprite     (void) const;

#ifdef OSG_1_GET_COMPAT
                  Real32              &getPriority        (void);
#endif
                  Real32              &editPriority       (void);
            const Real32              &getPriority        (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getShaderOperation (void);
#endif
                  GLenum              &editShaderOperation(void);
            const GLenum              &getShaderOperation (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getShaderInput     (void);
#endif
                  GLenum              &editShaderInput    (void);
            const GLenum              &getShaderInput     (void) const;

#ifdef OSG_1_GET_COMPAT
                  Real32              &getShaderOffsetMatrix (const UInt32 index);
                  MFReal32            &getShaderOffsetMatrix(void);
#endif
                  Real32              &editShaderOffsetMatrix(const UInt32 index);
            const Real32              &getShaderOffsetMatrix (const UInt32 index) const;
                  MFReal32            &editShaderOffsetMatrix(void);
            const MFReal32            &getShaderOffsetMatrix(void) const;

#ifdef OSG_1_GET_COMPAT
                  Real32              &getShaderOffsetScale (void);
#endif
                  Real32              &editShaderOffsetScale(void);
            const Real32              &getShaderOffsetScale (void) const;

#ifdef OSG_1_GET_COMPAT
                  Real32              &getShaderOffsetBias (void);
#endif
                  Real32              &editShaderOffsetBias(void);
            const Real32              &getShaderOffsetBias (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getShaderRGBADotProduct (void);
#endif
                  GLenum              &editShaderRGBADotProduct(void);
            const GLenum              &getShaderRGBADotProduct (void) const;

#ifdef OSG_1_GET_COMPAT
                  UInt8               &getShaderCullModes (void);
#endif
                  UInt8               &editShaderCullModes(void);
            const UInt8               &getShaderCullModes (void) const;

#ifdef OSG_1_GET_COMPAT
                  Vec3f               &getShaderConstEye  (void);
#endif
                  Vec3f               &editShaderConstEye (void);
            const Vec3f               &getShaderConstEye  (void) const;

#ifdef OSG_1_GET_COMPAT
                  Real32              &getLodBias         (void);
#endif
                  Real32              &editLodBias        (void);
            const Real32              &getLodBias         (void) const;

#ifdef OSG_1_GET_COMPAT
                  Int32               &getDirtyLeft       (void);
#endif
                  Int32               &editDirtyLeft      (void);
            const Int32               &getDirtyLeft       (void) const;

#ifdef OSG_1_GET_COMPAT
                  Int32               &getDirtyMinX       (void);
#endif
                  Int32               &editDirtyMinX      (void);
            const Int32               &getDirtyMinX       (void) const;

#ifdef OSG_1_GET_COMPAT
                  Int32               &getDirtyMaxX       (void);
#endif
                  Int32               &editDirtyMaxX      (void);
            const Int32               &getDirtyMaxX       (void) const;

#ifdef OSG_1_GET_COMPAT
                  Int32               &getDirtyMinY       (void);
#endif
                  Int32               &editDirtyMinY      (void);
            const Int32               &getDirtyMinY       (void) const;

#ifdef OSG_1_GET_COMPAT
                  Int32               &getDirtyMaxY       (void);
#endif
                  Int32               &editDirtyMaxY      (void);
            const Int32               &getDirtyMaxY       (void) const;

#ifdef OSG_1_GET_COMPAT
                  Int32               &getDirtyMinZ       (void);
#endif
                  Int32               &editDirtyMinZ      (void);
            const Int32               &getDirtyMinZ       (void) const;

#ifdef OSG_1_GET_COMPAT
                  Int32               &getDirtyMaxZ       (void);
#endif
                  Int32               &editDirtyMaxZ      (void);
            const Int32               &getDirtyMaxZ       (void) const;

#ifdef OSG_1_GET_COMPAT
                  Real32              &getAnisotropy      (void);
#endif
                  Real32              &editAnisotropy     (void);
            const Real32              &getAnisotropy      (void) const;

#ifdef OSG_1_GET_COMPAT
                  Color4f             &getBorderColor     (void);
#endif
                  Color4f             &editBorderColor    (void);
            const Color4f             &getBorderColor     (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getCompareMode     (void);
#endif
                  GLenum              &editCompareMode    (void);
            const GLenum              &getCompareMode     (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getCompareFunc     (void);
#endif
                  GLenum              &editCompareFunc    (void);
            const GLenum              &getCompareFunc     (void) const;

#ifdef OSG_1_GET_COMPAT
                  GLenum              &getDepthMode       (void);
#endif
                  GLenum              &editDepthMode      (void);
            const GLenum              &getDepthMode       (void) const;

#ifdef OSG_1_GET_COMPAT
                  UInt32              &getBorderWidth     (void);
#endif
                  UInt32              &editBorderWidth    (void);
            const UInt32              &getBorderWidth     (void) const;

#ifdef OSG_1_GET_COMPAT
                  UInt32              &getNPOTMatrixScale (void);
#endif
                  UInt32              &editNPOTMatrixScale(void);
            const UInt32              &getNPOTMatrixScale (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setImage          (ImagePtrConstArg value);
            void setInternalFormat (const GLenum &value);
            void setExternalFormat (const GLenum &value);
            void setScale          (const bool &value);
            void setFrame          (const UInt32 &value);
            void setMinFilter      (const GLenum &value);
            void setMagFilter      (const GLenum &value);
            void setWrapS          (const GLenum &value);
            void setWrapT          (const GLenum &value);
            void setWrapR          (const GLenum &value);
            void setEnvMode        (const GLenum &value);
            void setEnvColor       (const Color4f &value);
            void setEnvCombineRGB  (const GLenum &value);
            void setEnvCombineAlpha(const GLenum &value);
            void setEnvScaleRGB    (const Real32 &value);
            void setEnvScaleAlpha  (const Real32 &value);
            void setEnvSource0RGB  (const GLenum &value);
            void setEnvSource1RGB  (const GLenum &value);
            void setEnvSource2RGB  (const GLenum &value);
            void setEnvSource0Alpha(const GLenum &value);
            void setEnvSource1Alpha(const GLenum &value);
            void setEnvSource2Alpha(const GLenum &value);
            void setEnvOperand0RGB (const GLenum &value);
            void setEnvOperand1RGB (const GLenum &value);
            void setEnvOperand2RGB (const GLenum &value);
            void setEnvOperand0Alpha(const GLenum &value);
            void setEnvOperand1Alpha(const GLenum &value);
            void setEnvOperand2Alpha(const GLenum &value);
            void setGLId           (const GLenum &value);
            void setIgnoreGLForAspect(const Int32 &value);
            void setPointSprite    (const bool &value);
            void setPriority       (const Real32 &value);
            void setShaderOperation(const GLenum &value);
            void setShaderInput    (const GLenum &value);
            void setShaderOffsetScale(const Real32 &value);
            void setShaderOffsetBias(const Real32 &value);
            void setShaderRGBADotProduct(const GLenum &value);
            void setShaderCullModes(const UInt8 &value);
            void setShaderConstEye (const Vec3f &value);
            void setLodBias        (const Real32 &value);
            void setDirtyLeft      (const Int32 &value);
            void setDirtyMinX      (const Int32 &value);
            void setDirtyMaxX      (const Int32 &value);
            void setDirtyMinY      (const Int32 &value);
            void setDirtyMaxY      (const Int32 &value);
            void setDirtyMinZ      (const Int32 &value);
            void setDirtyMaxZ      (const Int32 &value);
            void setAnisotropy     (const Real32 &value);
            void setBorderColor    (const Color4f &value);
            void setCompareMode    (const GLenum &value);
            void setCompareFunc    (const GLenum &value);
            void setDepthMode      (const GLenum &value);
            void setBorderWidth    (const UInt32 &value);
            void setNPOTMatrixScale(const UInt32 &value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */


    void pushToShaderOffsetMatrix          (const Real32    &value   );
    void insertIntoShaderOffsetMatrix      (      UInt32     uiIndex,
                                            const Real32    &value   );
    void replaceInShaderOffsetMatrix       (      UInt32     uiIndex,
                                            const Real32    &value   );
    void replaceInShaderOffsetMatrix       (const Real32    &pOldElem,
                                            const Real32    &pNewElem);
    void removeFromShaderOffsetMatrix      (      UInt32     uiIndex );
    void removeFromShaderOffsetMatrix      (const Real32    &value   );
    void clearShaderOffsetMatrix           (      void               );


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  TextureChunkPtr create     (void);
    static  TextureChunkPtr createEmpty(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr shallowCopy(void) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static void   classDescInserter(TypeObject &oType);
    static Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFImagePtr        _sfImage;
    SFGLenum          _sfInternalFormat;
    SFGLenum          _sfExternalFormat;
    SFBool            _sfScale;
    SFUInt32          _sfFrame;
    SFGLenum          _sfMinFilter;
    SFGLenum          _sfMagFilter;
    SFGLenum          _sfWrapS;
    SFGLenum          _sfWrapT;
    SFGLenum          _sfWrapR;
    SFGLenum          _sfEnvMode;
    SFColor4f         _sfEnvColor;
    SFGLenum          _sfEnvCombineRGB;
    SFGLenum          _sfEnvCombineAlpha;
    SFReal32          _sfEnvScaleRGB;
    SFReal32          _sfEnvScaleAlpha;
    SFGLenum          _sfEnvSource0RGB;
    SFGLenum          _sfEnvSource1RGB;
    SFGLenum          _sfEnvSource2RGB;
    SFGLenum          _sfEnvSource0Alpha;
    SFGLenum          _sfEnvSource1Alpha;
    SFGLenum          _sfEnvSource2Alpha;
    SFGLenum          _sfEnvOperand0RGB;
    SFGLenum          _sfEnvOperand1RGB;
    SFGLenum          _sfEnvOperand2RGB;
    SFGLenum          _sfEnvOperand0Alpha;
    SFGLenum          _sfEnvOperand1Alpha;
    SFGLenum          _sfEnvOperand2Alpha;
    SFGLenum          _sfGLId;
    SFInt32           _sfIgnoreGLForAspect;
    SFBool            _sfPointSprite;
    SFReal32          _sfPriority;
    SFGLenum          _sfShaderOperation;
    SFGLenum          _sfShaderInput;
    MFReal32          _mfShaderOffsetMatrix;
    SFReal32          _sfShaderOffsetScale;
    SFReal32          _sfShaderOffsetBias;
    SFGLenum          _sfShaderRGBADotProduct;
    SFUInt8           _sfShaderCullModes;
    SFVec3f           _sfShaderConstEye;
    SFReal32          _sfLodBias;
    SFInt32           _sfDirtyLeft;
    SFInt32           _sfDirtyMinX;
    SFInt32           _sfDirtyMaxX;
    SFInt32           _sfDirtyMinY;
    SFInt32           _sfDirtyMaxY;
    SFInt32           _sfDirtyMinZ;
    SFInt32           _sfDirtyMaxZ;
    SFReal32          _sfAnisotropy;
    SFColor4f         _sfBorderColor;
    SFGLenum          _sfCompareMode;
    SFGLenum          _sfCompareFunc;
    SFGLenum          _sfDepthMode;
    SFUInt32          _sfBorderWidth;
    SFUInt32          _sfNPOTMatrixScale;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    TextureChunkBase(void);
    TextureChunkBase(const TextureChunkBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~TextureChunkBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const TextureChunk *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleImage           (void) const;
    EditFieldHandlePtr editHandleImage          (void);
    GetFieldHandlePtr  getHandleInternalFormat  (void) const;
    EditFieldHandlePtr editHandleInternalFormat (void);
    GetFieldHandlePtr  getHandleExternalFormat  (void) const;
    EditFieldHandlePtr editHandleExternalFormat (void);
    GetFieldHandlePtr  getHandleScale           (void) const;
    EditFieldHandlePtr editHandleScale          (void);
    GetFieldHandlePtr  getHandleFrame           (void) const;
    EditFieldHandlePtr editHandleFrame          (void);
    GetFieldHandlePtr  getHandleMinFilter       (void) const;
    EditFieldHandlePtr editHandleMinFilter      (void);
    GetFieldHandlePtr  getHandleMagFilter       (void) const;
    EditFieldHandlePtr editHandleMagFilter      (void);
    GetFieldHandlePtr  getHandleWrapS           (void) const;
    EditFieldHandlePtr editHandleWrapS          (void);
    GetFieldHandlePtr  getHandleWrapT           (void) const;
    EditFieldHandlePtr editHandleWrapT          (void);
    GetFieldHandlePtr  getHandleWrapR           (void) const;
    EditFieldHandlePtr editHandleWrapR          (void);
    GetFieldHandlePtr  getHandleEnvMode         (void) const;
    EditFieldHandlePtr editHandleEnvMode        (void);
    GetFieldHandlePtr  getHandleEnvColor        (void) const;
    EditFieldHandlePtr editHandleEnvColor       (void);
    GetFieldHandlePtr  getHandleEnvCombineRGB   (void) const;
    EditFieldHandlePtr editHandleEnvCombineRGB  (void);
    GetFieldHandlePtr  getHandleEnvCombineAlpha (void) const;
    EditFieldHandlePtr editHandleEnvCombineAlpha(void);
    GetFieldHandlePtr  getHandleEnvScaleRGB     (void) const;
    EditFieldHandlePtr editHandleEnvScaleRGB    (void);
    GetFieldHandlePtr  getHandleEnvScaleAlpha   (void) const;
    EditFieldHandlePtr editHandleEnvScaleAlpha  (void);
    GetFieldHandlePtr  getHandleEnvSource0RGB   (void) const;
    EditFieldHandlePtr editHandleEnvSource0RGB  (void);
    GetFieldHandlePtr  getHandleEnvSource1RGB   (void) const;
    EditFieldHandlePtr editHandleEnvSource1RGB  (void);
    GetFieldHandlePtr  getHandleEnvSource2RGB   (void) const;
    EditFieldHandlePtr editHandleEnvSource2RGB  (void);
    GetFieldHandlePtr  getHandleEnvSource0Alpha (void) const;
    EditFieldHandlePtr editHandleEnvSource0Alpha(void);
    GetFieldHandlePtr  getHandleEnvSource1Alpha (void) const;
    EditFieldHandlePtr editHandleEnvSource1Alpha(void);
    GetFieldHandlePtr  getHandleEnvSource2Alpha (void) const;
    EditFieldHandlePtr editHandleEnvSource2Alpha(void);
    GetFieldHandlePtr  getHandleEnvOperand0RGB  (void) const;
    EditFieldHandlePtr editHandleEnvOperand0RGB (void);
    GetFieldHandlePtr  getHandleEnvOperand1RGB  (void) const;
    EditFieldHandlePtr editHandleEnvOperand1RGB (void);
    GetFieldHandlePtr  getHandleEnvOperand2RGB  (void) const;
    EditFieldHandlePtr editHandleEnvOperand2RGB (void);
    GetFieldHandlePtr  getHandleEnvOperand0Alpha (void) const;
    EditFieldHandlePtr editHandleEnvOperand0Alpha(void);
    GetFieldHandlePtr  getHandleEnvOperand1Alpha (void) const;
    EditFieldHandlePtr editHandleEnvOperand1Alpha(void);
    GetFieldHandlePtr  getHandleEnvOperand2Alpha (void) const;
    EditFieldHandlePtr editHandleEnvOperand2Alpha(void);
    GetFieldHandlePtr  getHandleGLId            (void) const;
    EditFieldHandlePtr editHandleGLId           (void);
    GetFieldHandlePtr  getHandleIgnoreGLForAspect (void) const;
    EditFieldHandlePtr editHandleIgnoreGLForAspect(void);
    GetFieldHandlePtr  getHandlePointSprite     (void) const;
    EditFieldHandlePtr editHandlePointSprite    (void);
    GetFieldHandlePtr  getHandlePriority        (void) const;
    EditFieldHandlePtr editHandlePriority       (void);
    GetFieldHandlePtr  getHandleShaderOperation (void) const;
    EditFieldHandlePtr editHandleShaderOperation(void);
    GetFieldHandlePtr  getHandleShaderInput     (void) const;
    EditFieldHandlePtr editHandleShaderInput    (void);
    GetFieldHandlePtr  getHandleShaderOffsetMatrix (void) const;
    EditFieldHandlePtr editHandleShaderOffsetMatrix(void);
    GetFieldHandlePtr  getHandleShaderOffsetScale (void) const;
    EditFieldHandlePtr editHandleShaderOffsetScale(void);
    GetFieldHandlePtr  getHandleShaderOffsetBias (void) const;
    EditFieldHandlePtr editHandleShaderOffsetBias(void);
    GetFieldHandlePtr  getHandleShaderRGBADotProduct (void) const;
    EditFieldHandlePtr editHandleShaderRGBADotProduct(void);
    GetFieldHandlePtr  getHandleShaderCullModes (void) const;
    EditFieldHandlePtr editHandleShaderCullModes(void);
    GetFieldHandlePtr  getHandleShaderConstEye  (void) const;
    EditFieldHandlePtr editHandleShaderConstEye (void);
    GetFieldHandlePtr  getHandleLodBias         (void) const;
    EditFieldHandlePtr editHandleLodBias        (void);
    GetFieldHandlePtr  getHandleDirtyLeft       (void) const;
    EditFieldHandlePtr editHandleDirtyLeft      (void);
    GetFieldHandlePtr  getHandleDirtyMinX       (void) const;
    EditFieldHandlePtr editHandleDirtyMinX      (void);
    GetFieldHandlePtr  getHandleDirtyMaxX       (void) const;
    EditFieldHandlePtr editHandleDirtyMaxX      (void);
    GetFieldHandlePtr  getHandleDirtyMinY       (void) const;
    EditFieldHandlePtr editHandleDirtyMinY      (void);
    GetFieldHandlePtr  getHandleDirtyMaxY       (void) const;
    EditFieldHandlePtr editHandleDirtyMaxY      (void);
    GetFieldHandlePtr  getHandleDirtyMinZ       (void) const;
    EditFieldHandlePtr editHandleDirtyMinZ      (void);
    GetFieldHandlePtr  getHandleDirtyMaxZ       (void) const;
    EditFieldHandlePtr editHandleDirtyMaxZ      (void);
    GetFieldHandlePtr  getHandleAnisotropy      (void) const;
    EditFieldHandlePtr editHandleAnisotropy     (void);
    GetFieldHandlePtr  getHandleBorderColor     (void) const;
    EditFieldHandlePtr editHandleBorderColor    (void);
    GetFieldHandlePtr  getHandleCompareMode     (void) const;
    EditFieldHandlePtr editHandleCompareMode    (void);
    GetFieldHandlePtr  getHandleCompareFunc     (void) const;
    EditFieldHandlePtr editHandleCompareFunc    (void);
    GetFieldHandlePtr  getHandleDepthMode       (void) const;
    EditFieldHandlePtr editHandleDepthMode      (void);
    GetFieldHandlePtr  getHandleBorderWidth     (void) const;
    EditFieldHandlePtr editHandleBorderWidth    (void);
    GetFieldHandlePtr  getHandleNPOTMatrixScale (void) const;
    EditFieldHandlePtr editHandleNPOTMatrixScale(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      TextureChunkBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainerPtr createAspectCopy(void) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const TextureChunkBase &source);
};

typedef TextureChunkBase *TextureChunkBaseP;

OSG_END_NAMESPACE

#endif /* _OSGTEXTURECHUNKBASE_H_ */
