/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTURECHUNKFIELDS_H_
#define _OSGTEXTURECHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TextureChunk;

OSG_GEN_CONTAINERPTR(TextureChunk);

/*! \ingroup GrpSystemFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<TextureChunk *> :
    public FieldTraitsFCPtrBase<TextureChunk *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TextureChunk *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTextureChunkPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTextureChunkPtr"; }
};

template<> inline
const Char8 *FieldTraits<TextureChunk *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTextureChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureChunk *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTextureChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureChunk *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTextureChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureChunk *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTextureChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureChunk *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTextureChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureChunk *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTextureChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureChunk *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTextureChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureChunk *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTextureChunkPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<TextureChunk *,
                      RecordedRefCountPolicy  > SFRecTextureChunkPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<TextureChunk *,
                      UnrecordedRefCountPolicy> SFUnrecTextureChunkPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<TextureChunk *,
                      WeakRefCountPolicy      > SFWeakTextureChunkPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<TextureChunk *,
                      NoRefCountPolicy        > SFUncountedTextureChunkPtr;


/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<TextureChunk *,
                      RecordedRefCountPolicy  > MFRecTextureChunkPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<TextureChunk *,
                      UnrecordedRefCountPolicy> MFUnrecTextureChunkPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<TextureChunk *,
                      WeakRefCountPolicy      > MFWeakTextureChunkPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<TextureChunk *,
                      NoRefCountPolicy        > MFUncountedTextureChunkPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecTextureChunkPtr : 
    public PointerSField<TextureChunk *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecTextureChunkPtr : 
    public PointerSField<TextureChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakTextureChunkPtr :
    public PointerSField<TextureChunk *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedTextureChunkPtr :
    public PointerSField<TextureChunk *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecTextureChunkPtr :
    public PointerMField<TextureChunk *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecTextureChunkPtr :
    public PointerMField<TextureChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakTextureChunkPtr :
    public PointerMField<TextureChunk *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedTextureChunkPtr :
    public PointerMField<TextureChunk *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTURECHUNKFIELDS_H_ */
