/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGANIMMATRIXBLENDERFIELDS_H_
#define _OSGANIMMATRIXBLENDERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGDynamicsDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class AnimMatrixBlender;

OSG_GEN_CONTAINERPTR(AnimMatrixBlender);
/*! \ingroup GrpDynamicsFieldTraits
    \ingroup GrpLibOSGDynamics
 */
template <>
struct FieldTraits<AnimMatrixBlender *, nsOSG> :
    public FieldTraitsFCPtrBase<AnimMatrixBlender *, nsOSG>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<AnimMatrixBlender *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_DYNAMICS_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<AnimMatrixBlender *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAnimMatrixBlenderPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimMatrixBlender *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAnimMatrixBlenderPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimMatrixBlender *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAnimMatrixBlenderPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimMatrixBlender *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAnimMatrixBlenderPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimMatrixBlender *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAnimMatrixBlenderPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimMatrixBlender *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAnimMatrixBlenderPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimMatrixBlender *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAnimMatrixBlenderPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimMatrixBlender *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAnimMatrixBlenderPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpDynamicsFieldSFields */
typedef PointerSField<AnimMatrixBlender *,
                      RecordedRefCountPolicy, nsOSG  > SFRecAnimMatrixBlenderPtr;
/*! \ingroup GrpDynamicsFieldSFields */
typedef PointerSField<AnimMatrixBlender *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecAnimMatrixBlenderPtr;
/*! \ingroup GrpDynamicsFieldSFields */
typedef PointerSField<AnimMatrixBlender *,
                      WeakRefCountPolicy, nsOSG      > SFWeakAnimMatrixBlenderPtr;
/*! \ingroup GrpDynamicsFieldSFields */
typedef PointerSField<AnimMatrixBlender *,
                      NoRefCountPolicy, nsOSG        > SFUncountedAnimMatrixBlenderPtr;


/*! \ingroup GrpDynamicsFieldMFields */
typedef PointerMField<AnimMatrixBlender *,
                      RecordedRefCountPolicy, nsOSG  > MFRecAnimMatrixBlenderPtr;
/*! \ingroup GrpDynamicsFieldMFields */
typedef PointerMField<AnimMatrixBlender *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecAnimMatrixBlenderPtr;
/*! \ingroup GrpDynamicsFieldMFields */
typedef PointerMField<AnimMatrixBlender *,
                      WeakRefCountPolicy, nsOSG      > MFWeakAnimMatrixBlenderPtr;
/*! \ingroup GrpDynamicsFieldMFields */
typedef PointerMField<AnimMatrixBlender *,
                      NoRefCountPolicy, nsOSG        > MFUncountedAnimMatrixBlenderPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpDynamicsFieldSFields \ingroup GrpLibOSGDynamics */
struct SFRecAnimMatrixBlenderPtr : 
    public PointerSField<AnimMatrixBlender *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpDynamicsFieldSFields \ingroup GrpLibOSGDynamics */
struct SFUnrecAnimMatrixBlenderPtr : 
    public PointerSField<AnimMatrixBlender *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpDynamicsFieldSFields \ingroup GrpLibOSGDynamics */
struct SFWeakAnimMatrixBlenderPtr :
    public PointerSField<AnimMatrixBlender *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpDynamicsFieldSFields \ingroup GrpLibOSGDynamics */
struct SFUncountedAnimMatrixBlenderPtr :
    public PointerSField<AnimMatrixBlender *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpDynamicsFieldMFields \ingroup GrpLibOSGDynamics */
struct MFRecAnimMatrixBlenderPtr :
    public PointerMField<AnimMatrixBlender *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpDynamicsFieldMFields \ingroup GrpLibOSGDynamics */
struct MFUnrecAnimMatrixBlenderPtr :
    public PointerMField<AnimMatrixBlender *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpDynamicsFieldMFields \ingroup GrpLibOSGDynamics */
struct MFWeakAnimMatrixBlenderPtr :
    public PointerMField<AnimMatrixBlender *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpDynamicsFieldMFields \ingroup GrpLibOSGDynamics */
struct MFUncountedAnimMatrixBlenderPtr :
    public PointerMField<AnimMatrixBlender *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGANIMMATRIXBLENDERFIELDS_H_ */
