/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFULLSTATECHUNKFIELDS_H_
#define _OSGFULLSTATECHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class FullStateChunk;

OSG_GEN_CONTAINERPTR(FullStateChunk);
/*! \ingroup GrpSystemStateFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<FullStateChunk *, nsOSG> :
    public FieldTraitsFCPtrBase<FullStateChunk *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<FullStateChunk *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<FullStateChunk *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecFullStateChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FullStateChunk *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecFullStateChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FullStateChunk *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakFullStateChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FullStateChunk *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdFullStateChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FullStateChunk *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecFullStateChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FullStateChunk *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecFullStateChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FullStateChunk *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakFullStateChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<FullStateChunk *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdFullStateChunkPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<FullStateChunk *,
                      RecordedRefCountPolicy, nsOSG  > SFRecFullStateChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<FullStateChunk *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecFullStateChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<FullStateChunk *,
                      WeakRefCountPolicy, nsOSG      > SFWeakFullStateChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<FullStateChunk *,
                      NoRefCountPolicy, nsOSG        > SFUncountedFullStateChunkPtr;


/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<FullStateChunk *,
                      RecordedRefCountPolicy, nsOSG  > MFRecFullStateChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<FullStateChunk *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecFullStateChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<FullStateChunk *,
                      WeakRefCountPolicy, nsOSG      > MFWeakFullStateChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<FullStateChunk *,
                      NoRefCountPolicy, nsOSG        > MFUncountedFullStateChunkPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecFullStateChunkPtr : 
    public PointerSField<FullStateChunk *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecFullStateChunkPtr : 
    public PointerSField<FullStateChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakFullStateChunkPtr :
    public PointerSField<FullStateChunk *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedFullStateChunkPtr :
    public PointerSField<FullStateChunk *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecFullStateChunkPtr :
    public PointerMField<FullStateChunk *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecFullStateChunkPtr :
    public PointerMField<FullStateChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakFullStateChunkPtr :
    public PointerMField<FullStateChunk *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedFullStateChunkPtr :
    public PointerMField<FullStateChunk *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGFULLSTATECHUNKFIELDS_H_ */
