/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ShaderStorageBufferObjBaseChunk!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGConfig.h"




#include "OSGShaderStorageBufferObjBaseChunkBase.h"
#include "OSGShaderStorageBufferObjBaseChunk.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ShaderStorageBufferObjBaseChunk
    Base class for all ShaderStorageBufferObj chunk classes.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ShaderStorageBufferObjBaseChunk *, nsOSG>::_type(
    "ShaderStorageBufferObjBaseChunkPtr", 
    "StateChunkPtr", 
    ShaderStorageBufferObjBaseChunk::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ShaderStorageBufferObjBaseChunk *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ShaderStorageBufferObjBaseChunk *,
                           nsOSG)

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ShaderStorageBufferObjBaseChunk *,
                           nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ShaderStorageBufferObjBaseChunkBase::classDescInserter(TypeObject &oType)
{
}


ShaderStorageBufferObjBaseChunkBase::TypeObject ShaderStorageBufferObjBaseChunkBase::_type(
    ShaderStorageBufferObjBaseChunkBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    reinterpret_cast<InitContainerF>(&ShaderStorageBufferObjBaseChunk::initMethod),
    reinterpret_cast<ExitContainerF>(&ShaderStorageBufferObjBaseChunk::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(
        reinterpret_cast<void *>(&ShaderStorageBufferObjBaseChunk::classDescInserter)),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"ShaderStorageBufferObjBaseChunk\"\n"
    "   parent=\"StateChunk\"\n"
    "   library=\"System\"\n"
    "   pointerfieldtypes=\"both\"\n"
    "   structure=\"abstract\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   decoratable=\"false\"\n"
    "   useLocalIncludes=\"false\"\n"
    "   docGroupBase=\"GrpSystemState\"\n"
    "   >\n"
    "  \n"
    "  Base class for all ShaderStorageBufferObj chunk classes.\n"
    "</FieldContainer>\n",
    "Base class for all ShaderStorageBufferObj chunk classes.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ShaderStorageBufferObjBaseChunkBase::getType(void)
{
    return _type;
}

const FieldContainerType &ShaderStorageBufferObjBaseChunkBase::getType(void) const
{
    return _type;
}

UInt32 ShaderStorageBufferObjBaseChunkBase::getContainerSize(void) const
{
    return sizeof(ShaderStorageBufferObjBaseChunk);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT ShaderStorageBufferObjBaseChunkBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ShaderStorageBufferObjBaseChunkBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void ShaderStorageBufferObjBaseChunkBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}




/*------------------------- constructors ----------------------------------*/

ShaderStorageBufferObjBaseChunkBase::ShaderStorageBufferObjBaseChunkBase(void) :
    Inherited()
{
}

ShaderStorageBufferObjBaseChunkBase::ShaderStorageBufferObjBaseChunkBase(const ShaderStorageBufferObjBaseChunkBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ShaderStorageBufferObjBaseChunkBase::~ShaderStorageBufferObjBaseChunkBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void ShaderStorageBufferObjBaseChunkBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ShaderStorageBufferObjBaseChunk *pThis = static_cast<ShaderStorageBufferObjBaseChunk *>(this);

    pThis->execSync(static_cast<ShaderStorageBufferObjBaseChunk *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void ShaderStorageBufferObjBaseChunkBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
