/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSIMPLESTATISTICSFOREGROUNDFIELDS_H_
#define _OSGSIMPLESTATISTICSFOREGROUNDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGUtilDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGFieldContainerPtrSField.h"
#include "OSGFieldContainerPtrMField.h"


OSG_BEGIN_NAMESPACE

class SimpleStatisticsForeground;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! SimpleStatisticsForegroundPtr

OSG_GEN_CONTAINERPTR(SimpleStatisticsForeground);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpUtilFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<SimpleStatisticsForegroundPtr> :
    public FieldTraitsFCPtrBase<SimpleStatisticsForegroundPtr>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SimpleStatisticsForegroundPtr>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_UTIL_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSimpleStatisticsForegroundPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSimpleStatisticsForegroundPtr"; }
};

template<> inline
const Char8 *FieldTraits<SimpleStatisticsForegroundPtr, 0>::getSName<RecordedRefCounts>(void)
{
    return "SFRecSimpleStatisticsForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleStatisticsForegroundPtr, 0>::getSName<UnrecordedRefCounts>(void)
{
    return "SFUnrecSimpleStatisticsForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleStatisticsForegroundPtr, 0>::getSName<WeakRefCounts>(void)
{
    return "SFWeakSimpleStatisticsForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleStatisticsForegroundPtr, 0>::getSName<NoRefCounts>(void)
{
    return "SFUnrefdSimpleStatisticsForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleStatisticsForegroundPtr, 0>::getMName<RecordedRefCounts>(void)
{
    return "MFRecSimpleStatisticsForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleStatisticsForegroundPtr, 0>::getMName<UnrecordedRefCounts>(void)
{
    return "MFUnrecSimpleStatisticsForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleStatisticsForegroundPtr, 0>::getMName<WeakRefCounts>(void)
{
    return "MFWeakSimpleStatisticsForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleStatisticsForegroundPtr, 0>::getMName<NoRefCounts>(void)
{
    return "MFUnrefdSimpleStatisticsForegroundPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<SimpleStatisticsForegroundPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpUtilFieldSingle */

typedef FieldContainerPtrSField<SimpleStatisticsForegroundPtr,
                                RecordedRefCounts  > SFRecSimpleStatisticsForegroundPtr;
typedef FieldContainerPtrSField<SimpleStatisticsForegroundPtr,
                                UnrecordedRefCounts> SFUnrecSimpleStatisticsForegroundPtr;
typedef FieldContainerPtrSField<SimpleStatisticsForegroundPtr,
                                WeakRefCounts      > SFWeakSimpleStatisticsForegroundPtr;
typedef FieldContainerPtrSField<SimpleStatisticsForegroundPtr,
                                NoRefCounts        > SFUncountedSimpleStatisticsForegroundPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpUtilFieldMulti */

typedef FieldContainerPtrMField<SimpleStatisticsForegroundPtr,
                                RecordedRefCounts  > MFRecSimpleStatisticsForegroundPtr;
typedef FieldContainerPtrMField<SimpleStatisticsForegroundPtr,
                                UnrecordedRefCounts> MFUnrecSimpleStatisticsForegroundPtr;
typedef FieldContainerPtrMField<SimpleStatisticsForegroundPtr,
                                WeakRefCounts      > MFWeakSimpleStatisticsForegroundPtr;
typedef FieldContainerPtrMField<SimpleStatisticsForegroundPtr,
                                NoRefCounts        > MFUncountedSimpleStatisticsForegroundPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGSIMPLESTATISTICSFOREGROUNDFIELDS_H_ */
