
MESSAGE(STATUS "Prepare OSGComputeBase")

GET_FILENAME_COMPONENT(_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake")
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake/cuda")

FIND_PACKAGE(CUDA QUIET)

INCLUDE(ConfigurePackages.OSGContribComputeBase)

IF(NOT OSG_BUILD_DEPENDEND)
  OSG_CONFIGURE_NVSDKCOMMON()
  OSG_CONFIGURE_NVOCLUTILS()
  OSG_CONFIGURE_CUDACOMMON()
  OSG_CONFIGURE_CUDAUTIL()
  OSG_CONFIGURE_CUDPP()
  OSG_CONFIGURE_CUDAPARTSDK()
ENDIF(NOT OSG_BUILD_DEPENDEND)

MESSAGE(STATUS "NV Status: NV:${OSG_WITH_NVSDKCOMMON}")
MESSAGE(STATUS "Cuda Status: CC:${OSG_WITH_CUDACOMMON} CU:${OSG_WITH_CUDAUTIL} CP:${OSG_WITH_CUDPP}")
MESSAGE(STATUS "OCL Status : NV:${OSG_WITH_NVOCLUTILS}")

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_NVSDKCOMMON 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_NVOCLUTILS 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDACOMMON 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDAUTIL 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDPP 1")

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/FindOpenCL.cmake"
        DESTINATION share/OpenSG/cmake)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/ConfigurePackages.OSGContribComputeBase.cmake"
        DESTINATION share/OpenSG/cmake)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/OSGContribComputeBase.SetupHelper.cmake"
        DESTINATION share/OpenSG/cmake)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/cuda/FindCUDA.cmake"
        DESTINATION share/OpenSG/cmake)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/cuda/FindCUDA/make2cmake.cmake"
        DESTINATION share/OpenSG/cmake/FindCUDA)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/cuda/FindCUDA/parse_cubin.cmake"
        DESTINATION share/OpenSG/cmake/FindCUDA)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/cuda/FindCUDA/run_nvcc.cmake"
        DESTINATION share/OpenSG/cmake/FindCUDA)
