
MESSAGE(STATUS "Prepare OSGComputeBase")

GET_FILENAME_COMPONENT(_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake")

IF(CUDA_TOOLKIT_ROOT_DIR)
  OSG_ADD_OPT(CUDA_TOOLKIT_ROOT_DIR)
ENDIF(CUDA_TOOLKIT_ROOT_DIR)

IF(CUDA_NVCC_FLAGS)
  OSG_ADD_OPT(CUDA_NVCC_FLAGS)
ENDIF(CUDA_NVCC_FLAGS)

IF(CUDA_VERBOSE_BUILD)
  OSG_ADD_OPT(CUDA_VERBOSE_BUILD)
ENDIF(CUDA_VERBOSE_BUILD)

FIND_PACKAGE(CUDA QUIET)

INCLUDE(CudaHelper)

OSG_SETUP_CUDA_FLAGS()

INCLUDE(ConfigurePackages.OSGContribComputeBase)

OSG_CONFIGURE_NVSDKCOMMON()
#OSG_CONFIGURE_NVOCLUTILS()
OSG_CONFIGURE_CUDACOMMON()
#OSG_CONFIGURE_CUDAUTIL()
OSG_CONFIGURE_CUDAPARTSDK()

MESSAGE(STATUS "NV Status: NV:${OSG_WITH_NVSDKCOMMON}")
MESSAGE(STATUS "Cuda Status: CC:${OSG_WITH_CUDACOMMON} CU:${OSG_WITH_CUDAUTIL} CP:${OSG_WITH_CUDPP}")
MESSAGE(STATUS "OCL Status : NV:${OSG_WITH_NVOCLUTILS}")

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_NVSDKCOMMON 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_NVOCLUTILS 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDACOMMON 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDAUTIL 1")
LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_CUDPP 1")

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/FindOpenCL.cmake"
        DESTINATION share/OpenSG/cmake
        COMPONENT development_configuration)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/ConfigurePackages.OSGContribComputeBase.cmake"
        DESTINATION share/OpenSG/cmake
        COMPONENT development_configuration)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/OSGContribComputeBase.SetupHelper.cmake"
        DESTINATION share/OpenSG/cmake
        COMPONENT development_configuration)

