
MACRO(OSG_CONFIGURE_ZLIB)

  IF(NOT OSG_USE_OSGSUPPORT_LIBS)

    OSG_FIND_PACKAGE(ZLIB)

  ELSE(NOT OSG_USE_OSGSUPPORT_LIBS)

	IF(EXISTS ${OSG_SUPPORT_ROOT}/include/zlib.h)
	  SET(ZLIB_INCLUDE_DIR ${OSG_SUPPORT_ROOT}/include CACHE PATH "" FORCE)
	ENDIF()

	IF(OSG_USE_STATIC_SUPPORT_LIBS)
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgzlib.lib)
        SET(ZLIB_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/libosgzlib.lib)
	  ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgzlibD.lib)
        SET(ZLIB_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/libosgzlibD.lib)
	  ENDIF()
	ELSE()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgzlib.lib)
        SET(ZLIB_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/osgzlib.lib)
	  ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgzlibD.lib)
        SET(ZLIB_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/osgzlibD.lib)
	  ENDIF()
	ENDIF()

    OSG_ADD_LIB_TARGET(OSG_ZLIB_TARGETS ZLIB_LIBRARY)
	SET(ZLIB_LIBRARIES ${OSG_ZLIB_TARGETS} CACHE STRING "" FORCE)

	IF(ZLIB_INCLUDE_DIR)
	  IF(ZLIB_LIBRARY_DEBUG OR ZLIB_LIBRARY_RELEASE)
	    SET(ZLIB_FOUND TRUE)
	  ENDIF()
	ENDIF()

  ENDIF(NOT OSG_USE_OSGSUPPORT_LIBS)

ENDMACRO(OSG_CONFIGURE_ZLIB)

MACRO(OSG_CONFIGURE_GLUT)

  IF(NOT OSG_USE_OSGSUPPORT_LIBS)

    OSG_FIND_PACKAGE(GLUT)

    IF(GLUT_FOUND)
      OSG_SET(OSG_GLUT_INC_DIR ${GLUT_INCLUDE_DIR})
      OSG_SET(OSG_GLUT_LIBS ${GLUT_LIBRARIES})
    ELSE(GLUT_FOUND)
      OSG_SET(OSG_GLUT_INC_DIR "")
      OSG_SET(OSG_GLUT_LIBS "")
    ENDIF(GLUT_FOUND)

  ELSE(NOT OSG_USE_OSGSUPPORT_LIBS)

	IF(EXISTS ${OSG_SUPPORT_ROOT}/include/GL/glut.h)
	  SET(GLUT_INCLUDE_DIR ${OSG_SUPPORT_ROOT}/include CACHE PATH "" FORCE)
	ENDIF()

	IF(OSG_USE_STATIC_SUPPORT_LIBS)
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgfreeglut.lib)
        SET(GLUT_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/libosgfreeglut.lib)
	  ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgfreeglutD.lib)
        SET(GLUT_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/libosgfreeglutD.lib)
	  ENDIF()
	ELSE()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgfreeglut.lib)
        SET(GLUT_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/osgfreeglut.lib)
	  ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgfreeglutD.lib)
        SET(GLUT_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/osgfreeglutD.lib)
	  ENDIF()
	ENDIF()

    OSG_ADD_LIB_TARGET(OSG_GLUT_TARGETS GLUT_LIBRARY)
	SET(GLUT_LIBRARIES ${OSG_GLUT_TARGETS} CACHE STRING "" FORCE)

	IF(GLUT_INCLUDE_DIR)
	  IF(GLUT_LIBRARY_DEBUG OR GLUT_LIBRARY_RELEASE)
	    SET(GLUT_FOUND TRUE)
	  ENDIF()
	ENDIF()

  ENDIF(NOT OSG_USE_OSGSUPPORT_LIBS)

ENDMACRO(OSG_CONFIGURE_GLUT)

MACRO(OSG_CONFIGURE_PNG)

  IF(NOT OSG_USE_OSGSUPPORT_LIBS)
    OSG_FIND_PACKAGE(PNG)
  ELSE(NOT OSG_USE_OSGSUPPORT_LIBS)

	IF(EXISTS ${OSG_SUPPORT_ROOT}/include/png.h)
	  SET(PNG_PNG_INCLUDE_DIR ${OSG_SUPPORT_ROOT}/include CACHE PATH "" FORCE)
	ENDIF()

	IF(OSG_USE_STATIC_SUPPORT_LIBS)
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgpng.lib)
        SET(PNG_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/libosgpng.lib)
	  ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgpngD.lib)
        SET(PNG_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/libosgpngD.lib)
	  ENDIF()
	ELSE()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgpng.lib)
        SET(PNG_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/osgpng.lib)
	  ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgpngD.lib)
        SET(PNG_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/osgpngD.lib)
	  ENDIF()
	ENDIF()

    OSG_ADD_LIB_TARGET(OSG_PNG_TARGETS PNG_LIBRARY)
	SET(PNG_LIBRARIES ${OSG_PNG_TARGETS} CACHE STRING "" FORCE)

	IF(PNG_PNG_INCLUDE_DIR)
	  IF(PNG_LIBRARY_DEBUG OR PNG_LIBRARY_RELEASE)
	    SET(PNG_FOUND TRUE)
	  ENDIF()
	ENDIF()

  ENDIF(NOT OSG_USE_OSGSUPPORT_LIBS)

ENDMACRO(OSG_CONFIGURE_PNG)

MACRO(OSG_CONFIGURE_TIFF)

  IF(NOT OSG_USE_OSGSUPPORT_LIBS)
    OSG_FIND_PACKAGE(TIFF)
  ELSE(NOT OSG_USE_OSGSUPPORT_LIBS)

	IF(EXISTS ${OSG_SUPPORT_ROOT}/include/tiff.h)
	  SET(TIFF_INCLUDE_DIR ${OSG_SUPPORT_ROOT}/include CACHE PATH "" FORCE)
	ENDIF()

	IF(OSG_USE_STATIC_SUPPORT_LIBS)
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgtiff.lib)
        SET(TIFF_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/libosgtiff.lib)
	  ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgtiffD.lib)
        SET(TIFF_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/libosgtiffD.lib)
	  ENDIF()
	ELSE()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgtiff.lib)
        SET(TIFF_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/osgtiff.lib)
	  ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgtiffD.lib)
        SET(TIFF_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/osgtiffD.lib)
	  ENDIF()
	ENDIF()

    OSG_ADD_LIB_TARGET(OSG_TIFF_TARGETS TIFF_LIBRARY)
	SET(TIFF_LIBRARIES ${OSG_TIFF_TARGETS} CACHE STRING "" FORCE)

	IF(TIFF_INCLUDE_DIR)
	  IF(TIFF_LIBRARY_DEBUG OR TIFF_LIBRARY_RELEASE)
	    SET(TIFF_FOUND TRUE)
	  ENDIF()
	ENDIF()

  ENDIF(NOT OSG_USE_OSGSUPPORT_LIBS)

ENDMACRO(OSG_CONFIGURE_TIFF)

MACRO(OSG_CONFIGURE_JPEG)

  IF(NOT OSG_USE_OSGSUPPORT_LIBS)
    OSG_FIND_PACKAGE(JPEG)
  ELSE(NOT OSG_USE_OSGSUPPORT_LIBS)

	IF(EXISTS ${OSG_SUPPORT_ROOT}/include/jpeglib.h)
	  SET(JPEG_INCLUDE_DIR ${OSG_SUPPORT_ROOT}/include CACHE PATH "" FORCE)
	ENDIF()

    IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgjpg.lib)
      SET(JPEG_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/libosgjpg.lib)
    ENDIF()
    IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgjpgD.lib)
      SET(JPEG_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/libosgjpgD.lib)
	ENDIF()

    OSG_ADD_LIB_TARGET(OSG_JPEG_TARGETS JPEG_LIBRARY)
	SET(JPEG_LIBRARIES ${OSG_JPEG_TARGETS} CACHE STRING "" FORCE)

	IF(JPEG_INCLUDE_DIR)
	  IF(JPEG_LIBRARY_DEBUG OR JPEG_LIBRARY_RELEASE)
	    SET(JPEG_FOUND TRUE)
	  ENDIF()
	ENDIF()

  ENDIF(NOT OSG_USE_OSGSUPPORT_LIBS)

ENDMACRO(OSG_CONFIGURE_JPEG)

