
####################
# WARNING WARNING
#
# HIGHLY IN PROGRESS
####################

MACRO(OSG_INIT)

  SET(BUILD_SHARED_LIBS "Set to OFF to build static libraries" ON)

  MESSAGE(STATUS "ARGS: ${ARGC} | ${ARGV} ")

  SET(_OSG_COMPONENTS ${ARGV})

  #############
  #### OpenSG

  FIND_PACKAGE(OpenSG REQUIRED COMPONENTS ${_OSG_COMPONENTS})

  IF(OpenSG_DIR)
    IF(NOT OSG_COMPILER_DEFAULTS)
      INCLUDE(SetupCompiler)
      SET(OSG_COMPILER_DEFAULTS 1 CACHE INTERNAL "Defaults written" FORCE ) #INTERNAL
    ENDIF(NOT OSG_COMPILER_DEFAULTS)

    INCLUDE(UpdateCompiler)

    INCLUDE(BuildFunctions)
    INCLUDE(ConfigurePackages)

    INCLUDE_DIRECTORIES(${OpenSG_INCLUDE_DIRS})

  ENDIF(OpenSG_DIR)

  #############
  #### Support
  #############

  IF(UNIX)
    FIND_LIBRARY(OSG_THREAD_LIB NAMES pthread)
    FIND_LIBRARY(OSG_DL_LIB     NAMES dl)

    OSG_ADD_OPT(OSG_THREAD_LIB)
    OSG_ADD_OPT(OSG_DL_LIB)
  ENDIF(UNIX)

  #############
  #### OpenGL
  #############

  FIND_PACKAGE(OpenGL REQUIRED)
  FIND_PACKAGE(GLU REQUIRED)

  OSG_ADD_OPT(OPENGL_gl_LIBRARY)
  OSG_ADD_OPT(OPENGL_glu_LIBRARY)

  #############
  #### GLUT
  #############

  IF(NOT APPLE)
    OSG_CONFIGURE_GLUT()

    IF(GLUT_FOUND)
      OSG_SET(OSG_WITH_GLUT 1)
      OSG_SET(OSG_GLUT_INC_DIR ${GLUT_INCLUDE_DIR})
      OSG_SET(OSG_GLUT_LIBS ${GLUT_LIBRARIES})
    ELSE(GLUT_FOUND)
      OSG_SET(OSG_WITH_GLUT 0)
      OSG_SET(OSG_GLUT_INC_DIR "")
      OSG_SET(OSG_GLUT_LIBS "")
    ENDIF(GLUT_FOUND)
        
  ENDIF(NOT APPLE)

  ##########
  #### boost
  ##########

  OSG_CONFIGURE_BOOST()

  CHECK_BUILD_DIR()

  SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
  SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
  SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

ENDMACRO(OSG_INIT)

MACRO(OSG_COLLECT_LIBS)

# when adding passes, make sure to add a corresponding pass directory variable
# OSG_PASSDIR_${PASSNAME} - this variable may not be empty!
SET(OSG_CMAKE_PASSES "OSGCOLLECT" "OSGSETUP")

SET(OSG_PASSDIR_OSGCOLLECT "Collect")
SET(OSG_PASSDIR_OSGSETUP   "Build")

###############
# Clean
###############

FILE(GLOB OSG_OLD_BUILD_FILES  "${CMAKE_BINARY_DIR}/*.cmake")

IF(OSG_OLD_BUILD_FILES)
    FILE(REMOVE ${OSG_OLD_BUILD_FILES})
ENDIF(OSG_OLD_BUILD_FILES)

FOREACH(_OSG_COMPONENT ${_OSG_COMPONENTS})

  IF(${_OSG_COMPONENT} STREQUAL OSGBase)
    SET_TARGET_PROPERTIES(${_OSG_COMPONENT} PROPERTIES
                          IMPORTED_LINK_INTERFACE_LIBRARIES "${OSG_THREAD_LIB};${OSG_DL_LIB}")
  ELSEIF(${_OSG_COMPONENT} STREQUAL OSGSystem)
    SET_TARGET_PROPERTIES(${_OSG_COMPONENT} PROPERTIES
                          IMPORTED_LINK_INTERFACE_LIBRARIES "${OPENGL_gl_LIBRARY}")
  ELSEIF(${_OSG_COMPONENT} STREQUAL OSGWindow)
    SET_TARGET_PROPERTIES(${_OSG_COMPONENT} PROPERTIES
                          IMPORTED_LINK_INTERFACE_LIBRARIES "OSGBase;OSGSystem")
  ELSEIF(${_OSG_COMPONENT} STREQUAL OSGWindowGLUT)
    SET_TARGET_PROPERTIES(${_OSG_COMPONENT} PROPERTIES
                          IMPORTED_LINK_INTERFACE_LIBRARIES "OSGWindow;${OSG_GLUT_LIBS}")
  ENDIF()

  MESSAGE(STATUS "FAKE : ${CMAKE_BINARY_DIR}/${_OSG_COMPONENT}.cmake")
  FILE(WRITE ${CMAKE_BINARY_DIR}/${_OSG_COMPONENT}.cmake "#dummy")

ENDFOREACH(_OSG_COMPONENT ${_OSG_COMPONENTS})

###############
# Tests
###############

# optional pass for test programs
LIST(APPEND OSG_CMAKE_PASSES "OSGSETUPTEST")
SET(OSG_PASSDIR_OSGSETUPTEST "Test")

OSG_OPTION(OSG_ENABLE_FCD2CODE "" ON)
OSG_OPTION(OSG_FCD2CODE_WRITE_CLASS "" OFF)

IF(NOT WIN32 AND NOT CMAKE_BUILD_TYPE)
  SET(CMAKE_BUILD_TYPE Debug CACHE STRING
      "Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel."
      FORCE)
ENDIF(NOT WIN32 AND NOT CMAKE_BUILD_TYPE)

###############
# Passes
###############

# Find files describing libraries to build, but make sure base
# and system are processed first
FILE(GLOB_RECURSE OSG_LIBRARY_CONFIG_FILES RELATIVE "${CMAKE_SOURCE_DIR}"
     "./*CMakeLists.Lib.*.txt")

# run build passes
FOREACH(PASS ${OSG_CMAKE_PASSES})
    SET(OSG_CMAKE_PASS ${PASS})

    MESSAGE(STATUS "\nPASS : ${OSG_CMAKE_PASS} in ${OSG_PASSDIR_${PASS}}\n")

    FOREACH(LIBCONFIGFILE ${OSG_LIBRARY_CONFIG_FILES})
        GET_FILENAME_COMPONENT(LIBCONFIGDIR "${LIBCONFIGFILE}" PATH)
        GET_FILENAME_COMPONENT(LIBFILENAME  "${LIBCONFIGFILE}" NAME)
        STRING(REPLACE "CMakeLists.Lib." "" LIBFILENAME "${LIBFILENAME}")
        STRING(REPLACE ".txt"            "" LIBFILENAME "${LIBFILENAME}")

        ADD_SUBDIRECTORY("${LIBCONFIGDIR}" "${OSG_PASSDIR_${PASS}}/${LIBFILENAME}")

    ENDFOREACH(LIBCONFIGFILE)
   
ENDFOREACH()

ENDMACRO(OSG_COLLECT_LIBS)
