# - Find OpenNurbs
# Find the native OpenNurbs includes and library
# This module defines
#  OpenNurbs_INCLUDE_DIR, where to find opennurbs.h, etc.
#  OPENNURBS_LIBRARIES, the libraries needed to use OpenNurbs.
#  OPENNURBS_FOUND, If false, do not try to use OpenNurbs.
# also defined, but not for general use are
#  OPENNURBS_LIBRARY, where to find the OpenNurbs library.

FIND_PATH(OPENNURBS_INCLUDE_DIR opennurbs/opennurbs.h)

SET(OPENNURBS_NAMES_RELEASE ${OPENNURBS_NAMES_RELEASE} opennurbs)
FIND_LIBRARY(OPENNURBS_LIBRARY_RELEASE NAMES ${OPENNURBS_NAMES_RELEASE} )

SET(OPENNURBS_NAMES_DEBUG ${OPENNURBS_NAMES_DEBUG} opennurbsd)
FIND_LIBRARY(OPENNURBS_LIBRARY_DEBUG NAMES ${OPENNURBS_NAMES_DEBUG} )

IF(OPENNURBS_LIBRARY_DEBUG)
  SET(OPENNURBS_LIBRARIES_FOUND TRUE)
  MARK_AS_ADVANCED(OPENNURBS_LIBRARY_DEBUG)
ENDIF(OPENNURBS_LIBRARY_DEBUG)

IF(OPENNURBS_LIBRARY_RELEASE)
  SET(OPENNURBS_LIBRARIES_FOUND TRUE)
  MARK_AS_ADVANCED(OPENNURBS_LIBRARY_RELEASE)
ENDIF(OPENNURBS_LIBRARY_RELEASE)

# handle the QUIETLY and REQUIRED arguments and set OPENNURBS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENNURBS DEFAULT_MSG 
                                  OPENNURBS_LIBRARIES_FOUND OPENNURBS_INCLUDE_DIR)

#IF(OPENNURBS_FOUND)
#  SET(OPENNURBS_LIBRARIES ${OPENNURBS_LIBRARY})
#ENDIF(OPENNURBS_FOUND)

# Deprecated declarations.
#SET (NATIVE_OPENNURBS_INCLUDE_PATH ${OPENNURBS_INCLUDE_DIR} )
#IF(OPENNURBS_LIBRARY)
#  GET_FILENAME_COMPONENT (NATIVE_OPENNURBS_LIB_PATH ${OPENNURBS_LIBRARY} PATH)
#ENDIF(OPENNURBS_LIBRARY)

MARK_AS_ADVANCED(OPENNURBS_LIBRARIES_FOUND OPENNURBS_INCLUDE_DIR )
