# - Find LibMini
# Find the native LibMini includes and library
# This module defines
#  OSG_LIBMINI_INCLUDE_DIR, where to find mini/mini.h, etc.
#  OSG_LIBMINI_LIBRARIES, the libraries needed to use LibMini.
#  OSG_LIBMINI_FOUND, If false, do not try to use LibMini.
# also defined, but not for general use are
#  OSG_LIBMINI_LIBRARY, where to find the LibMini library.

FIND_PATH(OSG_LIBMINI_INCLUDE_DIR mini/mini.h)

SET(OSG_LIBMINI_NAMES_RELEASE ${OSG_LIBMINI_NAMES_RELEASE} libmini)
FIND_LIBRARY(OSG_LIBMINI_LIBRARY_RELEASE NAMES ${OSG_LIBMINI_NAMES_RELEASE} )

SET(OSG_LIBMINI_NAMES_DEBUG ${OSG_LIBMINI_NAMES_DEBUG} libminid)
FIND_LIBRARY(OSG_LIBMINI_LIBRARY_DEBUG NAMES ${OSG_LIBMINI_NAMES_DEBUG} )

IF(OSG_LIBMINI_LIBRARY_DEBUG)
  SET(OSG_LIBMINI_LIBRARIES_FOUND TRUE)
  MARK_AS_ADVANCED(OSG_LIBMINI_LIBRARY_DEBUG)
ENDIF(OSG_LIBMINI_LIBRARY_DEBUG)

IF(OSG_LIBMINI_LIBRARY_RELEASE)
  SET(OSG_LIBMINI_LIBRARIES_FOUND TRUE)
  MARK_AS_ADVANCED(OSG_LIBMINI_LIBRARY_RELEASE)
ENDIF(OSG_LIBMINI_LIBRARY_RELEASE)

# handle the QUIETLY and REQUIRED arguments and set OSG_LIBMINI_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSG_LIBMINI DEFAULT_MSG 
                                  OSG_LIBMINI_LIBRARIES_FOUND OSG_LIBMINI_INCLUDE_DIR)

#IF(OSG_LIBMINI_FOUND)
#  SET(OSG_LIBMINI_LIBRARIES ${OSG_LIBMINI_LIBRARY})
#ENDIF(OSG_LIBMINI_FOUND)

# Deprecated declarations.
#SET (NATIVE_OSG_LIBMINI_INCLUDE_PATH ${OSG_LIBMINI_INCLUDE_DIR} )
#IF(OSG_LIBMINI_LIBRARY)
#  GET_FILENAME_COMPONENT (NATIVE_OSG_LIBMINI_LIB_PATH ${OSG_LIBMINI_LIBRARY} PATH)
#ENDIF(OSG_LIBMINI_LIBRARY)

MARK_AS_ADVANCED(OSG_LIBMINI_LIBRARIES_FOUND OSG_LIBMINI_INCLUDE_DIR )
