# - Find AntTweakBar
# Find the native AntTweakBar includes and library
# This module defines
#  ANTTWEAKBAR_INCLUDE_DIR, where to find AntTweakBar/include/AntTweakBar.h.
#  ANTTWEAKBAR_LIBRARIES, the libraries needed to use AntTweakBar.
#  ANTTWEAKBAR_FOUND, If false, do not try to use AntTweakBar.
# also defined, but not for general use are
#  ANTTWEAKBAR_LIBRARY, where to find the AntTweakBar library.

FIND_PATH(ANTTWEAKBAR_INCLUDE_DIR AntTweakBar/include/AntTweakBar.h)

SET(ANTTWEAKBAR_NAME AntTweakBar)
IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(ANTTWEAKBAR_NAME AntTweakBar64)
ENDIF()

SET(ANTTWEAKBAR_NAMES_RELEASE ${ANTTWEAKBAR_NAMES_RELEASE} ${ANTTWEAKBAR_NAME})
FIND_LIBRARY(ANTTWEAKBAR_LIBRARY_RELEASE NAMES ${ANTTWEAKBAR_NAMES_RELEASE} )

SET(ANTTWEAKBAR_NAMES_DEBUG ${ANTTWEAKBAR_NAMES_DEBUG} ${ANTTWEAKBAR_NAME})
FIND_LIBRARY(ANTTWEAKBAR_LIBRARY_DEBUG NAMES ${ANTTWEAKBAR_NAMES_DEBUG} )

IF(ANTTWEAKBAR_LIBRARY_DEBUG)
  SET(ANTTWEAKBAR_LIBRARIES_FOUND TRUE)
  MARK_AS_ADVANCED(ANTTWEAKBAR_LIBRARY_DEBUG)
ENDIF(ANTTWEAKBAR_LIBRARY_DEBUG)

IF(ANTTWEAKBAR_LIBRARY_RELEASE)
  SET(ANTTWEAKBAR_LIBRARIES_FOUND TRUE)
  MARK_AS_ADVANCED(ANTTWEAKBAR_LIBRARY_RELEASE)
ENDIF(ANTTWEAKBAR_LIBRARY_RELEASE)

# handle the QUIETLY and REQUIRED arguments and set ANTTWEAKBAR_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ANTTWEAKBAR DEFAULT_MSG 
                                  ANTTWEAKBAR_LIBRARIES_FOUND ANTTWEAKBAR_INCLUDE_DIR)

#IF(ANTTWEAKBAR_FOUND)
#  SET(ANTTWEAKBAR_LIBRARIES ${ANTTWEAKBAR_LIBRARY})
#ENDIF(ANTTWEAKBAR_FOUND)

# Deprecated declarations.
#SET (NATIVE_ANTTWEAKBAR_INCLUDE_PATH ${ANTTWEAKBAR_INCLUDE_DIR} )
#IF(ANTTWEAKBAR_LIBRARY)
#  GET_FILENAME_COMPONENT (NATIVE_ANTTWEAKBAR_LIB_PATH ${ANTTWEAKBAR_LIBRARY} PATH)
#ENDIF(ANTTWEAKBAR_LIBRARY)

MARK_AS_ADVANCED(ANTTWEAKBAR_LIBRARIES_FOUND ANTTWEAKBAR_INCLUDE_DIR )
