
IF(NOT WIN32)
  IF(OSG_BUILD_DEPENDEND)
    # Hide it from further manipulation
    SET(OSG_BUILD_DEPENDEND ${OSG_BUILD_DEPENDEND} CACHE INTERNAL "")
  ENDIF(OSG_BUILD_DEPENDEND)
ENDIF(NOT WIN32)

MACRO(OSG_COMMON_OPTIONS)

  SET(BUILD_SHARED_LIBS ON CACHE INTERNAL 
                        "Set to OFF to build static libraries")

ENDMACRO()

MACRO(OSG_COMMON_OPTIONS_CONFIGURED)

  OPTION(OSG_ENABLE_CUDA "Build OpenSG with CUDA support" OFF)

ENDMACRO()

MACRO(OSG_COMMON_OPTIONS_DEPRECATED)

ENDMACRO()
