
SET(OSGPREFIX "OSG")

MACRO(OSG_COMMON_CUDA)

  IF(OSG_ENABLE_CUDA)
    IF(CUDA_FOUND)
      SET(OSG_WITH_CUDA 1)
      ADD_CUSTOM_TARGET(OSGAllCudaLibs)
      ADD_DEPENDENCIES(OSGAllLibs OSGAllCudaLibs)
    ENDIF(CUDA_FOUND)
  ELSE(OSG_ENABLE_CUDA)
    SET(OSG_WITH_CUDA 0)
  ENDIF(OSG_ENABLE_CUDA)

  IF(OPENCL_FOUND)
    SET(OSG_WITH_OPENCL)
  ENDIF(OPENCL_FOUND)

ENDMACRO()

MACRO(OSG_COMMON_TARGETS)

  ADD_CUSTOM_TARGET(OSGAll)

  ADD_CUSTOM_TARGET(OSGAllApps)
  ADD_DEPENDENCIES(OSGAll OSGAllApps)

  # optional pass for test programs
  IF(OSGBUILD_TESTS)
    ADD_CUSTOM_TARGET(OSGAllTests)
    ADD_DEPENDENCIES(OSGAll OSGAllTests)
  ENDIF(OSGBUILD_TESTS)

  ADD_CUSTOM_TARGET(OSGAllLibs)
  ADD_CUSTOM_TARGET(OSGAllContribLibs)

  ADD_DEPENDENCIES(OSGAll OSGAllLibs)
  ADD_DEPENDENCIES(OSGAllLibs OSGAllContribLibs)

ENDMACRO()