/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSHADERVARIABLEMATRIXFIELDS_H_
#define _OSGSHADERVARIABLEMATRIXFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class ShaderVariableMatrix;

OSG_GEN_CONTAINERPTR(ShaderVariableMatrix);

/*! \ingroup GrpSystemShaderFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<ShaderVariableMatrix *> :
    public FieldTraitsFCPtrBase<ShaderVariableMatrix *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ShaderVariableMatrix *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFShaderVariableMatrixPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFShaderVariableMatrixPtr"; }
};

template<> inline
const Char8 *FieldTraits<ShaderVariableMatrix *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecShaderVariableMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMatrix *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecShaderVariableMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMatrix *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakShaderVariableMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMatrix *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdShaderVariableMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMatrix *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecShaderVariableMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMatrix *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecShaderVariableMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMatrix *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakShaderVariableMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMatrix *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdShaderVariableMatrixPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemShaderFieldSFields */
typedef PointerSField<ShaderVariableMatrix *,
                      RecordedRefCountPolicy  > SFRecShaderVariableMatrixPtr;
/*! \ingroup GrpSystemShaderFieldSFields */
typedef PointerSField<ShaderVariableMatrix *,
                      UnrecordedRefCountPolicy> SFUnrecShaderVariableMatrixPtr;
/*! \ingroup GrpSystemShaderFieldSFields */
typedef PointerSField<ShaderVariableMatrix *,
                      WeakRefCountPolicy      > SFWeakShaderVariableMatrixPtr;
/*! \ingroup GrpSystemShaderFieldSFields */
typedef PointerSField<ShaderVariableMatrix *,
                      NoRefCountPolicy        > SFUncountedShaderVariableMatrixPtr;


/*! \ingroup GrpSystemShaderFieldMFields */
typedef PointerMField<ShaderVariableMatrix *,
                      RecordedRefCountPolicy  > MFRecShaderVariableMatrixPtr;
/*! \ingroup GrpSystemShaderFieldMFields */
typedef PointerMField<ShaderVariableMatrix *,
                      UnrecordedRefCountPolicy> MFUnrecShaderVariableMatrixPtr;
/*! \ingroup GrpSystemShaderFieldMFields */
typedef PointerMField<ShaderVariableMatrix *,
                      WeakRefCountPolicy      > MFWeakShaderVariableMatrixPtr;
/*! \ingroup GrpSystemShaderFieldMFields */
typedef PointerMField<ShaderVariableMatrix *,
                      NoRefCountPolicy        > MFUncountedShaderVariableMatrixPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemShaderFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecShaderVariableMatrixPtr : 
    public PointerSField<ShaderVariableMatrix *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemShaderFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecShaderVariableMatrixPtr : 
    public PointerSField<ShaderVariableMatrix *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemShaderFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakShaderVariableMatrixPtr :
    public PointerSField<ShaderVariableMatrix *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemShaderFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedShaderVariableMatrixPtr :
    public PointerSField<ShaderVariableMatrix *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemShaderFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecShaderVariableMatrixPtr :
    public PointerMField<ShaderVariableMatrix *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemShaderFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecShaderVariableMatrixPtr :
    public PointerMField<ShaderVariableMatrix *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemShaderFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakShaderVariableMatrixPtr :
    public PointerMField<ShaderVariableMatrix *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemShaderFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedShaderVariableMatrixPtr :
    public PointerMField<ShaderVariableMatrix *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSHADERVARIABLEMATRIXFIELDS_H_ */
