/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSHADERVARIABLEFUNCTORFIELDS_H_
#define _OSGSHADERVARIABLEFUNCTORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class ShaderVariableFunctor;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! ShaderVariableFunctorPtr

OSG_GEN_CONTAINERPTR(ShaderVariableFunctor);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpSystemFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<ShaderVariableFunctor *> :
    public FieldTraitsFCPtrBase<ShaderVariableFunctor *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ShaderVariableFunctor *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFShaderVariableFunctorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFShaderVariableFunctorPtr"; }
};

template<> inline
const Char8 *FieldTraits<ShaderVariableFunctor *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecShaderVariableFunctorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableFunctor *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecShaderVariableFunctorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableFunctor *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakShaderVariableFunctorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableFunctor *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdShaderVariableFunctorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableFunctor *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecShaderVariableFunctorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableFunctor *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecShaderVariableFunctorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableFunctor *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakShaderVariableFunctorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableFunctor *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdShaderVariableFunctorPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<ShaderVariableFunctorPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpSystemFieldSingle */

typedef PointerSField<ShaderVariableFunctor *,
                      RecordedRefCountPolicy  > SFRecShaderVariableFunctorPtr;
typedef PointerSField<ShaderVariableFunctor *,
                      UnrecordedRefCountPolicy> SFUnrecShaderVariableFunctorPtr;
typedef PointerSField<ShaderVariableFunctor *,
                      WeakRefCountPolicy      > SFWeakShaderVariableFunctorPtr;
typedef PointerSField<ShaderVariableFunctor *,
                      NoRefCountPolicy        > SFUncountedShaderVariableFunctorPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpSystemFieldMulti */

typedef PointerMField<ShaderVariableFunctor *,
                      RecordedRefCountPolicy  > MFRecShaderVariableFunctorPtr;
typedef PointerMField<ShaderVariableFunctor *,
                      UnrecordedRefCountPolicy> MFUnrecShaderVariableFunctorPtr;
typedef PointerMField<ShaderVariableFunctor *,
                      WeakRefCountPolicy      > MFWeakShaderVariableFunctorPtr;
typedef PointerMField<ShaderVariableFunctor *,
                      NoRefCountPolicy        > MFUncountedShaderVariableFunctorPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGSHADERVARIABLEFUNCTORFIELDS_H_ */
