/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSHADERVARIABLEMMATRIXFIELDS_H_
#define _OSGSHADERVARIABLEMMATRIXFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class ShaderVariableMMatrix;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! ShaderVariableMMatrixPtr

OSG_GEN_CONTAINERPTR(ShaderVariableMMatrix);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpSystemFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<ShaderVariableMMatrix *> :
    public FieldTraitsFCPtrBase<ShaderVariableMMatrix *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ShaderVariableMMatrix *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFShaderVariableMMatrixPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFShaderVariableMMatrixPtr"; }
};

template<> inline
const Char8 *FieldTraits<ShaderVariableMMatrix *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecShaderVariableMMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMMatrix *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecShaderVariableMMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMMatrix *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakShaderVariableMMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMMatrix *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdShaderVariableMMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMMatrix *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecShaderVariableMMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMMatrix *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecShaderVariableMMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMMatrix *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakShaderVariableMMatrixPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariableMMatrix *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdShaderVariableMMatrixPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<ShaderVariableMMatrixPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpSystemFieldSingle */

typedef PointerSField<ShaderVariableMMatrix *,
                      RecordedRefCountPolicy  > SFRecShaderVariableMMatrixPtr;
typedef PointerSField<ShaderVariableMMatrix *,
                      UnrecordedRefCountPolicy> SFUnrecShaderVariableMMatrixPtr;
typedef PointerSField<ShaderVariableMMatrix *,
                      WeakRefCountPolicy      > SFWeakShaderVariableMMatrixPtr;
typedef PointerSField<ShaderVariableMMatrix *,
                      NoRefCountPolicy        > SFUncountedShaderVariableMMatrixPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpSystemFieldMulti */

typedef PointerMField<ShaderVariableMMatrix *,
                      RecordedRefCountPolicy  > MFRecShaderVariableMMatrixPtr;
typedef PointerMField<ShaderVariableMMatrix *,
                      UnrecordedRefCountPolicy> MFUnrecShaderVariableMMatrixPtr;
typedef PointerMField<ShaderVariableMMatrix *,
                      WeakRefCountPolicy      > MFWeakShaderVariableMMatrixPtr;
typedef PointerMField<ShaderVariableMMatrix *,
                      NoRefCountPolicy        > MFUncountedShaderVariableMMatrixPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGSHADERVARIABLEMMATRIXFIELDS_H_ */
