/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSHADERVARIABLEPNT2FFIELDS_H_
#define _OSGSHADERVARIABLEPNT2FFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ShaderVariablePnt2f;

OSG_GEN_CONTAINERPTR(ShaderVariablePnt2f);
/*! \ingroup GrpSystemShaderFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<ShaderVariablePnt2f *, nsOSG> :
    public FieldTraitsFCPtrBase<ShaderVariablePnt2f *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ShaderVariablePnt2f *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ShaderVariablePnt2f *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecShaderVariablePnt2fPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariablePnt2f *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecShaderVariablePnt2fPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariablePnt2f *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakShaderVariablePnt2fPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariablePnt2f *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdShaderVariablePnt2fPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariablePnt2f *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecShaderVariablePnt2fPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariablePnt2f *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecShaderVariablePnt2fPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariablePnt2f *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakShaderVariablePnt2fPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderVariablePnt2f *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdShaderVariablePnt2fPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemShaderFieldSFields */
typedef PointerSField<ShaderVariablePnt2f *,
                      RecordedRefCountPolicy, nsOSG  > SFRecShaderVariablePnt2fPtr;
/*! \ingroup GrpSystemShaderFieldSFields */
typedef PointerSField<ShaderVariablePnt2f *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecShaderVariablePnt2fPtr;
/*! \ingroup GrpSystemShaderFieldSFields */
typedef PointerSField<ShaderVariablePnt2f *,
                      WeakRefCountPolicy, nsOSG      > SFWeakShaderVariablePnt2fPtr;
/*! \ingroup GrpSystemShaderFieldSFields */
typedef PointerSField<ShaderVariablePnt2f *,
                      NoRefCountPolicy, nsOSG        > SFUncountedShaderVariablePnt2fPtr;


/*! \ingroup GrpSystemShaderFieldMFields */
typedef PointerMField<ShaderVariablePnt2f *,
                      RecordedRefCountPolicy, nsOSG  > MFRecShaderVariablePnt2fPtr;
/*! \ingroup GrpSystemShaderFieldMFields */
typedef PointerMField<ShaderVariablePnt2f *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecShaderVariablePnt2fPtr;
/*! \ingroup GrpSystemShaderFieldMFields */
typedef PointerMField<ShaderVariablePnt2f *,
                      WeakRefCountPolicy, nsOSG      > MFWeakShaderVariablePnt2fPtr;
/*! \ingroup GrpSystemShaderFieldMFields */
typedef PointerMField<ShaderVariablePnt2f *,
                      NoRefCountPolicy, nsOSG        > MFUncountedShaderVariablePnt2fPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemShaderFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecShaderVariablePnt2fPtr : 
    public PointerSField<ShaderVariablePnt2f *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemShaderFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecShaderVariablePnt2fPtr : 
    public PointerSField<ShaderVariablePnt2f *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemShaderFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakShaderVariablePnt2fPtr :
    public PointerSField<ShaderVariablePnt2f *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemShaderFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedShaderVariablePnt2fPtr :
    public PointerSField<ShaderVariablePnt2f *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemShaderFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecShaderVariablePnt2fPtr :
    public PointerMField<ShaderVariablePnt2f *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemShaderFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecShaderVariablePnt2fPtr :
    public PointerMField<ShaderVariablePnt2f *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemShaderFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakShaderVariablePnt2fPtr :
    public PointerMField<ShaderVariablePnt2f *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemShaderFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedShaderVariablePnt2fPtr :
    public PointerMField<ShaderVariablePnt2f *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSHADERVARIABLEPNT2FFIELDS_H_ */
