/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPERSPECTIVECAMERAFIELDS_H_
#define _OSGPERSPECTIVECAMERAFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PerspectiveCamera;

OSG_GEN_CONTAINERPTR(PerspectiveCamera);

/*! \ingroup GrpSystemWindowFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<PerspectiveCamera *> :
    public FieldTraitsFCPtrBase<PerspectiveCamera *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PerspectiveCamera *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPerspectiveCameraPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPerspectiveCameraPtr"; }
};

template<> inline
const Char8 *FieldTraits<PerspectiveCamera *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPerspectiveCameraPtr"; 
}

template<> inline
const Char8 *FieldTraits<PerspectiveCamera *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPerspectiveCameraPtr"; 
}

template<> inline
const Char8 *FieldTraits<PerspectiveCamera *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPerspectiveCameraPtr"; 
}

template<> inline
const Char8 *FieldTraits<PerspectiveCamera *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPerspectiveCameraPtr"; 
}

template<> inline
const Char8 *FieldTraits<PerspectiveCamera *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPerspectiveCameraPtr"; 
}

template<> inline
const Char8 *FieldTraits<PerspectiveCamera *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPerspectiveCameraPtr"; 
}

template<> inline
const Char8 *FieldTraits<PerspectiveCamera *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPerspectiveCameraPtr"; 
}

template<> inline
const Char8 *FieldTraits<PerspectiveCamera *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPerspectiveCameraPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemWindowFieldSFields */
typedef PointerSField<PerspectiveCamera *,
                      RecordedRefCountPolicy  > SFRecPerspectiveCameraPtr;
/*! \ingroup GrpSystemWindowFieldSFields */
typedef PointerSField<PerspectiveCamera *,
                      UnrecordedRefCountPolicy> SFUnrecPerspectiveCameraPtr;
/*! \ingroup GrpSystemWindowFieldSFields */
typedef PointerSField<PerspectiveCamera *,
                      WeakRefCountPolicy      > SFWeakPerspectiveCameraPtr;
/*! \ingroup GrpSystemWindowFieldSFields */
typedef PointerSField<PerspectiveCamera *,
                      NoRefCountPolicy        > SFUncountedPerspectiveCameraPtr;


/*! \ingroup GrpSystemWindowFieldMFields */
typedef PointerMField<PerspectiveCamera *,
                      RecordedRefCountPolicy  > MFRecPerspectiveCameraPtr;
/*! \ingroup GrpSystemWindowFieldMFields */
typedef PointerMField<PerspectiveCamera *,
                      UnrecordedRefCountPolicy> MFUnrecPerspectiveCameraPtr;
/*! \ingroup GrpSystemWindowFieldMFields */
typedef PointerMField<PerspectiveCamera *,
                      WeakRefCountPolicy      > MFWeakPerspectiveCameraPtr;
/*! \ingroup GrpSystemWindowFieldMFields */
typedef PointerMField<PerspectiveCamera *,
                      NoRefCountPolicy        > MFUncountedPerspectiveCameraPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemWindowFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecPerspectiveCameraPtr : 
    public PointerSField<PerspectiveCamera *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemWindowFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecPerspectiveCameraPtr : 
    public PointerSField<PerspectiveCamera *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemWindowFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakPerspectiveCameraPtr :
    public PointerSField<PerspectiveCamera *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemWindowFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedPerspectiveCameraPtr :
    public PointerSField<PerspectiveCamera *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemWindowFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecPerspectiveCameraPtr :
    public PointerMField<PerspectiveCamera *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemWindowFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecPerspectiveCameraPtr :
    public PointerMField<PerspectiveCamera *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemWindowFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakPerspectiveCameraPtr :
    public PointerMField<PerspectiveCamera *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemWindowFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedPerspectiveCameraPtr :
    public PointerMField<PerspectiveCamera *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPERSPECTIVECAMERAFIELDS_H_ */
